woowacourse-teams/2024-haeng-dong

client/.eslintrc.json
client/.gitignore
client/.npmrc
client/.prettierrc
client/index.html
client/package-lock.json
client/package.json
client/src/App.tsx
client/src/index.tsx
client/tsconfig.json
client/webpack.config.js

프로젝트를 위한 webpack, eslint, prettier에 대한 기본 세팅을 완료했어요.
- #2

webpack, eslint, prettier 기본 세팅 완료

---

client/.npmrc
client/.prettierrc
client/package-lock.json
client/package.json
client/src/App.tsx
client/tsconfig.json
client/webpack.config.js

emotion 초기 세팅

---

.github/workflows/backend-pull-request.yml
.github/workflows/backend-push.yml
server/Dockerfile
server/src/main/java/server/haengdong/domain/CiCd.java

- close #22 
- 백엔드 CI 구축
- 백엔드 CD 구축
PR 테스트는 못해봤습니다.

[BE] CI/CD 파이프라인 구축

---

.github/workflows/backend-pull-request.yml

- close #55
pr에서 테스트 리포트를 볼 수 있는 기능을 추가했습니다.

[BE] PR 후 테스트 리포트 발행 기능 추가

---

client/src/apis/fetcher.ts

- close #66 
공통 api wrapping 로직 작성
추후 api 연결 후 구체화 및 디벨롭

[FE] api wrapping

---

client/package-lock.json
client/package.json
client/webpack.config.js

- close #73
@svgr/webpack 설치 및 webpack.config.js 수정

[FE] @svgr/webpack 플러그인 설치

---

.github/workflows/backend-push.yml
.gitmodules
server/Dockerfile
server/src/main/resources/application.yml
server/src/test/resources/application.yml

[BE] 설정 파일 서브 모듈 생성

---

server/src/main/java/server/haengdong/presentation/EventController.java

- close #85 
- events Controller 파라미터에 `@RequestBody` 추가

[BE] 요청 데이터가 맵핑되지 않는 문제 해결

---

server/src/main/java/server/haengdong/config/WebConfig.java
server/src/main/resources/application.yml
server/src/test/resources/application.yml

[BE] CORS 설정

---

server/src/main/java/server/haengdong/presentation/response/StepResponse.java

[BE] 액션 이력이 없는 경우 빈 리스트 반환

---

server/src/main/java/server/haengdong/application/EventService.java
server/src/main/java/server/haengdong/domain/action/MemberActionStatus.java
server/src/main/java/server/haengdong/presentation/response/StepResponse.java

[BE] 액션 이력 조회 오류 수정

---

.github/workflows/backend-pull-request.yml
.github/workflows/backend-push.yml
server/src/main/java/server/haengdong/HaengdongApplication.java

[BE] Gradle, Docker 캐싱을 위한 Feature/#121 test

---

.github/workflows/backend-pull-request.yml
.github/workflows/backend-push.yml
server/src/main/java/server/haengdong/HaengdongApplication.java

[BE] Gardle, Docker 캐싱을 위한 Feature/#121 test2

---

.github/workflows/backend-push.yml
server/Dockerfile

gradle build test

---

server/src/main/java/server/haengdong/HaengdongApplication.java

gradle build test2

---

.github/workflows/backend-push.yml

[BE] 애플리케이션 도커 포트 번호 수정

---

.github/workflows/backend-push.yml

- close #136
도커 계정 관련 정보를 github secrets로 수정했습니다.

[BE] 도커 관련 정보 secrets로 수정

---

.github/workflows/backend-pull-request.yml
.github/workflows/backend-push.yml

- close #151 
CI/CD시 gradlew 권한 문제로 빌드에 실패하는 버그를 
gradlew 권한을 부여하는 step를 추가하여 수정했습니다.

[BE]: gradle 빌드 실패 버그

---

.github/workflows/backend-dev.yml
.github/workflows/backend-prod.yml
.github/workflows/backend-pull-request.yml
.gitmodules
server/Dockerfile
server/src/main/java/server/haengdong/HaengdongApplication.java
server/src/main/resources/application.yml

- close #147 
github workflow dev, prod yml 분리 및 dev, prod ec2, db mysql 설정.

 [BE] CD workflow main, develop 분리

---

.github/workflows/design-pull-request.yml
.github/workflows/frontend-pull-request.yml

- close #164 
branch 변경에 따른 github workflow 수정

[FE] branch 변경에 따른 github workflow 수정

---

.github/workflows/design-pull-request.yml

- close #167
yml을 수정하고,
github secrets에 CHROMATIC_PROJECT_TOKEN값을 추가했습니다.

[FE] 스토리북 워크플로우 오류

---

server/src/main/java/server/haengdong/config/AdminInterceptor.java

[BE] 로그인 토큰 인증 오류

---

server/src/main/java/server/haengdong/config/AdminInterceptor.java
server/src/main/java/server/haengdong/config/WebMvcConfig.java
server/src/main/java/server/haengdong/infrastructure/auth/CookieProperties.java
server/src/main/java/server/haengdong/presentation/EventController.java
server/src/main/resources/application.yml

- close #233 
쿠키에 SameSite=none 속성을 추가하여 다른 도메인에서 쿠키를 저장 할 수 있게 변경했습니다.
CORS 설정에 withCredentials=true 를 추가하여 다른 도메인에서 쿠키나 인증 헤더를 받을 수 있게 변경했습니다.

[BE] 쿠키 저장 오류 2차 수정

---

client/src/apis/fetcher.ts
client/src/apis/request/event.ts
client/src/components/StepList/BillStepItem.tsx
client/src/hooks/useEvent.tsx
client/src/index.tsx
client/src/pages/CreateEventPage/SetEventNamePage.tsx
client/src/pages/CreateEventPage/SetEventPasswordPage.tsx

- close #244
- webpack merge 설치
- useEvent에서 eventName 타입 에러
- BillStepItemProps에서 setOpenBottomSheet 에러
- requestPost 분기 처리 추가

[FE] merge를 통해 발생한 에러 해결

---

server/src/main/resources/application.yml

- close #247 
JWT 유효기간을 7일로 설정했습니다.

[BE] JWT 유효기간 만료 버그 수정

---

HDesign/package-lock.json
HDesign/package.json
HDesign/src/components/Input/useInput.ts

- close #252 
행동디자인 useInput에서 props value가 변했을 때 setValue가 호출되도록 수정했어요!

[FE] input value 수정이 되지 않는 문제

---

.github/workflows/backend-pull-request.yml
server/src/docs/asciidoc/event.adoc
server/src/main/java/server/haengdong/presentation/EventController.java
server/src/test/java/server/haengdong/docs/EventControllerDocsTest.java

- close #256 
<h3 id="_행사_어드민_권한_확인 API" style="box-sizing: border-box; margin: 1em 0px 0.5em; padding: 0px; font-family: &quot;Open Sans&quot;, &quot;DejaVu Sans&quot;, sans-serif; font-weight: 300; font-style: normal; color: rgb(204, 204, 204); text-rendering: optimizelegibility; line-height: 1.2; font-size: 1.375em; word-spacing: -0.05em; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(69, 73, 74); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">행사 어드민 권한 확인</h3><div class="sect3" style="box-sizing: border-box; margin: 0px; padding: 0px; color: …

[BE] 관리자 권한 확인 API 구현

---

client/package-lock.json
client/package.json
client/src/pages/CreateEventPage/CompleteCreateEventPage.tsx

- close #145 
- 현재 우리 서비스는 로그인, 로그아웃 기능이 없이 유저가 생성한 행사에 대해서 링크를 통해서만 접근이 가능함
- 하지만 처음 행사를 생성했을 때 관리 링크를 보관하라는 안내를 작성해 주지만 눈에 띄지 않음
- 또한 직접 url을 복사해야 하기 때문에 이 과정이 유저가 원하는 대로 행동하기 쉽지 않게 함
- 링크를 보관하라는 UX writing을 더 눈에 띄는 계층 구조로 변경
- 링크 복사 버튼을 통해서 쉽게 링크를 복사할 수 있는 기능 추가
- 링크 복사가 완료되었다는 상태를 유저에게 알려줄 수 있는 기능 추가
- 클립보드에 복사하는 방법
- `document.execCommand("copy")` 메소드 사용
- `navigate.clipboard.writeText(text)` 메소드 사용
- [react-copy-to-clipboard](https://www.npmjs.com/package/react-copy-to-clipboard) 라이브러리 사용
1. **브라우저 호환성 보장**:
- `navigator.clipboard.writeText` 메서드는 일부 모바일 환경에서 보안상의 이유로 특정 브라우저 및 버전에서 호환성 문제가 있을 수 있습니다. 특히, HTTPS 환경에서만 작동하고 사용자 제스처 내에서 호출되어야 합니다. `react-copy-to-clipboard` 라이브러리는 이러한 제한 사항을 해결하여 다양한 브라우저 환경에서 안정적으로 작동합니다.
2. **deprecated된 메서드 사용 지양**:
- `document.execCommand("copy")` …

[FE] 행사 생성 완료 페이지 유저 친화적으로 변경

---

HDesign/package-lock.json
HDesign/package.json
client/package-lock.json
client/package.json
client/src/apis/fetcher.ts
client/src/apis/request/auth.ts
client/src/apis/request/member.ts
client/src/components/Modal/SetAllMemberListModal/SetAllMemberListModal.tsx
client/src/hooks/useAuth.tsx
client/src/index.tsx
client/src/pages/EventPage/AdminPage/EventLoginPage.tsx
client/src/utils/sendLogToSentry.ts

- close #277
3차 데모데이 merge 중 발생한 문제 수정했습니다.

[FE] 3차 데모데이 merge 중 발생한 문제 수정

---

client/src/pages/EventPage/AdminPage/AdminPage.tsx
client/src/pages/MainPage/MainPage.tsx

- close #287 
랜딩 페이지에 데모데이 키워드를 넣었습니다

[FE] 데모데이를 위해 페이지 약간 수정

---

.github/workflows/backend-dev.yml
.github/workflows/backend-pull-request.yml

- close #307
CI 와 개발 서버 CD 트리거 조건에서 server 폴더 조건 제거했습니다.

[BE] CI/CD 트리거 조건에서 server 폴더 조건 제거 

---

.github/workflows/pr-issue-close.yml

- close #306 
github actions를 사용하여 pr merge 시 issue를 자동으로 닫는 workflow 를 작성했습니다.
망쵸의 토큰을 빌렸습니다.

[ALL] pr 머지시 issue close 기능 추가

---

client/package-lock.json
client/package.json
client/src/components/Modal/SetActionModal/PutAndDeleteBillActionModal/PutAndDeleteBillActionModal.tsx
client/src/components/StepList/BillStepItem.tsx

- close #316 
행동디자인 반영 대기로 임시 버튼이 있었는데 행동디자인 최신 버전에 반영되어서 임시 버튼을 삭제하고 반영시켰습니다.
중괄호 export 문제도 살짝 껴서ㅎㅎㅎ

[FE] 참여 인원 확인 임시 버튼 삭제

---

.github/workflows/backend-dev.yml
.github/workflows/backend-prod.yml

- close #296 
서버의 로그 파일 영속화 및 모니터링을 위한 볼륨 마운트 설정을 추가했습니다.
EC2 내부 경로 : /home/ubuntu/log
컨테이너 내부 경로 : /app/logs
cloudwatch agent의 config 설정에  /home/ubuntu/log/spring-application.log 를 등록하여 모니터링이 가능합니다.
개발 서버는 agent의  config설정이 되어있지만 운영 서버는 되어있지 않아 작업이 필요합니다.

[BE] 서버 로그 볼륨 마운트 설정

---

.github/workflows/pr-issue-close.yml

- close #306 
github actions를 사용하여 pr merge 시 issue를 자동으로 닫는 workflow 를 작성했습니다.
fe-dev 에도 추가합니다.

[ALL] pr issue close workflow 생성

---

server/src/main/java/server/haengdong/application/BillActionDetailService.java
server/src/main/java/server/haengdong/domain/action/BillActionDetail.java
server/src/main/java/server/haengdong/domain/action/BillActionDetailRepository.java
server/src/main/java/server/haengdong/presentation/BillActionDetailController.java

[BE] BillActionDetail 엔티티 추가

---

client/src/pages/CreateEventPage/CompleteCreateEventPage.tsx

- close #380 
행사 생성 완료 페이지 머지하면서 잘못된 코드 수정했어요
eventId를 넣어서 주소를 만들어줘야 했는데 그렇지 못하고 있어서 수정했습니다~

[FE] 행사 생성 완료 페이지 머지하면서 잘못된 코드 수정

---

server/src/main/java/server/haengdong/exception/GlobalExceptionHandler.java
server/src/main/java/server/haengdong/presentation/BillActionController.java
server/src/main/java/server/haengdong/presentation/request/BillActionDetailsUpdateRequest.java
server/src/main/java/server/haengdong/presentation/request/BillActionsSaveRequest.java
server/src/main/java/server/haengdong/presentation/request/MemberActionsSaveRequest.java
server/src/main/java/server/haengdong/presentation/request/MemberNamesUpdateRequest.java

- close #336 
- 리스트 형태의 요청 바디에 null을 넣으면 500이 뜨는 에러 수정
- 로그를 json 형태로 수정

[BE] 예외 처리 및 로깅 형식 수정

---

client/src/hooks/useDynamicInput.tsx
client/src/utils/validate/validateMemberName.ts

- close #393 
useDynamicInput에 넘겨준 유효성 검사 함수에 문제가 있었습니다.
value의 길이가 1이하면 유효성 검사 결과가 invalid로 나가는 것이 문제였습니다.
따라서 이 조건을 제거했습니다.

[FE] Input이 완전히 비워지지 않는 버그

---

server/src/main/java/server/haengdong/presentation/response/StepResponse.java
server/src/main/java/server/haengdong/presentation/response/StepsResponse.java
server/src/test/java/server/haengdong/docs/EventControllerDocsTest.java
server/src/test/java/server/haengdong/presentation/response/StepsResponseTest.java

- close #419 
액션 이력 조회 stepName

[BE] 액션 이력 조회 stepName 추가

---

client/src/hooks/useMemberReportListInAction/useMemberReportInput.tsx
client/src/hooks/useMemberReportListInAction/useMemberReportListInAction.ts

- close #427 
차등 적용 can submit이 valid 하지만 false되는 버그를 해결했어요.
추가로 데이터가 없을 때 reCalculate가 돌지 않도록 수정했어요.

[FE] 차등 적용 can submit이 valid 하지만 false되는 버그

---

HDesign/src/components/BottomSheet/BottomSheet.tsx
HDesign/src/components/DragHandleItem/DragHandleItem.stories.tsx
HDesign/src/components/DragHandleItem/DragHandleItem.tsx
HDesign/src/components/DragHandleItem/DragHandleItem.type.ts
HDesign/src/components/EditableItem/EditableItem.Input.style.ts
HDesign/src/components/EditableItem/EditableItem.Input.tsx
HDesign/src/components/IsFixedIcon/IsFixedIcon.style.ts
HDesign/src/components/IsFixedIcon/IsFixedIcon.tsx
client/package-lock.json
client/package.json
client/src/components/Modal/SetActionModal/PutAndDeleteBillActionModal/PutAndDeleteBillActionModal.tsx
client/src/hooks/usePutAndDeleteBillAction.ts

- close #410 
지출 내역 아이템 클릭 시 뜨는 차등 정산 모달을 퍼블리싱했습니다.
https://github.com/user-attachments/assets/e98bcde8-7d22-45c6-804f-90c40230490d

[FE] 지출 내역 아이템 클릭시 뜨는 차등 정산 모달 퍼블리싱

---

client/src/hooks/useDynamicInput.tsx
client/src/pages/MainPage/Nav/Nav.style.ts
client/src/pages/MainPage/Nav/Nav.tsx

- close #437
데스크탑에서도 Nav가 정상적으로 출력되도록 maxWidth를 추가했습니다.

[FE] 랜딩페이지 Nav 버그 수정

---

client/src/GlobalStyle.ts

[FE] 배경 색 문제

---

client/index.html

- close #242 
amplitude를 적용해봤어요. 공식문서대로 index.html에 코드를 스윽했습니다.
디스코드에 있는 amplitude key env 추가해야합니다.
린트 문제 있다고 해서 다시 올렸어요

[FE] amplitude 적용

---

HDesign/package-lock.json
HDesign/package.json
client/package-lock.json
client/package.json
client/src/pages/CreateEventPage/SetEventPasswordPage.tsx

- close #502 
비밀번호 4자리 넘게 적용되던 오류를 해결했습니다.

[FE] 비밀번호 4자리 넘게 적용되는 오류 수정

---

client/src/components/StepList/BillStepItem.tsx
client/src/pages/MainPage/Nav/Nav.tsx

- close #512 
커밋 두개가 알아서 말하고 있음 ㅅㄱ

[FE] build를 위한 없는 파일 import 제거

---

client/index.html

- close #514 
행동 디자인 이미지 og tag 해상도에 맞춰서 변경했어요.

[FE] OG태그 이미지 해상도 변경

---

client/package-lock.json
client/package.json

[FE] 라이버러리 버전 업데이트

---

server/src/main/java/server/haengdong/config/AdminInterceptor.java
server/src/test/java/server/haengdong/config/AdminInterceptorTest.java

- close #571 
eventToken 을 추출하는 로직이 잘못되어 정규표현식으로 추출하는 방법으로 수정합니다.

[BE] 관리자 인증 불가 버그 수정

---

server/src/main/java/server/haengdong/application/MemberService.java
server/src/test/java/server/haengdong/application/ServiceTestSupport.java

- close #588
read-only 트랜잭션을 수정했습니다.

[BE] 행사 멤버 추가 시 500 에러 발생

---

server/src/main/java/server/haengdong/domain/bill/Bill.java
server/src/main/java/server/haengdong/domain/bill/BillDetailRepository.java
server/src/main/java/server/haengdong/domain/bill/BillRepository.java
server/src/test/java/server/haengdong/application/BillServiceTest.java

- close #596
fetch join 을 사용하여 N + 1 문제를 해결했습니다.

[BE] N+1문제 fetch join으로 쿼리 최적화

---

client/src/components/StepList/Step.stories.tsx
client/src/components/StepList/Step.tsx
client/src/components/StepList/Steps.tsx

- close #603 
홈에서 지출 상세로 넘어가지 않도록 isAdmin prop을 추가했습니다.

[FE] 홈에서 지출 상세 수정 가능한 버그

---

client/src/hooks/useMembersStep.ts

- close #675 
#622 
#637 
에서 구현한 내용이 사라져 다시 적용합니다.

[FE] 지출 생성 시 나갔던 멤버를 다시 추가할 수 없는 오류

---

server/src/docs/asciidoc/event.adoc

- close #721 
누락된 adoc을 추가합니다.

[BE] 행사 이미지 추가, 조회, 삭제 Rest Docs 추가

---

client/index.html

- close #695 
- 행동대장의 핵심 이용자들의 의견을 들어본 결과, url을 외우고 다니지 않는 이상 행동대장 서비스에 접근하기 어렵다는 피드백이 있었습니다.
- url로 접근하지 않아도 검색을 통해 접근할 수 있는 활로를 열기 위해 기초적인 단계인 meta 태그 작성이 필요합니다.
- 필요한 meta 들을 작성하였습니다.
- google에 도메인 소유권 인증을 진행하였습니다.
안녕하세요! 각 메타 태그와 링크 태그의 역할을 주니어 개발자들을 대상으로 이해하기 쉽게 설명해 드리겠습니다.
---
**역할:**
- **문자 인코딩 지정**: 이 태그는 웹 페이지에서 사용되는 문자 인코딩 방식을 지정합니다.
- **UTF-8 설정**: UTF-8은 전 세계 대부분의 언어를 표현할 수 있는 표준 인코딩 방식입니다.
**이유:**
- **문자 깨짐 방지**: UTF-8을 사용하면 한글이나 다른 언어의 문자가 깨지지 않고 제대로 표시됩니다.
- **다국어 지원**: 다양한 언어를 사용하는 사용자들에게 올바른 콘텐츠를 제공합니다.
---
**역할:**
- **페이지 제목 설정**: 브라우저 탭이나 검색 엔진 결과에 표시되는 페이지의 제목을 지정합니다.
- **검색 엔진 최적화(SEO)**: 검색 결과에서 사용자가 볼 수 있는 중요한 정보로, 검색 순위에 영향을 미칠 수 있습니다.
**이유:**
- **서비스 소개**: '행동대장'의 핵심 기능과 혜택을 강조하여 사용자에게 어필합니다.
- **키워드 포함**: 중요한 키워드를 포함하여 검색 엔진에서의 가시성을 높입니다.
---
**역할:**
- **페이지 설명 …

[FE] 검색엔진 최적화를 위한 meta 태그 작성

---

client/src/components/Design/components/BankSelect/BankSelect.tsx
client/src/constants/bank.ts

- close #708 
토스에서 허용하지 않는 이름으로 보내주어서 버그가 발생한 것 같아요.
그래서 토스의 입력 값으로 은행 이름을 바꿨습니다.

[FE] 토스에서 은행 이름 인식하지 않는 버그

---

.github/workflows/backend-dev.yml

chore: 테스트용 트리거 브랜치 삭제

---

.github/workflows/backend-prod.yml

hofix: 운영 포트 수정

---

.github/workflows/backend-prod.yml

- close #n
서버 CD 트리거에 `.github/workflows/**` 추가합니다.

hotfix: 서버 CD 트리거 수정

---

client/src/components/Design/components/IconButton/IconButton.stories.tsx
client/src/components/Design/components/NumberKeyboard/useNumberKeyboard.tsx
client/src/hooks/useAdminPage.ts

- close #762 
[FE] v2.1.1 배포 과정에서의 문제를 해결했습니다.
merge 과정에서 IconButton에 삭제했던 불주사가 다시 부활하여 삭제하였습니다.
useBanner가 import되고 있지 않았습니다.

[FE] v2.1.1 배포 과정에서의 문제 해결

---

.github/workflows/backend-prod.yml
server/src/main/resources/application.yml

[BE] blue green 무중단 배포

---

server/src/main/resources/application.yml

- close #789 
tomcat max-thread : 200 -> 50 으로 변경하여 TPS를 개선합니다.
TPS : 460 -> 540

[BE] tomcat max-thread 변경

---

client/src/pages/MainPage/Section/FeatureSection/AutoCalculate/AutoCalculate.style.ts
client/src/pages/MainPage/Section/FeatureSection/AutoCalculate/AutoCalculate.tsx
client/src/pages/MainPage/Section/FeatureSection/CheckDeposit/CheckDeposit.style.ts
client/src/pages/MainPage/Section/FeatureSection/CheckDeposit/CheckDeposit.tsx
client/src/pages/MainPage/Section/FeatureSection/RecordMemoryWithPhoto/RecordMemoryWithPhoto.tsx
client/src/pages/MainPage/Section/FeatureSection/SimpleShare/SimpleShare.tsx
client/src/pages/MainPage/Section/FeatureSection/SimpleTransfer/SimpleTransfer.style.ts
client/src/pages/MainPage/Section/FeatureSection/SimpleTransfer/SimpleTransfer.tsx

 [FE] 랜딩페이지 사진의 layout이 맞지 않는 문제

---

README.md

- close #799 
인프라 구성도 및 CI/CD 파이프라인 그림을 추가합니다.

[ALL] infra 구성도 및 CI/CD 파이프라인 추가

---

client/src/apis/request/event.ts

- close #881
'/api/users' -> 'api/events'로 수정합니다.

[FE] 올바른 엔드포인트를 사용하지 않는 문제

---

server/src/main/java/haengdong/event/application/EventService.java
server/src/main/java/haengdong/event/application/request/EventDeleteAppRequest.java
server/src/main/java/haengdong/event/domain/event/Event.java
server/src/main/java/haengdong/event/presentation/EventController.java
server/src/main/java/haengdong/event/presentation/request/EventDeleteRequest.java
server/src/main/resources/logback-spring.xml

- close #900 
행사 여러개 삭제 API를 구현합니다.
DELETE /api/events
Cookie
accessToken=jwtToken;
```json
{
"eventIds" : [ "eevew029fdsf", "fgew029fdsf", "343vew029fdsf" ]
}
```

[BE] 행사 삭제 기능 구현

---

client/src/components/Design/components/Box/Box.stories.tsx
client/src/components/Design/components/Box/Box.style.ts
client/src/components/Design/components/Box/Box.tsx
client/src/components/Design/components/Box/Box.type.ts
client/src/components/Design/components/Container/Container.stories.tsx
client/src/components/Design/components/Container/Container.style.ts
client/src/components/Design/components/Container/Container.tsx
client/src/components/Design/components/Container/Container.type.ts
client/src/components/Design/components/Stack/HStack.stories.tsx
client/src/components/Design/components/Stack/HStack.tsx
client/src/components/Design/components/Stack/Stack.stories.tsx
client/src/components/Design/components/Stack/Stack.style.ts
client/src/components/Design/components/Stack/Stack.tsx
client/src/components/Design/components/Stack/Stack.type.ts
client/src/components/Design/components/Stack/VStack.stories.tsx
client/src/components/Design/components/Stack/VStack.tsx
client/src/components/Design/utils/attribute.ts

- close #898 
div에 flex css를 적용하는 번거로운 과정을 덜기 위해 Flex component를 구현하였습니다.
하지만, 디테일한 css 설정이 필요해 제대로 사용하지 못하거나, 
특히, 디테일한 css 설정이 필요한 경우를 모두 대응하지 못해 div를 flex로 만들어서 사용하는 경우가 많았습니다.
이에 다양한 상황에 대응할 수 있는 pattern component들을 구현하고, 해당 component들에 대한 문서화를 진행했습니다.
- Box Component
width, height를 고정할 수 있는 div 대용
ex) 구분선 만들기, 이미지 특정 크기에 가두기, fixed dimmedLayer 만들기 등
- Container Component
width 100%, maxWidh 제한, height auto 인 div
ex) 좌우 width를 고정하는 반응형 layout, 이름의 길이가 넘어가지 않도록 감싸기 등
- Stack Component
width, height, align, justify를 유동적으로 수정할 수 있는 flex div
ex) 디테일한 커스텀 레이아웃이 필요한 경우, HStack, VStack을 사용할 수 없는 경우
- HStack Component
width 100%, height auto, align center인 flex div
ex) ListItem의 좌우 항목 배치, Header 구현 등
- VStack Component
widht 100%, height auto, justify center인 flex div
ex) ListItem을 세로로 배치하여 …

[FE] Flex component 개선

---

client/src/pages/mypage/MyPage.tsx

- close #908 
마이페이지에서 계좌 수정 페이지에 진입할 수 있도록 onClick과 useNavigete로 라우트를 연결합니다.

[FE] 마이페이지에서 계좌 수정 페이지 연결

---

client/cypress/constants/constants.ts
client/cypress/e2e/createEvent.cy.ts
client/cypress/e2e/createEventByGuest.cy.ts
client/cypress/support/commands.ts

- close #926 
로그인 도입 후 플로우가 바뀌어 cypress 코드를 주석 처리가 되었습니다.
하지만 CI 과정에서 e2e 테스트 과정은 돌아가고 있기 때문에 최신 플로우에 맞게 코드를 수정했습니다.

[FE] Cypress 코드 정상화

---

client/src/hooks/useMembersStep.ts

* [FE] v3.1.1 배포 by @jinhokim98 in https://github.com/woowacourse-teams/2024-haeng-dong/pull/943
* [FE] 지출 내역 인원 변동 step으로 들어갈 때 provider 오류 by @jinhokim98 in https://github.com/woowacourse-teams/2024-haeng-dong/pull/945
**Full Changelog**: https://github.com/woowacourse-teams/2024-haeng-dong/compare/v3.1.1...v3.1.2

[FE] v3.1.2 배포

---

client/src/components/Design/components/Icons/Svg.style.ts

* [FE] v3.1.2 배포 by @jinhokim98 in https://github.com/woowacourse-teams/2024-haeng-dong/pull/946
* [FE] iOS에서 아이콘이 제대로 보이지 않던 문제 by @Todari in https://github.com/woowacourse-teams/2024-haeng-dong/pull/948
**Full Changelog**: https://github.com/woowacourse-teams/2024-haeng-dong/compare/v3.1.2...v3.1.3

[FE] v3.1.3 배포

---

client/src/components/AccountView/index.tsx
client/src/components/Design/components/Stack/HStack.tsx
client/src/components/Design/components/Stack/Stack.style.ts
client/src/components/Design/components/Stack/Stack.tsx
client/src/components/Design/components/Stack/VStack.tsx

- close #992 
전혀 상상하지 못했는데;;;ㅜ 발견해주셔서 감사합니당!

[FE] Bank icon 설정이 되어있지 않을 때 오류 해결

---

client/index.html

- close #997 
크루위키 s3에 연결되어있던 이미지를 우리 s3에서 가져오는 것으로 변경했습니다.
```html
<meta property="og:image" content="<%= process.env.IMAGE_URL %>/og-image.jpg" />
```

[FE] index.html og image를 우리 s3에서 가져오도록 변경

---

.github/workflows/frontend-dev-deploy.yml
.github/workflows/frontend-prod-deploy.yml
client/package-lock.json
client/package.json
client/src/index.tsx
client/tsconfig.json
client/webpack.common.mjs
client/webpack.dev.mjs
client/webpack.prod.mjs

* [FE] v3.2.1 배포 by @soi-ha in https://github.com/woowacourse-teams/2024-haeng-dong/pull/999
* [FE] webpack build, buld-dev 속도 개선 by @pakxe in https://github.com/woowacourse-teams/2024-haeng-dong/pull/1002
**Full Changelog**: https://github.com/woowacourse-teams/2024-haeng-dong/compare/v.3.2.1...v3.2.2

[FE] v3.2.2 배포

---

.github/workflows/frontend-prod-deploy.yml
client/src/utils/NetworkStateCatcher.tsx

- close #1004
의존성 설치가 선행되지 않고 빌드를 하려고 해 오류가 발생하고 있었습니다.
의존성 설치를 먼저 하고 빌드하도록 수정했습니다.

[FE] 의존성 설치를 먼저 하고 빌드하도록 수정

---

.github/workflows/frontend-prod-deploy.yml
client/src/utils/NetworkStateCatcher.tsx

* [FE] v3.2.2 배포 by @pakxe in https://github.com/woowacourse-teams/2024-haeng-dong/pull/1003
* [FE] 의존성 설치를 먼저 하고 빌드하도록 수정 by @pakxe in https://github.com/woowacourse-teams/2024-haeng-dong/pull/1005
**Full Changelog**: https://github.com/woowacourse-teams/2024-haeng-dong/compare/v3.2.2...v3.2.3

[FE] v3.2.3 배포

---

.github/workflows/frontend-prod-deploy.yml
client/src/components/Design/components/Flex/Flex.style.ts

- close #1007
빌드 후에 환경변수를 주입하고 있어서 제대로 이미지와 환경변수가 반영되지 않고 있습니다.
빌드 전에 환경 변수 주입하도록 수정했습니다.

[FE] 빌드 전에 환경 변수 주입하도록 수정

---

client/src/components/Design/components/Banner/Banner.tsx
client/src/components/Design/components/Banner/Banner.type.ts
client/src/components/Design/components/SendButton/SendButton.tsx
client/src/pages/event/[eventId]/home/HomePage.tsx

* [FE] v3.2.3 배포 by @pakxe in https://github.com/woowacourse-teams/2024-haeng-dong/pull/1006
* [FE] 빌드 전에 환경 변수 주입하도록 수정 by @pakxe in https://github.com/woowacourse-teams/2024-haeng-dong/pull/1008
* [FE] 관리자 계좌번호 미입력시 참여자 Banner 알림 by @soi-ha in https://github.com/woowacourse-teams/2024-haeng-dong/pull/1010
**Full Changelog**: https://github.com/woowacourse-teams/2024-haeng-dong/compare/v3.2.3...v3.2.4

[FE] v3.2.4 배포
