woowacourse-teams/2024-haeng-dong

server/src/main/java/server/haengdong/application/EventService.java, server/src/main/java/server/haengdong/application/request/EventAppRequest.java, server/src/main/java/server/haengdong/application/response/EventAppResponse.java, server/src/main/java/server/haengdong/domain/Event.java, server/src/main/java/server/haengdong/domain/EventTokenProvider.java, server/src/main/java/server/haengdong/persistence/EventRepository.java, server/src/main/java/server/haengdong/presentation/EventController.java, server/src/main/java/server/haengdong/presentation/request/EventSaveRequest.java, server/src/test/java/server/haengdong/application/EventServiceTest.java, server/src/test/java/server/haengdong/presentation/EventControllerTest.java
- close #15 
행사 생성 API 구현
리뷰 시에 커밋의 규모가 적당했는지 궁금합니다. 
행사 token 생성 전략에 대하여, 임의로 UUID를 선택했습니다. 이후, 변경을 고려하여 EventTokenProvider.class로 분리했습니다. 추후 논의가 필요할 것 같습니다.
=> [BE] 행사 생성 기능 구현

server/src/main/java/server/haengdong/application/EventService.java, server/src/main/java/server/haengdong/application/response/EventDetailAppResponse.java, server/src/main/java/server/haengdong/presentation/EventController.java, server/src/main/java/server/haengdong/presentation/response/EventDetailResponse.java, server/src/test/java/server/haengdong/application/EventServiceTest.java, server/src/test/java/server/haengdong/presentation/EventControllerTest.java
- close #67 
- 행사 정보를 조회합니다. 
- 구현한 내용이 적어서 로직, 컨벤션 모두 확인 부탁드립니다.
=> [BE] 행사 정보 조회 기능 구현

server/src/main/java/server/haengdong/application/MemberActionService.java, server/src/main/java/server/haengdong/application/response/CurrentMemberAppResponse.java, server/src/main/java/server/haengdong/domain/action/CurrentMembers.java, server/src/main/java/server/haengdong/presentation/MemberActionController.java, server/src/main/java/server/haengdong/presentation/response/CurrentMemberResponse.java, server/src/main/java/server/haengdong/presentation/response/CurrentMembersResponse.java, server/src/test/java/server/haengdong/application/MemberActionServiceTest.java, server/src/test/java/server/haengdong/domain/action/CurrentMembersTest.java, server/src/test/java/server/haengdong/presentation/MemberActionControllerTest.java
- close #65 
행사에 현재 IN 상태인 모든 인원 목록을 조회하는 기능을 구현했습니다.
현재 참여 중인 인원 목록(CurrentMembers)으로 인원 변동 생성 검증을 하는 것은 어떨까요?
CurrentMembers가 추가하려는 MemberAction을 검증해도 괜찮을 것 같아요.
=> [BE] 현재 참여 인원 조회

server/src/main/java/server/haengdong/HaengdongApplication.java, server/src/main/java/server/haengdong/application/BillActionService.java, server/src/main/java/server/haengdong/application/EventService.java, server/src/main/java/server/haengdong/application/MemberActionFactory.java, server/src/main/java/server/haengdong/exception/ErrorResponse.java, server/src/main/java/server/haengdong/exception/GlobalExceptionHandler.java, server/src/main/java/server/haengdong/exception/HaengdongErrorCode.java, server/src/main/java/server/haengdong/exception/HaengdongException.java, server/src/test/java/server/haengdong/application/BillActionServiceTest.java, server/src/test/java/server/haengdong/application/MemberActionFactoryTest.java
=> [BE] 행사 커스텀 예외 처리

server/src/main/java/server/haengdong/application/ActionService.java, server/src/main/java/server/haengdong/application/response/MemberBillReportAppResponse.java, server/src/main/java/server/haengdong/domain/action/BillAction.java, server/src/main/java/server/haengdong/domain/action/MemberAction.java, server/src/main/java/server/haengdong/domain/action/MemberBillReports.java, server/src/main/java/server/haengdong/presentation/ActionController.java, server/src/main/java/server/haengdong/presentation/response/MemberBillReportResponse.java, server/src/main/java/server/haengdong/presentation/response/MemberBillReportsResponse.java, server/src/test/java/server/haengdong/application/ActionServiceTest.java, server/src/test/java/server/haengdong/domain/action/MemberBillReportsTest.java, server/src/test/java/server/haengdong/presentation/ActionControllerTest.java
- close #64
참여자별 정산 현황을 조회합니다.
[현재 참여 인원 조회](https://github.com/woowacourse-teams/2024-haeng-dong/pull/70) PR을 먼저 리뷰해주세요.
해당 PR 머지 후 리펙토링이 필요합니다.
=> [BE] 참여자별 정산 현황 조회 기능 구현

server/src/main/java/server/haengdong/presentation/ActionController.java, server/src/main/java/server/haengdong/presentation/BillActionController.java, server/src/main/java/server/haengdong/presentation/EventController.java, server/src/main/java/server/haengdong/presentation/MemberActionController.java, server/src/main/java/server/haengdong/presentation/response/EventResponse.java, server/src/test/java/server/haengdong/presentation/EventControllerTest.java
- close #97 
- 기존에 URL Path에서 `token`이라는 이름으로 전달하던 행사 URL을 `eventId`로 수정했습니다. 
- 응답 Header로 전달하던 행사 URL을 응답 Body에 `"{url: 550e8400-e29b-41d4-a716-446655440000}"` 형식으로 전달합니다. 
- 노션 api 문서 업데이트 완료
행사 URL을 응답 Body에 `url`이라는 이름의 필드로 전달하는 것이 괜찮은가요? 다른 제안을 해주시면 적극 반영해 볼게요!
=> [BE] api 명세에서 행사 url을 표현하는 용어와 전달 방식 수정

server/src/main/resources/application.yml
- close #101 
application.yml에서 DB 설정을 MySQL에서 H2로 수정했습니다.
=> [BE] 기본 프로파일에서 DB를 MySQL을 H2로 변경

server/src/main/java/server/haengdong/application/MemberActionService.java, server/src/main/java/server/haengdong/domain/action/BillAction.java, server/src/main/java/server/haengdong/exception/HaengdongErrorCode.java, server/src/main/java/server/haengdong/presentation/request/BillActionSaveRequest.java, server/src/test/java/server/haengdong/application/MemberActionServiceTest.java, server/src/test/java/server/haengdong/domain/action/BillActionTest.java
- close #96 
지출 내역 생성 및 현재 참여 인원 조회 예외 메시지 변경
=> [BE] 지출 내역 생성 및 현재 참여 인원 조회 예외 메시지 변경

server/src/main/java/server/haengdong/application/ActionService.java, server/src/test/java/server/haengdong/application/ActionServiceTest.java
- close #105 
참여자별 정산 현황 조회 API에서 발생하는 예외에 대한 구체적인 메시지를 추가했습니다.
- 존재하지 않는 eventId로 정산 현황 조회 - `존재하지 않는 행사입니다.`
=> [BE] 참여자별 정산 현황 조회 API 예외 메시지 추가

server/src/main/java/server/haengdong/domain/event/Event.java, server/src/main/java/server/haengdong/presentation/EventController.java, server/src/main/java/server/haengdong/presentation/request/EventSaveRequest.java, server/src/test/java/server/haengdong/domain/event/EventTest.java
- close #99 
행사 생성 API 
POST /api/events
`EventSaveRequest` 객체의 속성 `name`을 `eventName`으로 변경했습니다.
검증 애너테이션 `@NotBlank`, `@Size(min = 2, max = 20)`를 추가하여 행사 이름이 null과 공백 문자인지 검증하고,
행사 이름이 2자 이상 20자 이하인지 검증합니다.
=> [BE] 행사 생성 API 예외 메세지 및 DTO 검증 애너테이션 추가

server/src/main/java/server/haengdong/exception/ErrorResponse.java, server/src/main/java/server/haengdong/exception/GlobalExceptionHandler.java
- close #108 
HaengdongException을 생성시 HaengdongErrorCode과 예외 메세지를 넣어서 생성하고 던지는데, GlobalExceptionHandler 에서 catch 할 때 ErrorResponse.of()메서드에 HaengdongErrorCode의 getMessage() 메서드를 호출하여 예외 생성시 직접 정의한 메세지를 반환하지 않는 버그 해결.
=> [BE] 예외에서 정의한 메세지를 꺼내지 못하는 오류 해결

client/package-lock.json, client/package.json, client/src/constants/routerUrls.ts, client/src/pages/Create/Complete.tsx, client/src/pages/Create/Name.tsx, client/src/pages/Event/Event.tsx
- close #109
- router 연결
- StepList 연결
- 총 지출 금액 추가
=> [FE] 퍼블리싱된 페이지 매끄럽게 연결

server/src/main/java/server/haengdong/application/EventService.java, server/src/main/java/server/haengdong/application/response/ActionAppResponse.java, server/src/main/java/server/haengdong/presentation/EventController.java, server/src/main/java/server/haengdong/presentation/response/ActionResponse.java, server/src/main/java/server/haengdong/presentation/response/ActionsResponse.java, server/src/main/java/server/haengdong/presentation/response/StepResponse.java, server/src/test/java/server/haengdong/application/EventServiceTest.java, server/src/test/java/server/haengdong/presentation/EventControllerTest.java, server/src/test/java/server/haengdong/presentation/response/StepResponseTest.java
- close #20 
- 토큰으로 이벤트를 조회한다.
- 해당 이벤트에 속한 지출 내역과, 인원 변동 내역을 모두 조회한다.
- two pointer 알고리즘을 통해 지출 내역과 인원 변동 내역의 순서를 정렬하여 반환한다.
=> [BE] 액션 이력 조회 기능 구현

.github/workflows/backend-push.yml, server/Dockerfile
- close #135 
Dockerfile과 backend-push.yml 수정하여 도커 이미지 빌드 성능 개선
=> [BE] Docker 빌드 성능 개선

server/src/main/java/server/haengdong/application/ActionService.java, server/src/main/java/server/haengdong/domain/action/CurrentMembers.java, server/src/main/java/server/haengdong/domain/action/MemberAction.java, server/src/main/java/server/haengdong/domain/action/MemberBillReport.java, server/src/test/java/server/haengdong/domain/action/CurrentMembersTest.java, server/src/test/java/server/haengdong/domain/action/MemberBillReportTest.java
- close #95
MemberAction의 status에 따라 현재 참여인원을 추가 또는 삭제하는 로직의 역할을 MemberBillReport가 아닌 CurrentMembers 로 변경했습니다.
1. CurrentMembers를 불변 객체로 변경했는데 가변 객체를 사용하는 방법도 있을 것 같습니다. 어떻게 생각하시나요?
2. CurrentMembers는 `List<MemberAction>`로 만들어지는데 현재 MemberAction을 검증하고 있지는 않습니다. DB에서 읽어온 MemberAction 리스트를 검증을 하는 것이 좋을까요?
3. 인원 변동 추가 기능에서 검증을 CurrentMembers가 해도 괜찮을 것 같습니다. 어떻게 생각하시나요?
=> [BE] 참여자 정산 현황 로직 리펙토링

server/build.gradle, server/src/main/resources/application.yml, server/src/main/resources/logback-spring.xml
- close #148 
날짜별로 로그 파일 생성하고, nginx에 actuator log 파일 조회 endpoint 접근 제한을 설정했습니다.
=> [BE] 백엔드 서버 모니터링 환경 구축

server/src/main/java/server/haengdong/application/MemberActionFactory.java, server/src/main/java/server/haengdong/application/MemberActionService.java, server/src/main/java/server/haengdong/domain/action/CurrentMembers.java, server/src/main/java/server/haengdong/exception/ErrorResponse.java, server/src/main/java/server/haengdong/exception/GlobalExceptionHandler.java, server/src/main/java/server/haengdong/exception/HaengdongErrorCode.java, server/src/main/java/server/haengdong/exception/HaengdongException.java, server/src/test/java/server/haengdong/application/MemberActionFactoryTest.java, server/src/test/java/server/haengdong/domain/action/CurrentMembersTest.java
- close #118 
예외 메시지를 구체화했습니다.
예외 상황에 따라 code 필드를 추가로 전달해 주도록 변경했습니다.
도메인에서 발생한 예외는 좀 더 구체적인 message를 전달합니다.
ex)`MA_002` : message가 `"%s은 이미 참여하고 있습니다."`와 `%s은 현재 참여하고 있지 않습니다."`로 구분되어 전달합니다.
=> [BE] 예외메시지 구체화

HDesign/src/theme/GlobalStyle.ts
- close #170
GlobalStyle.tsx에 button:disabled를 수정했습니다.
=> [FE] Button컴포넌트에서 disabled일 때 커서 포인터가 보임

.github/workflows/backend-dev.yml, .github/workflows/backend-pull-request.yml, server/src/main/java/server/haengdong/application/EventService.java, server/src/main/java/server/haengdong/application/response/MembersAppResponse.java, server/src/main/java/server/haengdong/domain/action/MemberActionRepository.java, server/src/main/java/server/haengdong/presentation/EventController.java, server/src/main/java/server/haengdong/presentation/response/MembersResponse.java, server/src/test/java/server/haengdong/application/EventServiceTest.java, server/src/test/java/server/haengdong/presentation/EventControllerTest.java
- close #191 
**엔드포인트**
`/api/events/{eventId}/members`
**Path Variable**
- eventId: String
**예외 상황**
- eventId에 해당되는 행사가 없는 경우
- HttpStatus: 400
- ErrorCode: EV_400
- Message: 존재하지 않는 행사입니다.
- 간단한 API로 리뷰할 부분이 적을 것 같습니다. 
- 메서드 네이밍과 메서드의 구현 클래스 위치를 확인해 주세요! 
- ex) eventService 안에 구현했는데 적절한지
=> [BE] 행사에 참여한 전체 인원 조회 기능 구현

server/src/test/java/server/haengdong/application/ActionServiceTest.java, server/src/test/java/server/haengdong/application/BillActionServiceTest.java, server/src/test/java/server/haengdong/application/EventServiceTest.java, server/src/test/java/server/haengdong/application/MemberActionFactoryTest.java, server/src/test/java/server/haengdong/application/MemberActionServiceTest.java, server/src/test/java/server/haengdong/support/extension/DatabaseCleaner.java, server/src/test/java/server/haengdong/support/extension/DatabaseCleanerExtension.java
- close #58 
매 테스트가 종료되고 데이터를 삭제하는 클리너를 구현했습니다. 
클리너는 다음과 같이 동작합니다. 
1. 외래키 제약 조건 해제
2. 모든 테이블 truncate
3. 외래키 제약 조건 설정
- sql이 하드 코딩되어 있는데, 이에 대한 의견이 궁금합니다. 괜찮은가요? 
- 클리너 구현을 컨펌 받고 나서 현재 테스트 코드에 적용하겠습니다.
=> [BE] 테스트 데이터 클리너 구현

server/src/main/java/server/haengdong/config/AdminInterceptor.java, server/src/main/resources/application.yml
- close #233 
CORS는 HttpMethod Options로 Preflight 요청을 보냅니다.
백엔드 서버에서 쿠키가 없는 상태에서는 Get만 가능하게 막아두어 CORS 인증에 실패하는 버그가 있었습니다.
=> [BE] CORS, 쿠키 인증오류 수정

HDesign/package-lock.json, HDesign/package.json, HDesign/src/components/FixedButton/FixedButton.tsx, HDesign/src/components/IconButton/IconButton.style.ts
- close #229 
```tsx
<form css={bottomSheetStyle} onSubmit={event => onSubmit(event, inputPair, billAction.actionId)}>
<header css={bottomSheetHeaderStyle}>
<Text size="bodyBold">지출 내역 수정하기</Text>
</header>
<fieldset css={inputContainerStyle}>
<LabelGroupInput labelText="지출내역 / 금액" errorText={errorMessage}>
<LabelGroupInput.Element
aria-label="지출 내역"
elementKey={'0'}
type="text"
value={inputPair.title}
onChange={event => handleInputChange('title', event)}
onBlur={handleOnBlur}
isError={errorInfo.title}
placeholder="지출 내역"
/>
<LabelGroupInput.Element
aria-label="금액"
elementKey={'0'}
type="number"
value={inputPair.price}
onChange={event => handleInputChange('price', event)}
onBlur={handleOnBlur}
isError={errorInfo.price}
placeholder="금액"
/>
</LabelGroupInput>
</fieldset>
<FixedButton …
```
=> [FE] FixedButton의 delete button type "button"으로 변경

server/src/main/java/server/haengdong/application/ActionService.java, server/src/main/java/server/haengdong/application/AuthService.java, server/src/main/java/server/haengdong/application/BillActionService.java, server/src/main/java/server/haengdong/application/EventService.java, server/src/main/java/server/haengdong/application/MemberActionFactory.java, server/src/main/java/server/haengdong/application/MemberActionService.java, server/src/main/java/server/haengdong/config/AdminInterceptor.java, server/src/main/java/server/haengdong/domain/action/BillAction.java, server/src/main/java/server/haengdong/domain/action/CurrentMembers.java, server/src/main/java/server/haengdong/domain/action/MemberAction.java, server/src/main/java/server/haengdong/domain/action/MemberActionStatus.java, server/src/main/java/server/haengdong/domain/event/Event.java, server/src/main/java/server/haengdong/exception/AuthenticationException.java, server/src/main/java/server/haengdong/exception/ErrorResponse.java, server/src/main/java/server/haengdong/exception/GlobalExceptionHandler.java, server/src/main/java/server/haengdong/exception/HaengdongErrorCode.java, server/src/main/java/server/haengdong/exception/HaengdongException.java, server/src/main/java/server/haengdong/infrastructure/auth/AuthenticationExtractor.java, server/src/main/java/server/haengdong/presentation/request/BillActionSaveRequest.java, server/src/main/java/server/haengdong/presentation/request/BillActionUpdateRequest.java, server/src/main/java/server/haengdong/presentation/request/BillActionsSaveRequest.java, server/src/main/java/server/haengdong/presentation/request/EventLoginRequest.java, server/src/main/java/server/haengdong/presentation/request/EventSaveRequest.java, server/src/main/java/server/haengdong/presentation/request/MemberActionsSaveRequest.java, server/src/main/java/server/haengdong/presentation/request/MemberUpdateRequest.java, server/src/test/java/server/haengdong/application/ActionServiceTest.java, server/src/test/java/server/haengdong/domain/action/BillActionTest.java, server/src/test/java/server/haengdong/domain/event/EventTest.java, server/src/test/java/server/haengdong/presentation/BillActionControllerTest.java
- close #223 
프론트 크루 `웨디`의 요청에 따라 기존의 에러 코드를 보다 명확하고 직관적으로 표현하는 방식으로 수정하였습니다. 기존 도메인명 앞글자를 따서 만든 에러 코드에서, 에러 상황을 코드에 의미를 명확하게 담도록 변경하였습니다.
**기존 에러 응답 예시**
```json
{
"code": "MA_002",
"message": "현재 참여하고 있는 인원이 존재합니다."
}
```
**변경된 에러 응답**
```json
{
"code": "MEMBER_ALREADY_EXIST",
"message": "현재 참여하고 있는 인원이 존재합니다."
}
```
기존에 사용하던 ErrorCode를 ErrorResponse 필드에 넣는 방식을 변경하여, 보다 명확한 에러 코드를 제공하도록 구현하였습니다.
```java
public record ErrorResponse(
// 이전 코드
// String code,
// 변경된 코드
HaengdongErrorCode errorCode,
String message
) {}
```
프론트 크루 `웨디`의 요청에 따라, 기존의 에러 코드 체계를 보다 세분화하여 각 API에서 발생하는 예외 상황을 명확하게 표현하도록 수정하였습니다. 기존에는 전역적으로 8개의 에러 코드만 정의되어 있었으나, 이를 각 API별로 세분화된 에러 코드 체계로 개선하였습니다.
**기존 에러 코드 체계 문제점**
- 에러 코드가 전역적으로 8개만 정의되어 있어, 구체적인 에러 원인을 파악하기 어려웠습니다.
- 각 API에서 발생하는 예외가 5~10가지인데, 이를 명확하게 구분하지 …
=> [BE] 에러 코드 재정의

client/package-lock.json, client/package.json, client/src/components/Modal/SetActionModal/DeleteMemberActionModal/DeleteMemberActionModal.style.ts, client/src/components/Modal/SetActionModal/PutAndDeleteBillActionModal/PutAndDeleteBillActionModal.tsx, client/src/components/Modal/SetActionModal/PutAndDeleteBillActionModal/PutAndDeltetBillActionModal.style.ts, client/src/components/Modal/SetActionModal/PutAndDeleteBillActionModal/index.ts, client/src/components/StepList/BillStepItem.tsx, client/src/constants/errorMessage.ts, client/src/hooks/useDynamicBillActionInput.tsx, client/src/hooks/usePutAndDeleteBillAction/index.ts, client/src/hooks/usePutAndDeleteBillAction/usePutAndDeleteBillAction.ts, client/src/hooks/usePutBillAction/usePutBillAction.ts, client/src/utils/validate/type.ts, client/src/utils/validate/validatePurchase.ts
- close #175 
- 지출 액션 수정과 삭제를 구현했습니다.
지출 수정을 위해 액션을 클릭 시에 바텀 시트가 올라오면서 들어옵니다.
이 때 수정을 하지 않았으면 바텀 시트의 버튼은 비활성화로 유지됩니다.
검증 조건에 맞지 않는 경우 아래 사진과 같이 에러 메시지와 input 테두리에 에러 표시를 보여줍니다.
100,000,000을 적을 경우 10,000,000 이하로 입력하세요라는 에러가 나온다. 하지만 에러일 때는 값을 덮어쓰므로 값은 10,000,000이 되고 여기서 10,000,000은 정상적인 입력이기 때문에 에러가 아니라고 표시를 해주어야 하기 때문에 blur시에 다시 검증을 합니다.
값이 비워질 경우 에러이기 때문에 비워지는 순간 submit 버튼을 비활성화합니다
그리고 blur시에 에러를 활성화시키며 값은 비어있을 수 없다는 에러를 보여줍니다.
수정완료를 누르면 수정 api가 호출됩니다. 하지만 dev서버가 지금 말썽이라 테스트는 할 수 없는 상황..;; 뭐 되겠지?
삭제도 마찬가지 삭제도 누르면 삭제 api가 호출되지만 뭐 되겠지?
validateResult에 errorInfo를 추가해줬습니다. 각 인풋 창에 아래 사진과 같이 에러 상태를 보여주어야 하기 때문입니다.
```ts
export interface ValidateResult {
isValid: boolean;
errorMessage?: string;
errorInfo?: Record<string, boolean>;
}
const errorInfo = {
price: false,
title: false,
};
```
=> [FE] 지출 액션 수정, 삭제 기능 구현

server/build.gradle, server/src/docs/asciidoc/billAction.adoc, server/src/docs/asciidoc/event.adoc, server/src/docs/asciidoc/index.adoc, server/src/docs/asciidoc/memberAction.adoc, server/src/docs/asciidoc/memberBillReport.adoc, server/src/test/java/server/haengdong/docs/ActionControllerDocsTest.java, server/src/test/java/server/haengdong/docs/BillActionControllerDocsTest.java, server/src/test/java/server/haengdong/docs/EventControllerDocsTest.java, server/src/test/java/server/haengdong/docs/MemberActionControllerDocsTest.java, server/src/test/java/server/haengdong/docs/RestDocsSupport.java, server/src/test/java/server/haengdong/support/fixture/Fixture.java
- close #220 
Spring REST Docs를 전체 API에 적용했습니다.
- 서버 실행 후 `/docs/index.html`로 접속
- Path parameters: API 엔드포인트와 path 변수에 대한 정보
- HTTP request: HTTP Method, Header, Body가 포함된 전체 HTTP 요청 형식
- Request body: 요청 본문
- Request fields: 요청 본문 각 필드에 대한 상세 설명
- Response body: 응답 본문
- Response fields: 응답 본문 각 필드에 대한 상세 설명
- HTTP response: HTTP Status, Header, Body가 포함된 전체 HTTP 응답 형식
- Request cookies: 요청에 포함되어야 하는 쿠키 목록
- Response cookies: API 응답으로 발급되는 쿠키 목록
- Exceptions: 해당 API에서 발생할 수 있는 예외 사항 목록
1. path-parameters
2. http-request
3. request-body
4. request-fields
5. response-body
6. response-fields
7. http-response
8. request-cookies
9. response-cookies
10. exceptions
response-body가 생성되지 않는 경우에는 http-response와 response-fields의 순서를 변경하여 작성합니다.
- asciidoctor 실행하면 `/build/docs/asciidoc`에 각 adoc에 대응되는 …
=> [BE] REST docs를 통한 문서화

client/src/hooks/useDeleteMemberAction/useDeleteMemberAction.tsx
- close #261 
useToast는 ToastProvider가 선언되어야합니다. 에러로 인한 에러바운더리 실행 버그 해결
useToast의 import를 행동디자인이 아닌 components/Toast/ToastProvider로 옮겼습니다.
=> [FE] 멤버 내역을 클릭할 때 에러 바운더리가 실행되는 버그

HDesign/package-lock.json, HDesign/package.json, HDesign/src/components/DragHandleItem/DragHandleItem.style.ts, HDesign/src/components/DragHandleItem/DragHandleItem.tsx, HDesign/src/components/DragHandleItemContainer/DragHandleItemContainer.style.ts, HDesign/src/components/DragHandleItemContainer/DragHandleItemContainer.tsx, HDesign/src/components/ExpenseList/ExpenseList.style.ts, HDesign/src/components/ExpenseList/ExpenseList.tsx, HDesign/src/components/ListButton/ListButton.style.ts, HDesign/src/components/ListButton/ListButton.tsx, HDesign/src/components/Text/Text.style.ts, HDesign/src/components/Text/Text.tsx, HDesign/src/components/Text/Text.type.ts, HDesign/src/components/TextButton/TextButton.style.ts, HDesign/src/components/TextButton/TextButton.tsx, HDesign/src/components/Title/Title.style.ts, HDesign/src/components/Title/Title.tsx
- close #254 
현재 Text color를 설정해 주는 굉장히 많은 부분에서 보일러플레이트 코드가 발생하고 있습니다.
```tsx
// DragHandleItem.tsx
// ~
<Text css={textStyle(theme)} size="bodyBold">
{prefix}
</Text>
// ~
// DragHandleItem.style.ts
// ~
export const textStyle = (theme: Theme) =>
css({
color: theme.colors.black,
});
```
심지어 사용처에서는 color를 별도로 지정해 줄 수 있는 방법이 없었습니다.
이에 따라 color를 prop으로 받아 사용할 수 있도록 변경합니다.
```tsx
export interface TextStyleProps {
size?: TextSize;
color?: ColorKeys;
}
```
ColorKeys type을 받아서, semantic token 값을 prop 으로 받을 수 있도록 변경합니다.
color prop을 만들었지만, 사용처에서 color prop이 적용되지 않는 문제가 발생했습니다.
사용처에서 color의 타입을 확인해 본 결과, 
`React.HTMLAttributes<HTMLParagraphElement>.color` 로 들어가는 것을 확인할 수 있었습니다.
아마 기존의 paragraph prop들도 함께 받는 과정에서, color prop이 덫씌워진 것 같았습니다.
```tsx
export type TextSize =
| 'head'
| 'title'
| …
```
=> [FE] 디자인시스템 Text 컴포넌트 color prop 받도록 변경

server/src/main/java/server/haengdong/application/MemberActionService.java, server/src/main/resources/application.yml
```
server:
servlet:
encoding:
charset: UTF-8
enabled: true
force: true
```
**발생한 로그**
**문제가 되었던 부분**
delete 쿼리가 발생했지만 커넥션이 read-only여서 삭제 요청이 처리되지 못했다. 
**해결**
```java
MemberActionService.java
@Transactional // 추가한 부분
public void deleteMember(String token, String memberName) {
Event event = eventRepository.findByToken(token)
.orElseThrow(() -> new HaengdongException(HaengdongErrorCode.EVENT_NOT_FOUND));
memberActionRepository.deleteAllByEventAndMemberName(event, memberName);
}
```
=> [BE] 참여자 삭제 메서드 @Transactional 추가

client/src/components/Modal/SetActionModal/AddMemberActionListModalContent/OutMember.tsx, client/src/components/StepList/BillStepItem.tsx, client/src/components/StepList/MemberStepItem.tsx, client/src/components/StepList/StepList.tsx, client/src/pages/EventPage/EventPageLayout.tsx
- close #284 
홈에서 액션 수정 삭제 바텀시트 활성화가 되는 버그를 해결했어요
추가로 불주사도 홈과 관리에 따라서 활성화 변하도록 설정했어요
react-router-dom의 useMatch를 활용해서 isAdmin을 url에 따라서 구분할 수 있도록 설정했어요
EventLayout에서 isAdmin을 구한뒤 outletContext를 통해서 내부 컴포넌트로 값을 전달해줍니다.
내부에서 useOutletContext를 받아서 isAdmin을 사용합니다.
지금은 outlet에 isAdmin boolean 값밖에 없지만 추가될 때는 context type을 추가해야합니다.
=> [FE] 홈에서 액션 수정 삭제 바텀시트 활성화 버그

server/src/main/resources/application.yml
- close #267 
현재 CloudWatch를 통해 cpu, mem, 네트워크만 한정적으로 모니터링 가능합니다.
이 밖에 appliction, connection-pool, jvm, system 등 모니터링 하는 대상을 확장하기 위해
application.yml에 작성 되어있는 management.endpoints.web.exposure.include 에 metrics를 추가합니다.
=> [BE] actuator metrics 추가하여 모니터링 대상 확장

client/webpack.dev.mjs
- close #292
webpack.dev.mjs에 sentryWebpackPlugin를 import합니다.
=> [FE] webpack.dev.mjs에 sentryWebpackPlugin가 import되어있지 않음 

server/Dockerfile, server/src/main/resources/application.yml
- close #84 
- application.yml과 submodule에 들어있는 application-dev.yml, application-prod.yml에`spring.jpa.properties.jdbc.time_zone: Asia/Seoul` 설정을 추가했습니다. 이 설정은 프로퍼티를 추가하여 MySQL 데이터베이스의 Timezone 설정을 변경할 수 있습니다. 특정 database에 의존적이지 않기 때문에 이 방법을 선택했습니다.
- Dockerfile CMD에 java 실행 옵션으로 `-Duser.timezone=Asia/Seoul` 옵션을 추가해서 java 애플리케이션을 kst 시간대로 실행할 수 있도록 수정했습니다.
자바 실행 옵션으로 Asia/Seoul로 실행 했어도, yml에 DB TimeZone이 UTC로 되어있다면, 저장은 UTC 시간대로 저장됩니다.
그렇기 때문에 자바 실행 옵션과 MySQL 데이터베이스 TimeZone 설정을 일치시켜야 시간대 불일치 없이 저장됩니다.
---
> 로그에 시간도 현재 시간으로 잘 찍히는지 궁금합니다.
1. UTC 시간대 설정
`java -Duser.timezone=UTC -jar haengdong-0.0.1-SNAPSHOT.jar` 
---
2. Asia/Seoul 시간대 설정
`java -Duser.timezone=Asia/Seoul -jar haengdong-0.0.1-SNAPSHOT.jar `
보시는 바와 같이 설정에 따라 시간대가 잘 설정된 것을 볼 수 있습니다.
논의하고 싶은 부분이 …
=> [BE] yml, Dockerfile TZ Asia/Seoul 적용

server/src/main/java/server/haengdong/HaengdongApplication.java, server/src/main/java/server/haengdong/config/AdminInterceptor.java, server/src/main/java/server/haengdong/exception/GlobalExceptionHandler.java, server/src/main/java/server/haengdong/exception/HaengdongErrorCode.java, server/src/main/java/server/haengdong/presentation/EventController.java, server/src/main/resources/application.yml, server/src/main/resources/logback-spring.xml
- close #297 
- application.yml 설정에 actuator health 엔드포인트를 열어서 개발, 운영 서버가 정상 작동중인지 확인할 수 있도록 했습니다.
- 기존 logback-spring.xml 에 작성되어있던 로그 메세지 패턴을 날짜, 시간, 로그 레벨, 스레드 이름, 로거 이름, 메시지 형식을 볼 수 있도록 변경했습니다. 
- EventController, HaengdongAppliction 클래스에 작성한 테스트용 로그 메세지를 삭제했습니다.
- HaengdongErrorCode에 새로운 에러코드 `REQUEST_METHOD_NOT_SUPPORTED("지원하지 않는 요청 메서드입니다.")`를 추가했습니다. 아래와 같이 노션 API 문서에 반영하였습니다.
- GlobalExceptionHandler에서 관리하는 핸들러 중 Exception을 제외한 나머지 핸들러의 로깅 레벨을 warn으로 변경했습니다.
- AdminInterceptor prehandle 메서드에 있던 로그 레벨을 trace에서 debug로 변경했습니다.
=> [BE] actuator health 엔드포인트 설정 변경

HDesign/package-lock.json, HDesign/package.json, HDesign/src/components/BottomSheet/BottomSheet.style.ts
- close #317 
전체 app의 maxWidth는 768px로 고정되어 있었지만,
bottomSheet가 보일 때, 이를 넘어서 전체 화면의 너비만큼 출력되었음.
768px이 넘을 경우, 최대 너비만큼만의 영역이 생기게끔 변경함.
이렇게 만들 경우, 만약 우리 앱의 최대 너비가 768px에서 다른 너비로 변경되어야 할 때,
이 부분을 또 수정해 줘야 할 필요가 있음.
직접 선언해 주는게 아니라, client 단에서 사용하기 쉽게 prop을 받아야 하는것이 맞을까?
그런데, prop을 받는다고 한다면 오히려 사용하는 모든 곳에서 prop 으로 768px을 전달해 줘야 함.
어떤 방법이 좋을지 궁금하네요
=> [FE] BottomSheet component width 수정

client/src/components/Modal/SetActionModal/AddBillActionListModalContent/AddBillActionListModalContent.tsx, client/src/components/Modal/SetActionModal/AddMemberActionListModalContent/InMember.tsx, client/src/components/Modal/SetActionModal/AddMemberActionListModalContent/OutMember.tsx, client/src/components/Modal/SetInitialMemberListModal/SetInitialMemberListModal.tsx, client/src/constants/errorMessage.ts, client/src/hooks/useDynamicBillActionInput.tsx, client/src/hooks/useDynamicInput.tsx, client/src/pages/EventPage/AdminPage/AdminPage.tsx, client/src/utils/sendLogToSentry.ts
- close #313
- handleInputChange if문 수정
- 빈 Input이 띠워지는 조건문
기존에는 마지막 input임이 확인되면서 값도 변경될 수 있도록 되어 있었다.
```tsx
if (isLastInputFilled(index, value)) {
// 마지막 인풋이 한 자라도 채워진다면 새로운 인풋을 생성해 간편한 다음 입력을 유도합니다.
setErrorMessage('');
setInputList(prevInputs => {
const updatedInputList = [...prevInputs];
const targetInput = findInputByIndex(index, updatedInputList);
targetInput.value = value;
// 새로운 인덱스를 inputs 배열 길이를 기준으로 설정
const newIndex = updatedInputList[updatedInputList.length - 1].index + 1;
return [...updatedInputList, {index: newIndex, value: ''}];
});
}
```
변경된 사항은 해당 input이 마지막 Input임이 확인된다면, 값은 변경하지 못하도록 했다.
targeting된 값을 변경할 수 있으면서 새로운 Input을 생성하면 Input의 첫 글자에 invalid한 값이 들어올 수 있기 때문이다. 해당 조건만을 통해서는 들어온 첫번째 값이 valid한 지 확인하지 못하기 때문이다. 그렇기에 첫번째 값으로 invalid한 값이 들어올 수 있었다. 이후 두번째 값부터는 valid …
=> [FE] useDynamicInput 버그 수정

server/src/main/resources/application.yml, server/src/main/resources/logback-spring.xml
- close #322 
- Logback 롤링 정책을 7일 -> 1일 & 10MB로 수정했습니다. 
- 로그 레벨에 따라 파일을 분리했습니다.
=> [BE] LogBack 롤링 정책 수정, 로그 레벨에 따른 분리

server/src/main/resources/logback-spring.xml
- default -> dev 오타 수정
- prod 프로파일 추가
=> [BE] 로그백 설정 오타 수정

client/src/components/Modal/SetActionModal/AddMemberActionListModalContent/OutMember.tsx, client/src/hooks/useDynamicInput.tsx, client/src/hooks/useSearchInMemberList.ts
- close #337 
입력에 따라서 간헐적으로 can submit이 적절하게 반영되지 않았던 현상 해결했어요
https://github.com/user-attachments/assets/b95d65f8-f825-4e4a-958e-fa32a28bae43
버그의 원인은 크게 2가지가 있습니다.
1. 검색어 클릭 시 단순 set만 실행했고 validate 로직이 실행되지 않았습니다. 그래서 validate 로직을 돌아가게 하기 위해 handleInputChange 함수에서 validate 로직을 분리했어요
2. can submit 호출 시점을 변경했습니다. 이전의 can submit 함수는 input이 change되자마자 실행됩니다. 하지만 can submit을 판별하는 로직은 state에 의존합니다. 그래서 아직 setter가 반영이 되기 전에 can submit 함수가 돌아가게 되어 최신 상태의 submit 상태를 판별할 수 없었습니다. 그래서 input state가 반영된 시점에 can submit을 실행할 수 있도록 useEffect를 이용했습니다.
이건 사소한 것이지만 can submit 로직에 errorIndexList가 비어있는지도 체크하게 했습니다. 에러가 없었을 때 submit이 가능해야 한다고 생각해서 추가했어요!
두 가지를 고치고 다른 dynamic input 사용처에 영향을 끼치는지 확인해본 결과 버그는 없었는데 혹시나 문제 생기면 어디서 생겼는지 알려주시면 해결해볼게요..!
추가로 첫 번째 입력했을 때 동적으로 칸이 생기는 것은 validate 로직과는 크게 상관이 없어 보입니다. …
=> [FE] 인원 탈주 추가 시 disable 버그

client/src/apis/useFetch.ts, client/src/global.d.ts
- close #342 
Sentry CaptureError를 배포 환경에서만 실행되도록 설정했습니다.
Sentry는 배포 환경에서 사용자가 우리 프로그램을 이용하면서 발생한 에러를 알려주는 기능이므로 개발환경에서는 필요 없기 때문이에요
그래서 배포 환경과 개발 환경의 구분이 필요했고, global.d.ts에 아래 코드를 추가했습니다
```ts
declare namespace NodeJS {
interface ProcessEnv {
readonly NODE_ENV: 'development' | 'production' | 'test';
}
}
```
process.env.NODE_ENV를 하게 되면 타입 추론이 string | undefined으로 나오게 되는데
위 같이 선언을 해주게 되면 'development' | 'production' | 'test' 세 가지로 타입이 추론됩니다.
그래서 사용 측에서 undefined를 생각해주지 않아도 되기 때문에 위를 추가했어요.
그리고 추가로 env에 있는 key도 위에 추가를 해주면 env의 값이 없을 때 빈 문자열로 만들어서 string으로 타입을 맞춰주는 작업을 하지 않아도 가능해요!
그래서 다음 이슈로 그것을 리팩토링해서 올릴게요
Sentry를 배포 환경에서만 돌리도록 한 코드는 이렇게입니다.
```ts
if (process.env.NODE_ENV === 'production') {
captureError(error, navigate, eventId);
}
```
=> [FE] Sentry prod 환경에서만 돌아가도록 fetcher 설정

client/src/apis/baseUrl.ts, client/src/global.d.ts, client/src/pages/CreateEventPage/CompleteCreateEventPage.tsx, client/src/pages/EventPage/EventPageLayout.tsx, client/src/utils/getEventPageUrlByEnvironment.ts
- close #344 
env 환경 변수에 대한 타입을 정의해줬습니다.
```ts
declare namespace NodeJS {
interface ProcessEnv {
readonly NODE_ENV: 'development' | 'production' | 'test';
// env keys
readonly API_BASE_URL: string;
readonly AMPLITUDE_KEY: string;
}
}
```
이렇게 적용했을 때 process.env.API_BASE_URL의 타입은 string | undefined가 아닌 string입니다.
=> [FE] 환경 변수 타입 선언

client/src/components/Modal/SetActionModal/DeleteMemberActionModal/DeleteMemberActionModal.tsx, client/src/hooks/useDeleteMemberAction.tsx
- close #346 
useDeleteMemberAction 토스트 함수 결합도 제거를 해서 UI 컴포넌트에 위임했습니다.
삭제 멤버로 추가할 때 특수한 케이스에 대해 경고를 해주는 기능이라는 함수로 분리하여, 이미 지워진 멤버이거나 이전에 액션이 있는 멤버일 때 경고를 합니다.
```ts
const alertSpecificCaseFromAddDeleteMember = (memberAction: MemberAction) => {
if (!memberActionList.includes(memberAction)) {
showToast({
isClickToClose: true,
showingTime: 3000,
message: '이미 삭제된 인원입니다.',
type: 'error',
bottom: '160px',
});
return;
}
if (isExistSameMemberFromAfterStep(memberAction)) {
showToast({
isClickToClose: true,
showingTime: 3000,
message: `이후의 ${memberAction.name}가 사라져요`,
type: 'error',
position: 'top',
top: '30px',
style: {
zIndex: 9000,
},
});
}
};
```
=> [FE] useDeleteMemberAction 토스트 함수 결합도 제거

HDesign/package-lock.json, HDesign/package.json, HDesign/src/components/Text/Text.style.ts, HDesign/src/components/Title/Title.stories.tsx, HDesign/src/components/Title/Title.tsx, client/package-lock.json, client/package.json, client/src/components/Modal/SetInitialMemberListModal/SetInitialMemberListModal.tsx, client/src/pages/EventPage/AdminPage/AdminPage.tsx
- close #348 
1. 기존의 Title component의 description 부분이 앱의 전반적인 가이드를 제공해 주고 있지만, 유저들이 읽지 않고 넘어가는 경우가 너무 많음
2. 또한, 이곳에 적힌 UX writing이 직관적이지 못하고 혼동을 일으키는 경우가 많다는 피드백을 받음
1. Title component의 description 부분 폰트 사이즈 변경
2. 일부 UX writing 유저 친화적으로 변경
3. Text component가 줄바꿈 문자를 인식하도록 변경
```tsx
const baseStyle = css({
whiteSpace: 'pre-line',
});
```
whiteSpace : pre-line 속성을 통해서 Text component가 줄바꿈 문자를 인식하도록 변경
=> [FE] 사용성 개선 - Title component 변경 및 UX writing 수정

client/src/hooks/useSetPassword.ts, client/src/pages/CreateEventPage/SetEventPasswordPage.tsx, client/src/pages/CreateEventPage/index.ts, client/src/router.tsx
- close #351 
비밀번호 입력 페이지에 있는 로직을 커스텀 훅으로 분리했습니다.
useSetPassword.ts
location state가 없을 때 홈으로 리디렉션 시키는 코드는 비정상적인 접근에 대한 처리입니다.
비밀번호를 입력하는 기능과 큰 관련이 없다고 판단해서 UI 컴포넌트에 로직을 남겨두었습니다.
useSetPassword 훅은 비밀번호 입력 값, 에러 메시지, 제출 가능 여부, 제출 함수, input change 핸들러 다섯 가지를 제공해줍니다.
또한 event name 상태도 location.state.eventName을 바로 꺼내 쓰는 방식으로 변경하여, eventName 상태를 지웠습니다. useEffect로 location.state가 비어있는 상태에서는 홈으로 리디렉션 시키기 때문에 해당 페이지에 정상적으로 접근했을 때는 location.state.eventName이 있다고 판단할 수 있어서 useState를 지웠습니다.
=> [FE] 비밀번호 입력 페이지 커스텀 훅으로 분리

HDesign/src/components/Tabs/Tabs.style.ts
- close #355 
탭을 클릭했을 때 전체가 클릭 된 것처럼 보이는 현상 해결했습니다.
아래 css 한 줄 추가해주니깐 되네요;;;
WebkitTapHighlightColor: 'transparent',
이전
https://github.com/user-attachments/assets/e09da3c8-ef11-468b-913e-3ce2ed4f3f08
이후
https://github.com/user-attachments/assets/2419a808-357e-4e0b-b819-4a74e6db9ba6
=> [FE] 탭 클릭 시 탭 전체가 클릭 되는 현상

HDesign/package-lock.json, HDesign/package.json, HDesign/src/components/EditableItem/EditableItem.Input.style.ts, HDesign/src/components/EditableItem/EditableItem.Input.tsx, HDesign/src/components/EditableItem/EditableItem.Input.type.ts, HDesign/src/components/EditableItem/EditableItem.context.tsx, HDesign/src/components/EditableItem/EditableItem.input.stories.tsx, HDesign/src/components/EditableItem/EditableItem.stories.tsx, HDesign/src/components/EditableItem/EditableItem.style.ts, HDesign/src/components/EditableItem/EditableItem.tsx, HDesign/src/components/EditableItem/EditableItem.type.ts, HDesign/src/components/EditableItem/useEditableItem.ts, HDesign/src/components/EditableItem/useEditableItemInput.ts, HDesign/src/index.tsx
- close #353 
- 현재 가장 비중있는 이벤트가 지출 내역 등록인데, 이 과정이 직관적이지 않고 불필요한 많은 동직이 필요합니다.
- 현재 플로우는 "행동 추가 버튼" 클릭 -> 바텀시트에서 인원과 지출 중 선택 -> 지출내역 및 금액 입력 -> 추가 완료 버튼 클릭
- 플로우가 길기도 하며, 그 과정에서 유저들이 올바른 길로 가지 못하게 헷갈리는 과정이 많습니다.
- 예를 들어, 지출과 인원을 골라야 하는 점, 지출내역과 금액의 input이 서로 헷갈리는 점, 여러개의 인풋이 가능한걸 인지하지 못하는 점 등
- 이에 따라 기존의 화면을 벗어나지 않고, 익숙한 UI에서 바로 지출내역과 금액을 입력할 수 있는 Component를 구현합니다.
- `EditableItem`의 사용처에서도 Input의 value에 접근할 수 있도록 합성컴포넌트 도입을 고려합니다.
- children(`EditableItemInput`)이 focus되었는지 혹은 모든 focus가 없어졌는지에 따라 실행시킬 함수를 prop으로 받도록 고려합니다.
- children(`EditableItemInput`)이 focus되었는지 혹은 모든 focus가 없어졌는지를 파악하기 위해서 provider 구현을 고려합니다.
- `EditableItemInput`의 폰트 크기를 다양하게 쓸 수 있도록, `textSize` prop을 optional로 받도록 고려합니다.
- `EditableItemInput`에 error 상태를 표시하기 위해, `hasError`를 optional로 받도록 고려합니다.
```tsx
// …
```
=> [FE] 사용성 개선 - 지출 내역 입력 아이템 구현

client/src/pages/CreateEventPage/CompleteCreateEventPage.tsx, client/src/pages/CreateEventPage/SetEventNamePage.tsx, client/src/pages/CreateEventPage/SetEventPasswordPage.tsx
- close #349 
행사 생성 완료 페이지에서 불필요한 상태를 제거했습니다.
location.search로 충분히 가져올 수 있는 것을 useEffect를 사용해서 setter를 불러서 불필요한 상태를 이용하고 있다고 생각했기 때문입니다.
추가로 사용하지 않는 import 문도 제거했어요!
=> [FE] 행사 생성 완료 페이지에서 불필요한 상태 제거

server/src/main/java/server/haengdong/presentation/EventController.java, server/src/main/java/server/haengdong/presentation/response/ActionResponse2.java, server/src/main/java/server/haengdong/presentation/response/ActionsResponse.java, server/src/test/java/server/haengdong/docs/EventControllerDocsTest.java
- close #372 
액션 이력 조회 v2로 플랫한 형태로 기능 구현했습니다.
/api/events/{eventId}/actions/v2
```
{
"actions": [
{
"actionId": 2221,
"name": "감자탕",
"price": "10,000",
"order": 1,
"type": "BILL"
},
{
"actionId": 22,
"name": "인생네컷",
"price": "10,000",
"order": 2,
"type": "BILL"
},
{
"actionId": 13,
"name": "망쵸",
"price": null,
"order": 3,
"type": "IN"
},
{
"actionId": 34,
"name": "백호",
"price": null,
"order": 4,
"type": "IN"
},
{
"actionId": 54,
"name": "망쵸",
"price": null,
"order": 5,
"type": "OUT"
},
{
"actionId": 612,
"name": "백호",
"price": null,
"order": 6,
"type": "OUT"
},
{
"actionId": 137231,
"name": "노래방",
"price": "20,000",
"order": 7,
"type": "BILL"
}
]
}
```
=> [BE]  액션 이력 조회 v2 기능 구현

client/src/apis/request/member.ts, client/src/hooks/useSearchInMemberList.ts
- close #367 
인원 탈주 검색이 되지 않는 버그가 있습니다.
원래는 검색 리스트가 나와서 선택할 수 있어야 하지만 그렇지 않았어요
버그의 원인은 api 명세의 변경이었습니다.
members -> memberNames 변동과 Array<{name: string}> -> Array<string>의 형식 변화를 알아채지 못해서 이 형식을 아래와 같이 수정해주니 정상적으로 돌아가요~~~
```ts
export type ResponseGetCurrentInMemberList = {
memberNames: string[];
};
export const requestGetCurrentInMemberList = async (eventId: string) => {
return await requestGet<ResponseGetCurrentInMemberList>({
baseUrl: BASE_URL.HD,
endpoint: `${TEMP_PREFIX}/${eventId}/members/current`,
});
};
```
=> [FE] 인원 탈주 검색이 되지 않는 버그

client/src/components/Modal/SetActionModal/AddMemberActionListModalContent/OutMember.tsx, client/src/constants/errorMessage.ts, client/src/hooks/useDynamicInput.tsx, client/src/hooks/useInput.tsx, client/src/hooks/useSearchInMemberList.ts, client/src/hooks/useSetAllMemberList.tsx, client/src/utils/isArraysEqual.ts, client/src/utils/validate/validateMemberName.ts
- close #340
input과 관련된 훅은 useDynamicInput, useDynamicBillActionInput, useSetAllMemberList 3가지가 존재한다. 이 3가지 훅은 공통적으로 사용하는 부분이 존재한다.
- 입력된 값을 상태에 업데이트
- 올바르지 않은 입력 값일시, errorText와 error 테두리 띄우기
- 입력 값에 따라 canSubmit 관리
위와 같이 공통적으로 사용하는 코드가 3가지 정도 존재한다.
이때, 공통적으로 사용되는 코드 중 하나의 hook에서 버그가 발생하여 해결하면 다른 hook에서도 찾아서 똑같이 변경된 코드를 반영했다. 이런 일이 빈번히 일어나다 보니 불편함을 느끼게 되었다. 따라서 공통적으로 사용하는 로직은 useInput Hook으로 분리하여 각 hook에서 사용하도록 했다.
단, 여기서 useDynamicBillActionInput은 UI 변경에 따라 사용하지 않을 것으로 판단되어 수정하지 않았다. 수정된 파일은 useDynamicInput, useSetAllMemberList, useInput이다.
- 공통적으로 사용하는 상태
```tsx
const [inputList, setInputList] = useState<T[]>(initialInputList);
const [errorMessage, setErrorMessage] = useState('');
const [errorIndexList, setErrorIndexList] = useState<number[]>([]);
const [canSubmit, setCanSubmit] = …
```
=> [FE] 공통 input 코드를 useInput hook으로 분리

server/src/main/java/server/haengdong/application/ActionService.java, server/src/main/java/server/haengdong/application/BillActionService.java, server/src/main/java/server/haengdong/application/response/ActionAppResponse.java, server/src/main/java/server/haengdong/domain/action/BillAction.java, server/src/main/java/server/haengdong/domain/action/BillActionDetail.java, server/src/main/java/server/haengdong/domain/action/MemberBillReport.java, server/src/main/java/server/haengdong/presentation/response/ActionResponse.java, server/src/test/java/server/haengdong/application/ActionServiceTest.java, server/src/test/java/server/haengdong/application/BillActionServiceTest.java, server/src/test/java/server/haengdong/docs/EventControllerDocsTest.java, server/src/test/java/server/haengdong/domain/action/BillActionTest.java, server/src/test/java/server/haengdong/domain/action/MemberBillReportTest.java
- close #374 
- 참여자별 정산 현황 조회 시 BillActionDetail을 통해 각 참여자의 정산 금액을 계산하도록 수정
- 액션 이력 조회 시 지출 액션 고정 금액 설정 여부 필드 추가
=> [BE] 참여자별 정산 현황 조회 및 액션 이력 조회 수정

server/src/docs/asciidoc/billActionDetail.adoc, server/src/docs/asciidoc/index.adoc, server/src/main/java/server/haengdong/application/BillActionDetailService.java, server/src/main/java/server/haengdong/application/BillActionService.java, server/src/main/java/server/haengdong/application/request/BillActionDetailUpdateAppRequest.java, server/src/main/java/server/haengdong/application/request/BillActionDetailsUpdateAppRequest.java, server/src/main/java/server/haengdong/application/response/BillActionDetailAppResponse.java, server/src/main/java/server/haengdong/application/response/BillActionDetailsAppResponse.java, server/src/main/java/server/haengdong/domain/action/BillAction.java, server/src/main/java/server/haengdong/domain/action/BillActionDetail.java, server/src/main/java/server/haengdong/domain/action/BillActionDetailRepository.java, server/src/main/java/server/haengdong/exception/HaengdongErrorCode.java, server/src/main/java/server/haengdong/presentation/BillActionDetailController.java, server/src/main/java/server/haengdong/presentation/request/BillActionDetailUpdateRequest.java, server/src/main/java/server/haengdong/presentation/request/BillActionDetailsUpdateRequest.java, server/src/main/java/server/haengdong/presentation/response/BillActionDetailResponse.java, server/src/main/java/server/haengdong/presentation/response/BillActionDetailsResponse.java, server/src/test/java/server/haengdong/application/BillActionDetailServiceTest.java, server/src/test/java/server/haengdong/application/BillActionServiceTest.java, server/src/test/java/server/haengdong/application/MemberActionServiceTest.java, server/src/test/java/server/haengdong/docs/BillActionDetailControllerDocsTest.java, server/src/test/java/server/haengdong/presentation/BillActionDetailControllerTest.java, server/src/test/java/server/haengdong/presentation/ControllerTestSupport.java
- close #365 
지출에 포함된 참여자들의 개별 지출 금액을 조회합니다.
EventId, actionId로 해당 행사와 지출 액션이 존재하는지 확인하고 존재하지 않으면 예외가 발생합니다.
지출에 포함된 참여자들의 개별 지출 금액을 수정합니다.
BillAction이 가지고있는 총 금액과 비교하여 수정 요청 금액이 일치하지 않는 경우 예외를 던집니다.
수정 요청에 포함된 참여자의 이름으로 BillActionDetail을 조회하여 일치하지 않는 참여자가 있는 경우 예외를 던집니다.
=> [BE] 참여자 개별 지출 금액 수정 및 조회 기능 구현

server/src/main/java/server/haengdong/config/AdminInterceptor.java, server/src/main/java/server/haengdong/exception/GlobalExceptionHandler.java
- close #391 
GlobalExceptionHandler에서 HttpRequest 정보를 추출해서 로그에 함께 남겼습니다.
=> [BE] 에러를 재현할 수 있는 로그로 수정

client/src/components/Modal/SetActionModal/AddBillActionListModalContent/AddBillActionListModalContent.tsx, client/src/hooks/useDeleteMemberAction/useDeleteMemberAction.test.tsx, client/src/hooks/useDeleteMemberAction/useDeleteMemberAction.tsx
- close #382 
현재는 삭제 대상 리스트를 전체에서 - 지운 리스트를 제외한 현재 남아있는 리스트 aliveMemberList로 관리되고 있습니다. 하지만 이를 삭제 인원을 담는 deleteMemberList로 변경해서 삭제 관련 로직을 더 직관적으로 작성했습니다.
관리 대상을 삭제로 바꾸니 오히려 코드 가독성이 올라간 것 같아요! (알려준 웨디 당신은 도대체ㄷㄷㄷ)
AddBillActionListModalContent.tsx 에서 사용되고 있는 useDynamicBillActionInput 내부에서 errorIndexList가 사용되지 않고 export도 되고 있지 않아요;; 그래서 지워버렸습니다. 나중에 추가가 될 때 넣어줘도 좋을 것 같지만 이 부분 디자인 변경 예정이라 제 생각에는 불필요하다고 생각하긴 합니다
=> [FE] 멤버 액션 삭제 훅 리팩토링

client/src/hooks/useSetEventName.ts, client/src/pages/CreateEventPage/CompleteCreateEventPage.tsx, client/src/pages/CreateEventPage/SetEventNamePage.tsx, client/src/pages/CreateEventPage/SetEventPasswordPage.tsx
- close #384 
이벤트 이름 입력받는 부분 커스텀 훅으로 분리했습니다.
useSetEventName 훅은 input value (eventName), 에러 메시지, 제출 가능 상태, 이벤트 이름 입력 핸들러 네 가지를 제공합니다.
UI 컴포넌트는 navigate 기능만 남겨두었습니다.
추가로 비밀번호에서 생성 완료 페이지로 navigate 시킬 때 replace true 옵션을 추가했습니다. navigate를 할 때 페이지를 대체시킴으로써 뒤로 가기를 물리적으로 막았습니다. 비밀번호에서 이름은 뒤로가기가 가능합니다. (뒤로가기 버튼이 존재하기 때문)
navigate state를 지우는 방향으로 하고 싶었지만 생각보다 잘 되지 않아서.. 이 방법으로 가능하다면 알려주세요;;;
=> [FE] 이벤트 생성 페이지 리팩토링

server/src/main/java/server/haengdong/application/BillActionDetailService.java, server/src/main/java/server/haengdong/application/BillActionService.java, server/src/main/java/server/haengdong/application/MemberActionService.java, server/src/main/java/server/haengdong/application/request/BillActionDetailUpdateAppRequest.java, server/src/main/java/server/haengdong/application/response/BillActionDetailAppResponse.java, server/src/main/java/server/haengdong/domain/action/BillActionDetail.java, server/src/main/java/server/haengdong/presentation/request/BillActionDetailUpdateRequest.java, server/src/main/java/server/haengdong/presentation/response/BillActionDetailResponse.java, server/src/test/java/server/haengdong/application/ActionServiceTest.java, server/src/test/java/server/haengdong/application/BillActionDetailServiceTest.java, server/src/test/java/server/haengdong/application/BillActionServiceTest.java, server/src/test/java/server/haengdong/application/MemberActionServiceTest.java, server/src/test/java/server/haengdong/docs/BillActionDetailControllerDocsTest.java, server/src/test/java/server/haengdong/domain/action/BillActionTest.java, server/src/test/java/server/haengdong/domain/action/MemberBillReportTest.java, server/src/test/java/server/haengdong/presentation/BillActionDetailControllerTest.java, server/src/test/java/server/haengdong/support/fixture/Fixture.java
- close #403 
BillActionDetail에 isFixed 필드를 추가해서,
관리자에 의해 수정된 지출 상세인지 상태를 관리합니다.
=> [BE] 수정된 지출 상세의 상태 저장

client/src/hooks/queries/useRequestGetStepList.ts, client/src/store/totalExpenseAmountStore.ts
- close #400 
총액 업데이트 함수를 사용하는 곳에서 총액 계산 로직을 부르는 것보다 store안에서 부르는 것이 사용하는 입장에선 더 직관적이고 편할 것 같아 그렇게 수정해보았습니다.
=> [FE] 총액 업데이트 로직을 store안으로 이동

client/src/GlobalStyle.ts
- close #407 
- 변경 전: body의 height가 `100lvh` 일 때,
- 변경 후: height가 `100%`일 때,
=> [FE]  action 로그가 길어질 경우 배경색 높이가 잘리는 버그

client/src/hooks/useDynamicInput.tsx, client/src/hooks/useInput.tsx, client/src/hooks/useSetAllMemberList.tsx
- close #404
1. 삭제 버튼을 클릭하면 바로 삭제 api 요청을 보내는 것을 확인함.
삭제 버튼을 클릭하고 수정완료 버튼을 클릭해야 삭제 api 요청이 전송되어야 함.
2. 삭제 버튼을 클릭한 후 삭제한 input의 이후 input들을 수정하면 값이 변동되지 않는 것을 확인함. 
변동되지 않는 input의 다음 Input을 입력하면 값이 해당 값으로 변경됨
- 삭제 버튼을 클릭하면 바로 삭제 api 요청
merge를 하는 과정에서 이전 로직이 추가된 것을 확인함.
- 삭제 버튼 클릭 후 발생하는 버그
useInput에서 가져오는 inputList(editedAllMemberList)의 index와 useSetAllMemberList의 index가 일치하지 않아서 발생하는 에러였다.
`[소하,웨디,쿠키,토다리]`가 존재할 때 index는 `0,1,2,3`이다. ‘웨디’를 삭제하면 index가 재정렬되지 않고 그대로 `[소하,쿠키,토다리]`가 `0,2,3`으로 존재한다. 그러나 useSetAllMemberList에서는 index가 재정렬되면서 `[소하,쿠키,토다리]`가 `0,1,2`으로 변한다. (이때, 진짜 재정렬이 된다기 보다는 useSetAllMemberList에서 handleChange에 index를 넣어주는데, 이 index는 input을 렌더링하는 컴포넌트의 index이다. 즉, 삭제가 반영된 index이다.)
만약 토다리의 이름을 변경하려고 한다고 가정하자.
재정렬된 토다리의 index는 2이다. 하지만 재정렬되지 않는 index 2는 쿠키이다.
useInput에서 사용하는 …
=> [FE] 전체 인원 수정 '삭제' api 로직 롤백 수정

HDesign/package-lock.json, HDesign/package.json, HDesign/src/components/EditableItem/EditableItem.Input.style.ts, HDesign/src/components/EditableItem/EditableItem.Input.tsx, HDesign/src/components/EditableItem/EditableItem.Input.type.ts, HDesign/src/components/EditableItem/EditableItem.input.stories.tsx, HDesign/src/components/EditableItem/EditableItem.stories.tsx, HDesign/src/components/EditableItem/EditableItem.style.ts, HDesign/src/components/EditableItem/EditableItem.tsx, HDesign/src/components/EditableItem/EditableItem.type.ts, HDesign/src/type/withTheme.ts, client/src/components/StepList/StepList.tsx
- close #397 
<br/>
<br/>
value를 `EditableItem.Input`에 넘겨주지 않으면 가상 컴포넌트가 value 길이만큼의 width를 갖지 못하기 때문에 동적으로 width가 변하지 않습니다. 사용하실 땐 꼭 꼮 꼬꼬꼬꼮 `value` props를 넘겨주세요!!!
```js
<EditableItem.Input value={value} {...rest} />
```
(안넘겨주면 이렇게 됨)
https://github.com/user-attachments/assets/101a5cd9-aa08-48e0-8b59-221ea1c8b7a9
- 원래 이 브랜치가 모달 구현을 위한 것이었으나, 이 동적 width작업이 선행되어야 디자인대로 만들 수 있을 것 같아서 397브랜치를 디자인 시스템 수정으로 바꿨습니다.
- input의 width가 fit-content, min-content로는 조절이 불가능했습니다.
- 시안을 보니 동적으로 input의 width를 바꿔야 했습니다.
동적으로 width를 바꾸는 컨셉은 [샌드박스](https://codesandbox.io/p/sandbox/input-box-with-dynamic-width-r7lol?file=%2Fsrc%2FinlineEditor.js%3A95%2C12-97%2C17)를 참고했습니다.
input이 동적 wdith를 가질 수 없고 고정 width는 가능하기 때문에 처음에는`글자수 * 그 글자가 차지하는 크기`px 방법을 생각했었습니다. 다만 이 방법은 모든 charactor마다의 width(px)를 알고 계산해주어야 하기 때문에 …
=> [FE] EditableItem.Input이 동적인 width를 갖도록 수정

client/src/hooks/useMemberReportListInAction/useMemberReportInput.tsx, client/src/hooks/useMemberReportListInAction/useMemberReportListInAction.test.tsx, client/src/hooks/useMemberReportListInAction/useMemberReportListInAction.ts, client/src/utils/validate/validateMemberReportInAction.ts
- close #422 
차등 적용 적용 중 지원되지 않는 기능을 수정했습니다.
1. 해당하는 지출 금액이 변경되어도 반영해주는 것
서버에서 온 지출 금액과 현재 상태의 지출 금액이 다를 때 재계산하는 기능을 추가했습니다.
이 때 isFixed는 전부 false로 조정하고 여기서 발생하는 나머지 금액은 마지막 사람에게 부과됩니다.
```tsx
const totalPriceFromServer = memberReportListInActionFromServer.reduce((acc, cur) => acc + cur.price, 0);
if (totalPriceFromServer !== totalPrice) {
reCalculatePriceByTotalPriceChange();
}
}, [totalPrice]);
```
2. 하나라도 isFixed flag가 있는지 파악
isExistAdjustedPrice 함수를 사용하면 됩니다.
리스트에 isFixed가 하나라도 있으면 true, 아니면 false를 줍니다.
```tsx
const isExistAdjustedPrice = () => {
return memberReportListInAction.some(member => member.isFixed === true);
};
```
3. input이 0이 되지 않는 버그
validateMemberReportInAction에서 빈 값을 허용하지 않는 validation 조건을 삭제했습니다.
4. 3명 중 2명이 isFixed일 때 마지막 input 입력이 되는 현상 (계산은 되지 않음) …
=> [FE] 차등 적용 적용 중 지원되지 않는 기능 수정

client/package-lock.json, client/package.json, client/src/components/StepList/BillStepItem.tsx, client/src/components/StepList/Step.tsx, client/src/components/StepList/StepList.tsx, client/src/hooks/useSetBillInput.ts, client/src/pages/EventPage/AdminPage/AdminPage.style.ts, client/src/pages/EventPage/AdminPage/AdminPage.tsx
- close #399
- 인원 변동 추가 / 지출 내역 추가 Button
디자인시스템 Button을 활용함. 다만, Button width가 부모만큼 커지지 않는 것을 확인.
각 Button에 `style width: 100%`를 추가하여 부모 width 만큼 늘어나도록 함.
- isAddEditableItem
해당 상태는 지출 내역 추가를 click 했는지를 나타낸다.
이 상태는 AdminPage에서 만들어져 BillStepItem까지 props drilling을 통해 전해진다.
context나 store를 사용하여 관리할까 고민했지만, 일단은 props로 넘겨주는 것으로 했다. 추후 어떤 방식으로 하는 것이 좋을 지 논의 후 리팩토링을 꼭 진행해야 한다.
- useSetBillInput
- handleChangeBillInput
각 Input에 onChange가 발생할 때, valid를 실행하여 올바른 값인지 검사한다.
isValid 하다면, 해당 field의 값을 set을 통해 BillInput 상태를 변경한다.
```tsx
const handleChangeBillInput = (field: BillInputType, event: React.ChangeEvent<HTMLInputElement>) => {
const {value} = event.target;
const {isValid} = validatePurchase({
...billInput,
[field]: value,
});
if (isValid) {
setBillInput(prev => ({
...prev,
[field]: value, …
```
=> [FE] 지출 내역 추가 변경사항 적용

client/src/GlobalStyle.ts
- close #421
body 태그에 heigth가 100%임에도 배경색상이 잘리는 문제가 발생.
body 태그의 부모에 높이가 존재하지 않아서 발생한 문제이다.
따라서 body 태그의 부모인 html 태그에 height를 100% 추가해주었다.
=> [FE] html height 100%

client/src/hooks/useMemberReportListInAction/useMemberReportListInAction.test.tsx, client/src/hooks/useMemberReportListInAction/useMemberReportListInAction.ts, client/src/mocks/handlers/memberReportInActionHandlers.ts
- close #432
차등 적용 인원이 2명일 때 계산되지 않는 버그가 있었어요.
조정이 되지 않은 인원이 1명 남았을 때, 아에 계산 로직이 돌아가지 않았기 때문이에요.
그래서 1명 남았을 때도 계산을 하도록 수정했어요.
-> 한 명이 남았을 때 마지막 input은 아에 disabled 처리가 되므로 관련로직을 훅에서 제거했어요.
=> [FE] 차등 적용 인원이 2명일 때 계산되지 않는 버그

client/src/components/Modal/SetActionModal/PutAndDeleteBillActionModal/PutAndDeleteBillActionModal.tsx
- close #439 
전체 금액 수정 시 계산이 마이너스가 되는 문제를 해결했어요.
훅에 현재 입력 값이 아니라 서버에서 온 값으로 넣어줘서 변경 값으로 인식을 하지 않았던 문제입니다.
=> [FE] 전체 금액 수정 시 계산이 마이너스가 되는 문제

client/src/GlobalStyle.ts, client/src/pages/MainPage/Nav/Nav.style.ts
- close #440 
몇번째인지 모르겠는... heigth 잘림 수정..
간단하게 일단 문제를 해결하고자 html 태그에 background-color를 넣어줬어요.
color를 넣어줌으로 배경색이 더이상 잘리지 않습니다! 왜냐면 기본 틀의 색상을 그냥 저걸로 박어버렸기에..
**하지만 문제는 랜딩페이지입니다.**
html의 배경색이 더이상 화이트가 아니기 때문에.. 다음과 같이 배경색이 들어가게 됩니다.
근데 일단은 랜딩페이지에 배경색이 들어가는 것 보다는 관리/홈 페이지에서 배경색이 잘리는 것이 더 크리티컬하다고 판단하여 일단 해당 방식으로 해결했습니다.
사실 더 괜찮게 해결할 수 있는 방법이 존재합니다.
id가 root인 태그의 바로 아래 태그에는 height가 100% 존재합니다. 이 height를 삭제해줍니다.
그러면 홈/관리 Nav 탭이 사라지게 됩니다. 이유는 해당 Nav 탭에는 height가 존재하지 않기 때문입니다.
따라서 홈/관리 Nav 탭에 heigth를 지정해주면 됩니다. (개발자도구에서만 확인했던 사항이라 정확하진 않을 것입니다.)
하지만 해당 방법은 수정을 하려면 디자인시스템도 수정해야 합니다. 그리고 공수도 더 들어가구요. 일단 당장 금요일이 시연이기 때문에 더 간단한 방식으로 해결했습니다.
=> [FE] 배경색상 height 버그

client/src/hooks/queries/useRequestDeleteAllMemberList.ts, client/src/hooks/queries/useRequestDeleteMemberAction.ts, client/src/hooks/queries/useRequestPutAllMemberList.ts
- close #444 
멤버가 변동됐을 때 지출 상세 정보 데이터가 날라가지 않는 버그 수정했습니다.
인원이 변동됐을 때 (추가 제외) 지출 상세 캐시를 무효화 시켜서 영향이 없도록 수정했습니다
=> [FE] 인원을 삭제했을 때 지출 상세 캐시 데이터 지우지 않는 문제

client/src/components/StepList/BillStepItem.tsx, client/src/components/StepList/StepList.tsx
- close #445 
- 서버로 부터 받은 stepName을 뿌립니다.
- 마지막 action이 Bill이 아닐 때, 지출 내역을 추가하면 client에서 만든 임의의 데이터를 출력합니다.
이때, stepName을 넣어주기 위해서 서버로 부터 받은 stepList의 마지막 action의 stepName에서 1을 더한 값을 사용합니다.
백엔드의 요청으로 인해 인원수 click시 BottomSheet가 띄워지지 않도록 주석처리한 커밋이 존재합니다.
=> [FE] Step에 stepName 반영하기

client/src/hooks/usePutAndDeleteBillAction.ts
- close #461 
mutateAsync를 사용함에도 불구하고 async/await 키워드가 없어서 순서 보장이 안됐던 문제를 해결했습니다.
=> [FE] api 순서보장 await없어서 안됨

client/src/components/StepList/BillStepItem.tsx
- close #468 
```tsx
<EditableItem.Input
placeholder="지출 내역"
textSize="bodyBold"
value={billInput.title}
onChange={e => handleChangeBillInput('title', e)}
autoFocus
></EditableItem.Input>
<Flex gap="0.25rem" alignItems="center">
<EditableItem.Input
placeholder="0"
type="number"
value={billInput.price || ''}
onChange={e => handleChangeBillInput('price', e)}
style={{textAlign: 'right'}}
></EditableItem.Input>
```
- 지출 내역 금액 default가 0이 아닌 `‘’`로 변경
지출 내역 금액의 value를 `value={billInput.price || ''}`로 변경했다.
만약 value의 값이 falsy(0)하다면 ''를 truthy하다면 price를 출력하도록 했다.
useSetBillInput에서 price 값을 0에서 `''`로 변경하려고 했으나, validate 검사나 Type이 price는 number였다. 이로 인해 발생하는 다른 수정이 많기 때문에 해당 방법으로 `''`을 value로 갖도록 했다.
- 지출 내역을 추가하면 title에 autoFocus
지출 내역 title input에 autoFocus 속성을 추가했다.
- enter 키를 누르면 …
=> [FE] 지출 Input 금액 default 변경 및 autoFocus

HDesign/package-lock.json, HDesign/package.json, client/package-lock.json, client/package.json, client/src/components/StepList/BillStepItem.tsx
- close #436
현재 지출 내역에 참여 인원별 차등적용되었는지, 그렇지 않은지 확인하는 방법이 없었습니다.
차등계산이 적용된 지출 내역의 경우 별표 표시가 됩니다.
전에 얘기했던 `변경에 유연하게 대응하는 방법`에서 얘기했던것 중에
저는 제일 큰게 역할분리라고 생각해요~~ 컴포넌트가 기능적으로 몇개의 역할을 하느냐 도 있겠지만,
하나의 컴포넌트 안에서도 `디자인`만 연관있는 부분, `데이터`를 보여주는 부분, `기능`을 수행하는 부분을 구분해 놓아야 된다고 생각합니다.
그리고 그 중 `디자인`만 연관있는 부분을 디자인 시스템에 위임하려고 했던 거였어요.
전에도 한번 말했지만, 디자인시스템에서 데이터나 기능에 대한 부분이 많이 들어있는것같아서
조금씩 조금씩 바쁘지 않을 때 리팩토링 해나가려는 생각입니다.
제가 원하는 이상적인 component는
`디자인`은 HDesign에서 가져와서 처리.
`데이터`는 react-query 및 zustand에서 가져와서 디자인시스템에 주입
`기능`은 custom Hook에 data을 넘겨줘서 처리
정도일 것 같아요~!~!
``
(물론 변경에 따른 client 코드도 적용할거에요!!)
=> [FE] StepList에 isFixed 디자인시스템 반영

client/src/apis/request/bill.ts, client/src/hooks/queries/useRequestDeleteAllMemberList.ts, client/src/hooks/queries/useRequestPutAllMemberList.ts, client/src/hooks/queries/useRequestPutMemberReportListInAction.ts
- close #457 
차등 정산 적용 시 캐시를 초기화하는데 왜 늦게 반영되는 걸까요?
-> 그건 모르겠고 캐시를 무효화가 아니라 캐시를 지움으로서 해결했습니다
차등 정산 내역을 수정할 경우 반영이 늦게 되는 모습이 있어 낙관적 업데이트를 적용해 이를 해결했습니다.
https://github.com/user-attachments/assets/a2629404-58bb-4b3b-a8f4-8eacc4883f09
https://github.com/user-attachments/assets/de546b73-59ae-4b8d-901b-f44c7e45fac8
우선순위가 낮아서 안하려고 했는데, 데모데이때 사용자들이 당황할 수 있는 요소라고 생각이 들어서 수정했어요.
=> [FE] 차등 정산 적용시 신선한 데이터가 바로 반영되지 않고 시간차를 두고 반영되는 부분 수정

client/src/hooks/useEventLogin.ts, client/src/hooks/useNavSwitch.tsx, client/src/pages/EventPage/AdminPage/EventLoginPage.tsx, client/src/pages/EventPage/EventPageLayout.tsx, client/src/router.tsx
- close #467 
관리자 로그인 페이지에서 스위치가 관리로 활성화되지 않는 버그를 해결했습니다.
관리자로 접속해서 들어간 페이지인데 관리가 활성화되지 않아서 유저가 나는 지금 어디있는거지라고 생각할 것 같아서, 너는 지금 관리페이지에 들어왔어 하지만 너는 "쿠키 is me"가 없기 때문에 관리할 수 없어 비밀번호 입력해! 라는 것을 더 잘 표시하기 위해 로그인 페이지에도 관리 탭이 활성화됐음을 강조했어요.
자세한 것은 영상으로
https://github.com/user-attachments/assets/4d4ec8ff-08f6-4c01-a341-82c004aacbf2
추가로 useEventLogin 훅을 만들어서 EventLogin 관련 로직을 훅으로 분리했어요.
=> [FE] 관리자 로그인 페이지에서 스위치가 관리로 활성화되지 않는 버그

server/src/main/java/server/haengdong/application/BillActionDetailService.java, server/src/main/java/server/haengdong/application/BillActionService.java, server/src/main/java/server/haengdong/application/MemberActionService.java, server/src/main/java/server/haengdong/application/request/BillActionAppRequest.java, server/src/main/java/server/haengdong/domain/action/BillAction.java, server/src/main/java/server/haengdong/domain/action/BillActionDetailRepository.java
- close #456 
BillActionDetail 초기화 시 totalPrice와 정합성이 안맞는 버그를 수정합니다.
양방향 연관관계를 최대한 활용해서 Service에 있는 도메인 로직들을 BillAction으로 위임시켰습니다.
=> [BE] BillActionDetail 초기화시 totalPrice와 정합성 안맞는 버그 수정 

HDesign/src/components/Flex/Flex.style.ts, HDesign/src/components/Flex/Flex.type.ts, HDesign/src/layouts/MainLayout.tsx, client/src/GlobalStyle.ts, client/src/pages/CreateEventPage/CompleteCreateEventPage.tsx, client/src/pages/CreateEventPage/SetEventNamePage.tsx, client/src/pages/CreateEventPage/SetEventPasswordPage.tsx, client/src/pages/EventPage/AdminPage/AdminPage.style.ts, client/src/pages/EventPage/HomePage/HomePage.tsx
- close #464 
- 스크롤이 길어질 때 배경색이 짤리고 길어지지 않았던 버그 수정했어요
- #root의 속성에서 height: 100%을 제거했어요.
- 스크롤이 생기지 않을 정도로 내용이 부족할 때 메인 레이아웃의 배경색이 안 채워지는 문제가 있었습니다. 그래서 MainLayout에 min height: 100vh를 추가로 넣으니 내용이 부족할 때도 배경색이 화면을 꽉 채우고 스크롤이 생겨도 같이 배경색이 따라서 내려오게 됩니다.
- 이도 행동 디자인이 변경됐기 때문에 `행동 디자인 재배포`가 필요합니다.
https://github.com/user-attachments/assets/e43a574e-4a1e-4717-920f-0e47fe983060
- 메인 레이아웃 배경색 변경
- 토다리와 배경색 논의 결과 메인 레이아웃의 배경색을 gray에서 lightGray로 바꾸자는 결론이 나서 메인레이아웃 backgroundColor props로 lightGray도 추가했습니다.
- 적용하기 위해서 `행동 디자인 재배포`가 필요하며, 배포가 된 후에 적용을 해야합니다.
- 생성 페이지 배경색 하얀색으로 설정
- 메인 레이아웃 background color props를 white를 적용했어요
- 이벤트 레이아웃 padding bottom 조정
- home의 경우 아래 아무 패딩도 없어서 2rem을 띄웠습니다
- admin의 경우 fixed button 때문에 8rem이 띄워졌는데 사라졌기 때문에 home과 동일하게 2rem으로 설정했습니다.
배경색 너무 힘들어요;;
=> [FE] 배경색아 제발

client/src/hooks/useSetBillInput.ts
- close #471 
useSetBillInput의 handleBlurBillRequest에 조건문을 추가했습니다.
title과 price의 값이 존재하지 않다면 지출 Input은 set을 통해 false가 되면서 닫히게 됩니다.
```tsx
const handleBlurBillRequest = () => {
const isEmptyTitle = billInput.title.trim().length;
const isEmptyPrice = Number(billInput.price);
// 두 input의 값이 모두 채워졌을 때 api 요청
// api 요청을 하면 Input을 띄우지 않음
if (isEmptyTitle && isEmptyPrice) {
postBillList(
{billList: [billInput]},
{
onSuccess: () => {
setBillInput(initialInput);
setIsAddEditableItem(false);
},
},
);
} else if (!isEmptyTitle && !isEmptyPrice) {
setIsAddEditableItem(false);
}
};
```
단, 해당 코드를 추가하면서 발생한 문제가 존재합니다.
price를 먼저 입력하는 것이 불가능합니다. 현재 input이 생성되면 title에 autoFocus가 됩니다. 이 상태에서 price를 먼저 입력하고 싶어 price input을 클릭하면 onBlur가 실행됩니다. 그리고 title과 price의 값이 비워져있기 때문에 지출 input이 닫힙니다.
해당 문제를 해결하기 위해서는 …
=> [FE] title과 price에 값이 존재하지 않을 경우 지출 input 닫기

client/src/pages/CreateEventPage/CompleteCreateEventPage.tsx
- close #477 
- #271 에서 작업했던 행사 완료 페이지가 유저테스트 결과 유저 친화적이지 않다는 결론을 내렸습니다.
- 기존엔 링크를 복사할 방법이 없어 이 페이지를 제작해 주었지만, 한번에 주어지는 정보가 너무 많고 복잡해 실제로 사용하는 유저들이 해당 페이지에서 정체되는 상황을 경험했습니다.
- 이에 다시 행사 생성 완료 페이지를 간소화합니다.
=> [FE] 행사 완료 페이지 간소화

client/src/components/Modal/SetInitialMemberListModal/SetInitialMemberListModal.tsx
- close #479 
- 유저 테스트 결과, 초기 시작인원 설정 바텀시트에서 이름이 아닌 명수(숫자)를 입력하는 경우가 많았습니다.
- placeholder로 무엇을 입력해야 하는지 명시하지 않아서 생기는 오류라고 판단했습니다.
- 시작 인원 추가 flow에서 placeholder를 생성해 주었습니다.
label이 눈에 잘 안띄나 보네요.... 흐으으음 ㅜㅜㅠ
디자인 정말 어렵다...
=> [FE] 초기 인원 설정 시 placeholder 없던 오류 수정

client/src/components/StepList/BillStepItem.tsx, client/src/pages/CreateEventPage/SetEventPasswordPage.tsx
- close #490 
- 기존에 지출내역의 금액 부분에 문자가 입력되는 버그 발생
https://github.com/user-attachments/assets/c2b91e71-a791-4e06-a7e9-fe3958545cdf
- `type=number`로 제한되어 있는 input에 초기값으로 `''`가 주어지다 보니 이 부분에서 문자열을 받으면서 버그가 발생함
- value 초기값을 `''`이 아닌 `null`을 줌으로써 해결함
=> [FE] 지출 내역 추가 시 금액에 숫자 외 다른 문자 입력 가능한 버그 수정

client/src/components/StepList/BillStepItem.tsx, client/src/components/StepList/MemberStepItem.tsx, client/src/pages/EventPage/AdminPage/AdminPage.tsx
- close #492
BottomSheet의 애니메이션이 적용되지 않던 버그가 있어 이를 수정합니다.
BottomSheet 구조상, 조건부 렌더링이 아닌, `isOpen` 상태의 변화를 통해 애니메이션을 적용해 주는 것이기 때문에, 조건부 렌더링을 진행하면 애니메이션이 적용되지 않습니다.
조건부 렌더링을 상태를 이용하도록 변경해 주었습니다.
런칭페스티벌을 앞두고, 급하게 변경사항을 적용했습니다.
간단한 인원 변동 추가 바텀시트와 인원 수정 바텀시트는 잘 작동하지만,
여러 상태가 엮여있는 전체 참여자 바텀시트와 금액 수정 바텀시트는 여전히 작동하지 않습니다.
바텀시트 관련한 부분들도 수정을 직접 해보니 굉장히 결합도가 높고 불필요한 코드가 많아보여요
레벨 4에서 할일이 정말 고봉밥이네요...
=> [FE] BottomSheet 애니메이션이 적용되지 않던 오류 수정

client/package-lock.json, client/package.json, client/src/App.tsx
- close #459 
react-query devtools 초기 설정을 했습니다.
도입한 목적은 귀여운 야자수를 확인할 수 있기 때문입니다.
사실 devtool을 설치하면 캐싱 데이터의 상태를 눈으로 확인할 수 있어서 셋팅해뒀습니다.
stale time, gc time을 임시로 1분씩 설정했습니다.
추후에 같이 논의해서 수정해봐요
=> [FE] React-Query devtools 환경 설정

server/src/main/java/server/haengdong/application/EventService.java, server/src/main/java/server/haengdong/domain/action/BillActionDetail.java, server/src/main/java/server/haengdong/domain/action/BillActionDetailRepository.java
- close #497 
참여자 이름 변경시 지출 상세 이름 변경 안되는 버그 수정
=> [BE] 참여자 이름 변경시 지출 상세 이름 변경 안되는 버그 수정

client/src/components/Modal/SetActionModal/PutAndDeleteBillActionModal/PutAndDeleteBillActionModal.tsx, client/src/components/StepList/MemberStepItem.tsx, client/src/pages/EventPage/AdminPage/AdminPage.tsx
- close #505 
#493 에서 bottomSheet 애니메이션을 적용했지만,
이로 인해 bottomSheet 내부의 autoFocus 문제와
bottomSheet가 내려간 뒤에서 overflow: hidden 이 되는문제가 발생했습니다.
배포를 앞두고 우선 변경 사항을 롤백합니다.
- #493 의 bottomSheet 애니메이션 적용 롤백
=> [FE] bottomSheet 애니메이션 적용 롤백

client/src/components/Modal/ExpenseDetailModal/ExpenseDetailModal.tsx, client/src/components/Modal/SetActionModal/PutAndDeleteBillActionModal/PutAndDeleteBillActionModal.tsx, client/src/components/StepList/BillStepItem.tsx
- close #504 
홈페이지에서 지출 내역 눌렀을 때 차등 정산 모달을 띄워야 합니다.
`PutAndDeleteBillActionModal`을 그대로 복사해서 `ExpenseDetailModal`을 만들었습니다. 컴포넌트명만 수정하고 스타일파일은 모두 PutAndDeleteBillActionModal에서 끌어왔습니다. 마찬가지로 타입명도 모두 그렇습니다. 시간이 없었습니다.
https://github.com/user-attachments/assets/a11830f6-bb1c-456c-9c90-1c1fed3147e3
=> [FE] 홈페이지에서 지출 내역 눌렀을 때 차등 정산 모달 뜨기

client/src/components/Modal/SetActionModal/AddMemberActionListModalContent/AddMemberActionListModalContent.tsx, client/src/components/StepList/MemberStepItem.tsx, client/src/components/StepList/StepList.tsx, client/src/hooks/useDynamicInput.tsx, client/src/hooks/useMemberReportListInAction/useMemberReportListInAction.test.tsx, client/src/hooks/useSetAllMemberList.tsx
- close #495
- 지출 내역: 상단 Bill action이 존재하지 않을 경우에 Input만 닫히고 Bill Container는 닫히지 않음
```tsx
if (hasAddedItem) {
setHasAddedItem(false);
setStepList(prev => [...prev.filter(({actions}) => actions.length !== 0)]);
}
// ...
}, [isAddEditableItem]);
```
`setStepList(prev => [...prev.filter(({actions}) => actions.length !== 0)]);` 추가
지출 내역 추가 버튼을 클릭하면 isAddEditableItem은 false에서 true가 된다. 직전에 Bill action이 존재하지 않을 경우 새로운 bill action을 임의로 생성한다. 이때 새로운 bill이 생성되면 hasAddedItem은 true가 된다. 
그리고 사용자가 input에 아무런 값도 입력하지 않을 경우 isAddEditableItem의 값은 false로 변환된다. 이때 useEffect의 의존성으로 isAddEditableItem가 존재하기 때문에 useEffect가 실행된다.
useEffect 내부의 코드를 살펴보자.
만약 hasAddedItem이 true라면, 즉 새로운 Bill action이 생성되었다면 isAddEditableItem을 false로 반환한다.
그리고 stepList에서 actions 배열을 도는데 actions의 값이 존재하지 않는 것은 …
=> [FE] 지출 내역 및 전체 참여자 버그

client/src/components/MemberReportList/MemberReportList.tsx, client/src/components/StepList/StepList.tsx, client/src/hooks/useSearchMemberReportList/useSearchMemberReportList.tsx
- close #519 
지출 내역이 없을 때 참여자가 보는 홈 페이지에서 없다고 띄웁니다.
=> [FE] 지출 내역이 없을 때 홈페이지에서 없다고 띄우기

server/src/main/java/server/haengdong/domain/action/Bill.java, server/src/main/java/server/haengdong/domain/action/BillDetailRepository.java, server/src/main/java/server/haengdong/presentation/BillController.java, server/src/test/java/server/haengdong/application/BillServiceTest.java, server/src/test/java/server/haengdong/docs/AdminBillControllerDocsTest.java, server/src/test/java/server/haengdong/docs/BillControllerDocsTest.java, server/src/test/java/server/haengdong/presentation/BillControllerTest.java, server/src/test/java/server/haengdong/presentation/admin/AdminBillControllerTest.java, server/src/test/java/server/haengdong/support/fixture/Fixture.java
feature/#546-part1 브랜치에서 작업 후, feature/#546 브랜치에 push pr 올립니다.
1. 지출 전체 조회
2. 지출 고정 금액 조회
3. 지출 내역 추가
4. 지출 수정
RestDocs, 컨트롤러, 서비스 테스트코드를 수정했습니다.
=> [BE] MemberAction 제거로 인한 Bill 도메인의 테스트 변경사항 반영 to feature/#546

client/src/components/Design/components/DepositToggle/DepositToggle.stories.tsx, client/src/components/Design/components/DepositToggle/DepositToggle.style.ts, client/src/components/Design/components/DepositToggle/DepositToggle.tsx, client/src/components/Design/components/DepositToggle/DepositToggle.type.ts, client/src/components/Design/components/Text/Text.style.ts
- close #554 
DepositToggle의 디자인 컴포넌트를 구현했습니다.
- 디자인 수정
issue에 올린 Toggle의 디자인은 Button 컴포넌트를 활용하여 디자인한 것입니다.
그러나, 해당 Toggle은 Button 컴포넌트를 활용해서는 만들 수 없습니다. 따라서, 이전에 Button 컴포넌트로 font 사이즈가 맞춰져 있던 것을 일반 Text 컴포넌트의 font 사이즈로 변경했습니다.
font 사이즈는 12px로 동일하나 line-height, padding을 변경해줬습니다.
- div 태그에 `role=”button”`
button 태그를 활용하려고 했으나, 퍼블리싱이 원하는 대로 동작하지 않는 이슈가 발생했습니다. 이는 아마도 모든 태그의 스타일을 초기화하기 때문이 아닐까.. 싶은...
따라서 div 태그를 활용하여 Toggle을 만들어줬습니다. 그러나 스크린 리더기에서는 해당 div가 버튼인지를 모를 것입니다. 그렇기에 div 태그에 role 속성을 추가해줬습니다. 
role 속성을 button으로 지정해주면, 스크린 리더기에서 해당 div가 button임을 인지할 수 있습니다.
- onToggle시 배경색 이동 애니메이션
onToggle된 값(입금 확인/미입금)에는 흰색 배경색이 들어갑니다. 이때, DepositToggle을 클릭하면 그 반대의 값 (true면 false, false면 true)으로 변경됩니다. 그러면서 흰 배경색도 해당 값으로 이동하게 됩니다. 이때, 이동하는 배경색에 애니메이션을 줬습니다. (대-토다리)
toggle-background라는 클래스 이름을 가진 …
=> [FE] 입금 상태를 관리하는 컴포넌트 DepositToggle 기능 구현

server/src/docs/asciidoc/bill.adoc, server/src/docs/asciidoc/billDetail.adoc, server/src/main/java/server/haengdong/application/EventService.java, server/src/main/java/server/haengdong/application/MemberService.java, server/src/main/java/server/haengdong/domain/bill/Bill.java, server/src/main/java/server/haengdong/domain/bill/MemberBillReport.java, server/src/main/java/server/haengdong/domain/event/Bank.java, server/src/main/java/server/haengdong/domain/event/Event.java, server/src/main/java/server/haengdong/domain/event/Password.java, server/src/main/java/server/haengdong/domain/member/Member.java, server/src/main/java/server/haengdong/exception/ErrorResponse.java, server/src/main/java/server/haengdong/exception/GlobalExceptionHandler.java, server/src/main/java/server/haengdong/exception/HaengdongErrorCode.java, server/src/main/java/server/haengdong/exception/HaengdongException.java, server/src/test/java/server/haengdong/application/MemberServiceTest.java, server/src/test/java/server/haengdong/docs/BillControllerDocsTest.java, server/src/test/java/server/haengdong/domain/member/MemberBillReportTest.java, server/src/test/java/server/haengdong/presentation/BillControllerTest.java, server/src/test/java/server/haengdong/presentation/admin/AdminBillControllerTest.java
- close #580
HaengdongErrorCode에서 구체적인 예외 메시지 전달을 위해 Domain을 참조하고
Domain에서 예외를 던지기 위해 HaengdongErrorCode를 사용하여 순환참조 문제가 있었습니다.
해결 방법
- HaengdongErrorCode는 예외 메시지의 포멧만 지정한다.
- HaengdongException은 HaengdongErrorCode와 예외메시지 포멧에 필요한 인자를 받아 예외 메시지로 변환한다.
- 도메인은 예외를 던질 때 HaengdongErrorCode와 예외 메시지 포멧에 필요한 인자를 전달한다.
```java
public enum HaengdongErrorCode {
/* Domain */
EVENT_NOT_FOUND("존재하지 않는 행사입니다."),
EVENT_NAME_LENGTH_INVALID("행사 이름은 %d자 이상 %d자 이하만 입력 가능합니다."),
EVENT_NAME_CONSECUTIVE_SPACES("행사 이름에는 공백 문자가 연속될 수 없습니다."),
EVENT_PASSWORD_FORMAT_INVALID("비밀번호는 %d자리 숫자만 가능합니다."),
BANK_NAME_INVALID("지원하지 않는 은행입니다. 지원하는 은행 목록: %s"),
ACCOUNT_LENGTH_INVALID("계좌번호는 %d자 이상 %d자 이하만 입력 가능합니다."),
...
}
public class HaengdongException extends RuntimeException {
private final HaengdongErrorCode errorCode; …
```
=> [BE] Domain 패키지와 Exception 패키지간의 순환 참조 해결

server/src/main/java/server/haengdong/application/response/EventDetailAppResponse.java, server/src/main/java/server/haengdong/domain/event/Event.java, server/src/main/java/server/haengdong/presentation/response/EventDetailResponse.java, server/src/test/java/server/haengdong/application/EventServiceTest.java, server/src/test/java/server/haengdong/docs/EventControllerDocsTest.java, server/src/test/java/server/haengdong/domain/event/EventTest.java, server/src/test/java/server/haengdong/presentation/EventControllerTest.java
- close #606
- dto에 account 대신에 bankName과 accountNumber를 반환하도록 수정
- entity에 getBankName()과 getAccountNumber() 추가
현재 엔티티 내부에 account 필드가 있습니다. 
account를 bankName과 accountNumber로 변환해야 하지만, 그러지 않았습니다. 
이유는 현재 스키마 마이그레이션이 진행 중으로, 관련 작업에 영향을 주지 않기 위함입니다.
=> [BE] 계좌 정보를 은행 정보과 계좌 번호로 분리해서 응답

server/src/docs/asciidoc/member.adoc, server/src/main/java/server/haengdong/application/MemberService.java, server/src/main/java/server/haengdong/domain/member/Member.java, server/src/main/java/server/haengdong/exception/HaengdongErrorCode.java, server/src/test/java/server/haengdong/application/MemberServiceTest.java
- close #609
멤버 정보 수정 API 예외 처리 로직을 수정했습니다.
```java
private void validateUpdatedNamesUnique(List<Member> eventMembers, List<Member> updatedMembers) {
Set<String> eventMemberNames = eventMembers.stream()
.map(Member::getName)
.collect(Collectors.toSet());
boolean memberNameDuplicated = updatedMembers.stream()
.map(Member::getName)
.anyMatch(eventMemberNames::contains);
if (memberNameDuplicated) {
throw new HaengdongException(HaengdongErrorCode.MEMBER_NAME_DUPLICATE);
}
}
```
위와 같이 updatedMembers로 들어온 모든 멤버에 대해 이름 중복을 검증하고 있었는데, 이름 변경이 있는 멤버에 대해서만 검증을 수행하도록 수정했습니다.
```java
private void validateUpdatedNamesUnique(List<Member> eventMembers, List<Member> updatedMembers) {
Map<Long, String> eventMemberNames = eventMembers.stream()
.collect(toMap(Member::getId, Member::getName));
Set<String> …
```
=> [BE] 멤버 정보 수정 API 호출 버그 수정

server/src/main/java/server/haengdong/exception/HaengdongErrorCode.java, server/src/main/java/server/haengdong/presentation/request/BillDetailUpdateRequest.java, server/src/main/java/server/haengdong/presentation/request/MemberSaveRequest.java, server/src/test/java/server/haengdong/application/MemberServiceTest.java
- close #642 
노션 API 명세서에 작성된 예외 상황별 예외코드와 메세지를 백엔드 코드에 맞게 동기화하고,
`HaengdongErrorCode` enum에서 더이상 사용하지 않는 `TOKEN_EXPIRED`을 삭제했습니다.
`지출 상세 수정` API 에서 사용하는 DTO `BillDetailUpdateRequest`의 `isFixed` 필드의 잘못된 검증 메세지를 제거하고 primitive 타입으로 변환했습니다. 또 `참여자 추가` API 에서 사용하는 DTO `MemberSaveRequest`의 `name` 필드에 검증을 추가했습니다.
=> [BE] API 명세서에 작성된 예외 최신화 및 코드 수정

client/src/hooks/useAccount.ts
- close #599 
조건문을 변경했습니다.
서버 상태가 아니라 클라이언트 상태가 빈 값인지를 확인해서 현재 입력 중인 값이 빈 값인지 검증해요
```ts
const existEmptyField = bankNameState.trim() === '' || accountNumberState.trim() === '';
```
여기도 마찬가지.. 상태 헷갈림입니다
새로운 상태가 빈 값인지를 체크해서 초기에 빈 값일 때 새로운 값이 반영이 되지 않는 버그를 수정했어요
```ts
if (bankNameState.trim() !== '' && bankName !== bankNameState) {
changedField.bankName = bankNameState;
}
if (accountNumberState.trim() !== '' && accountNumber !== accountNumberState) {
changedField.accountNumber = accountNumberState;
}
```
=> [FE] 계좌번호 입력 확인 버튼 활성화가 되지 않는 버그, 빈 값일 때 새로운 값이 반영되지 않는 버그

client/src/hooks/queries/member/useRequestDeleteMember.ts, client/src/hooks/queries/member/useRequestPutMembers.ts, client/src/hooks/useEventMember.ts
- close #600
입금 상태만을 변경하고 '수정완료' 버튼을 클릭하면 "중복 이름입니다" 버그가 발생했습니다.
이에 대한 문제는 api 구조의 문제로 결론이 났습니다. 따라서 해당 문제의 해결은 백엔드의 수정 후에 정확히 확인해봐야 할 것 같습니다.
전체 참여자 delete,put 요청 mutate대신 mutateAsync를 사용하여 요청 순서 보장했습니다.
순서를 보장하지 않는다면 delete 요청 전에 put 요청이 먼저 갈 수 있다는 문제가 존재합니다. 
delete 요청 전, put 요청이 가는 것이 왜 문제냐? 생각하실 수 있습니다. put 요청은 delete가 요청이 된 것을 기반으로 데이터가 존재합니다. 따라서 delete 요청이 무조건 선행 되어야 put 요청을 전송할 수 있습니다.
=> [FE] 입금 상태를 변경하고 '수정완료' 버튼 클릭 시, 중복 이름 버그 발생

client/src/hooks/useEventMember.ts, client/src/pages/EventPage/AdminPage/EventMember.style.ts, client/src/pages/EventPage/AdminPage/EventMember.tsx, client/src/pages/EventPage/AdminPage/EventMemberManage.tsx, client/src/router.tsx
- close #612
해당 상태를 추가했던 이유는 불필요한 렌더링을 줄이기 위해서였습니다. 그러나 이런 문제를 useMemo나 useCallback을 사용하여 불필요한 렌더링을 줄이면서 불필요한 상태도 제거하였습니다!
불필요한 렌더링을 줄이기 위해서 useCallback과 useMemo를 사용했습니다.
Manage라는 것은 굳이 붙이지 않아도 될 것 같습니다. AdminPage 폴더에 존재하기 때문입니다.
따라서 EventMemberManage 파일 이름을 EventMember로 변경했습니다.
리뷰할 때, 이름에 대한 의견이 들어와서 isCanRequest를 isCanSubmit으로 다른 페이지들과 통일시켰습니다.
=> [FE] useEventMember 불필요한 상태 제거 및 렌더링 성능 개선

client/src/components/Design/components/FixedButton/FixedButton.tsx
- close #620 
https://github.com/user-attachments/assets/eb987e79-c3c4-44bb-a7db-77f8f65e53ec
FixedButton 에서 button의 variant가 loading인 경우에 아래의 영상처럼 layout이 깨져 이상하게 보이는 오류가 존재했습니다.
이를 올바르게 수정하여 좋은 사용자경험을 주고자 합니다.
기존에 FixedButton이 아닌, 버튼이 한개일 경우 사용되는 width 240 설정이 적용되어 있어 이를 해제함으로써 해결
=> [FE] Loading Button으로 인해 Layout이 깨지는 문제

client/src/components/AmountInput/AmountInput.tsx
- close #630 
지출 추가 시 금액이 없는 경우 Text의 값이 없어 공간을 차지하지 않게 되면서
아래와 같이 layout이 변경됩니다.
https://github.com/user-attachments/assets/d6fa8b0c-46ca-417f-932f-265923988ba2
값이 없는 경우에도 "0" 값을 이용하여 가상의 placeholder를 구현하였습니다.
이로 인해 layout이 변경되지 않습니다.
input과 비슷하게 작동을 하는 `AmountInput` component이지만 NumberKeyboard를 사용하기 때문에 실제 input으로 구현하지는 않았습니다.
하지만 추후 접근성을 위해서라면 input 태그를 사용하는 방식으로 변경해야 할 것 같은데 어떻게 생각하시나요? 이 component는 input일까요? 그냥 값을 보여주는 div일까요?
`Top/Linte.tsx`와 `Top/EditableLine.tsx`,
`Amount/Amount`와 `Amount/EditableAmount.tsx`의 차이점을 보시면
쉽게 이해가 되실 것이라 생각합니다~
=> [FE] 지출 추가에서 입력된 금액이 없을 시 layout이 변경되는 문제

client/src/components/Design/components/NumberKeyboard/NumberKeyboardBottomSheet.tsx, client/src/components/Design/components/NumberKeyboard/useNumberKeyboardBottomSheet.ts
- close #617 
https://github.com/user-attachments/assets/08bc4d63-2236-4788-90c6-deb5b1bfaf3d
NumberKeyboardBottomSheet가 올라온 경우 해당 영역을 드래그 해도 스크롤이 가능한 문제가 있습니다.
이 경우 사용자가 의도하지 않은 대로 동작할 수 있고, 안좋은 유저 경험의 원인이 될 수 있다고 생각합니다.
```tsx
const bottomSheet = bottomSheetRef.current;
if (!bottomSheet) return;
const preventScroll = (e: TouchEvent) => {
if (bottomSheet.contains(e.target as Node)) {
e.preventDefault();
}
};
if (isOpened) {
document.addEventListener('touchmove', preventScroll, {passive: false});
}
return () => {
document.removeEventListener('touchmove', preventScroll);
};
}, [isOpened]);
```
- bottomSheet 영역에 touchMove Event가 있다면, touchEvent를 prevent 하도록 하는 코드를 작성했습니다.
- 따라서 BottomSheet 영역을 드래그해도 preventEvent로 인해 뒷 영역의 스크롤이 작동하지 않습니다.
=> [FE] NumberKeyboardBottomSheet 영역에서 스크롤이 가능한 문제

client/src/hooks/useMembersStep.ts
- close #620
지출 생성 시 지워졌던 멤버를 다시 추가할 수 없는 오류가  발생합니다.
예를 들어 1차에 이상, 감자, 망쵸 가 있을 때, 2차에서는 망쵸가 나가고 이상, 감자가 남습니다.
3차에서 망쵸를 다시 추가하려고 할 때, "현재 참여하고 있는 인원이 존재합니다" 에러가 발생합니다.
https://github.com/user-attachments/assets/617eac71-bdb3-426e-a3e9-e7578fd881ab
기존에는 새로 멤버를 추가할 때, 이미 있는 멤버인지 판별하기 위해 `currentMember`와 비교했었습니다.
```tsx
// useMembersStep.tsx
// ...
const setBillInfoMemberWithId = (name: string) => {
const existingMember = currentMembers.find(currentMember => currentMember.name === name);
if (existingMember) {
setBillInfo(prev => ({...prev, members: [...prev.members, {id: existingMember.id, name: name}]}));
} else {
setBillInfo(prev => ({...prev, members: [...prev.members, {id: -1, name: name}]}));
}
};
// ...
```
하지만, 한번 나갔던 멤버의 정보는 currentMember에 존재하지 않고, allMember에 존재하기 때문에 비교하는 대상을 …
=>  [FE] 지출 생성 시 나갔던 멤버를 다시 추가할 수 없는 오류

client/src/GlobalStyle.ts, client/src/components/Design/theme/GlobalStyle.ts
- close #615
일부 모바일 환경에서 pretendart font가 적용되지 않는 문제가 있었습니다.
의도한 디자인을 전달할 수 없는 문제가 있어 이를 해결하려고 했습니다.
기존에 `font-family : "Pretendart"`를 사용해 줬지만, web font를 import 하는 코드가 없었습니다.
client 에서 pretendard font를 가지고 있는 데스크탑 환경에서는 정상 작동했지만,
그렇지 않을 수 있는 모바일 환경에서는 대체 폰트를 사용하기 때문에 발생한 문제라고 판단했습니다.
따라서
```tsx
@import url('https://cdn.jsdelivr.net/gh/orioncactus/pretendard/dist/web/static/pretendard.css');
```
를 이용해 webfont 주소를 명시해 주었습니다.
=> [FE] 모바일 환경에서 Font가 제대로 적용되지 않는 문제

client/src/hooks/useMembersStep.ts, client/src/pages/AddBillFunnel/steps/MembersStep.tsx
- close #619 
행사 생성 단계에서 멤버를 입력할 때 전에 입력한 이름이 같이 나옵니다.
예를 들어, 쿠키를 입력하고 토다리를 입력하려고 하면 "키토다리"와 같이 입력됩니다.
유저 편의성을 위해 이를 해결하려고 합니다.
기존에는 keyboard event에서 `isComposing`인 경우, return을 해주기 때문에, composing인 경우 를 건너 뛰는 방식을 사용했습니다.
하지만 일부 환경에서 제대로 작동하지 않아서 이를 위해 inputRef 초기화를 해주기 위한 focus와 blur를 해주는 방식을 사용했습니다.
```tsx
// useMembersStep.tsx
// ...
const handleNameInputEnter = (event: React.KeyboardEvent<HTMLInputElement>) => {
if (event.nativeEvent.isComposing) {
return;
}
if (event.key === 'Enter' && canAddMembers) {
event.preventDefault();
if (!billInfo.members.map(({name}) => name).includes(nameInput)) {
setBillInfoMemberWithId(nameInput);
}
setNameInput('');
}
};
// ...
```
```tsx
// useMembersStep.tsx
// ...
const handleNameInputEnter = (event: React.KeyboardEvent<HTMLInputElement>) => {
if …
```
=>  [FE] 모바일 환경에서 멤버 추가 시 전에 입력한 이름의 끝자리가 입력되는 문제

client/src/hooks/useEditBillState.ts
- close #621 
지출에서 수정되지 않은 멤버가 1명일 때 이 한명이 내야 하는 금액은 총 금액에서 고정된 멤버들을 뺀 금액과 같을 수 밖에 없어서 별도의 수정이 가능하지 않도록 막아야 합니다.
현재 수정이 가능하고, 이를 요청보내면 app이 터져버리는 버그가 있습니다.
기존 구현 상황에서, 수정되지 않은 멤버가 1명을 판단하는 로직 자체가 없었습니다.
이를 판단하는 로직을 추가하고, 해당 상황이라면 금액이 변경되지 않게 수정했습니다.
```tsx
// useEditBillState.ts
// ...
const isLastUnfixedMember = (keyboardTargetId: number) =>
!newBillDetails.find(({id}) => id === keyboardTargetId)?.isFixed &&
newBillDetails.filter(({isFixed}) => isFixed === false).length === 1;
const handleChangeBillDetails = ({value, keyboardTargetId}: HandleChangeBillDetailsProps) => {
if (isLastUnfixedMember(keyboardTargetId)) return;
if (Number(value.replace(/,/g, '')) === newBillDetails.find(({id}) => id === keyboardTargetId)?.price) return;
setNewBillDetails(prev => {
const updatedDetails = …
```
=> [FE] 지출에 멤버가 1명일 때, 금액이 수정되는 오류

client/src/GlobalStyle.ts
- close #647 
코드 수정 중 잘못 입력된 tnum attribute로 인해 예상된 폰트 디자인이 출력되지 않습니다.
tnum attribute 를 제거했습니다.
=> [FE] GlobalStyle tnum 삭제

client/src/components/Design/components/ExpenseList/ExpenseList.tsx, client/src/components/ShareEventButton/ShareEventButton.tsx, client/src/hooks/useReportsPage.ts, client/src/utils/detectDevice.ts, client/src/utils/isMobileDevice.ts
- close #649 
userAgent에서  [/iPhone/i, /iPad/i, /iPod/i]가 포함되어 있다면 ios로 판별 [/Android/i, /BlackBerry/i, /Windows Phone/i]가 포함되어 있다면 안드로이드로 판별합니다.
```tsx
if (isAndroid()) {
const url = 'supertoss://';
window.location.href = url;
return;
}
if (isIOS()) {
const url = 'supertoss://send';
window.location.href = url;
return;
}
```
안드로이드는 기존 그대로
IOS는 토스의 송금하기 페이지로 보내버립니다.
=> [FE] IOS 환경에서도 토스 송금 기능을 똑같이 이용할 수 있도록 설정

client/cypress/e2e/createEvent.cy.ts, client/src/components/Design/components/NumberKeyboard/NumberKeyboardBottomSheet.tsx, client/src/components/Design/components/TopNav/TopNav.style.ts, client/src/components/Design/components/TopNav/TopNav.tsx, client/src/components/ShareEventButton/ShareEventButton.tsx, client/src/constants/message.ts, client/src/hooks/useEventMember.ts, client/src/pages/EventPage/AdminPage/EventMember.tsx, client/src/pages/EventPage/EventPageLayout.tsx, client/src/pages/MainPage/MainPage.tsx, client/src/pages/MainPage/Nav/Nav.tsx
- close #646
- put, delete 요청 순서 보장 누락된 것 살리기
- '수정완료' 토스트 누락된 것 살리기
- 랜딩페이지와 메인페이지의 header 디자인이 일치하지 않는 문제 수정
랜딩페이지에서는 Nav를 사용하고 메인페이지에서는 TopNav를 사용했어요.
둘이 각자 다른 컴포넌트를 사용하고 있었기 때문에 디자인이 일치하지 않았어요.
따라서 Nav 컴포넌트는 TopNav 컴포넌트를 적용하도록 수정했습니다.
그러는 과정에서 margin이 '뒤로가기'에서는 적용되지 않았어요.
그래서 그냥 TopNav에 margin 양옆 1rem을 적용해줬습니다.
그러면 TopNav를 사용하는 곳에서 Flex에 항상` margin="0 1rem 0 0"`을 적용해줬는데 그럴 필요가 사라졌어요.
대신 "정산 시작하기" , "카카오톡 정산 초대하기" 버튼은 TopNav에 들어가는 것이 아니기 때문에 margin 1rem이 적용되지 않았어요. 그래서 각 button 들에` marginRight: 1rem`을 적용해줬습니다.
- z-index 상수 미적용 코드 적용 및 불필요한 z-index 삭제
=> [FE] merge 진행하면서 put, delete 요청 순서 보장 사라짐 + 수정 완료 Toast 없어짐 추가

client/src/hooks/useMembersStep.ts
- close #650 
#619 
#631 
에서 구현한 문제가 해결되지 않았습니다.
멤버를 추가할 경우, 인풋에 focus가 해제되는 경우도 있고,
전에 입력한 부분이 함께 입력되는 오류도 있습니다.
enter를 입력해도, isComposing이 true인 경우가 모바일에서 존재했습니다.
각 입력 상태를 검증하는 순서를 변경하고,
blur 후 focus를 줌으로써 isComposing을 초기화하는 방향을 선택했습니다.
=> [FE] 멤버 추가 시 제대로 작동하지 않는 문제 수정

client/src/pages/EventPage/AdminPage/EventLoginPage.tsx
- close #654 
top component가 변경되면서 login 페이지 레이아웃이 변경되었습니다.
로그인 페이지 레이아웃이 의도치 않게 망가져 있어 사용자 개선을 위해 이를 변경합니다.
css를 적용해주고, 문구를 변경하였습니다.
=> [FE] login 페이지 레이아웃 오류

client/src/hooks/useMembersStep.ts
- close #669 
첫 번째 인자에 string을 사용하면 가장 먼저 찾은 문자만 바뀌게 됩니다.
1,000,000의 경우 1000,000이 되어 숫자로 인식할 수 없는 문제였습니다.
그래서 /,/g 정규식을 사용해서 해당 문자의 모든 콤마를 지우도록 수정했습니다.
=> [FE] 지출 내역 100만원 이상 등록이 되지 않는 버그

client/src/components/Design/components/ExpenseList/ExpenseList.tsx
- close #674 
BankSendButton에 isDeposited prop을 넣어줬습니다.
기존에는 price가 0보다 작거나 같은지만 넣어줬다면 isDeposited 값도 넣어줍니다.
```tsx
<BankSendButton
clipboardText={clipboardText}
onBankButtonClick={onBankButtonClick}
isDeposited={price <= 0 || isDeposited}
/>
```
=> [FE] 입금 완료를 했는데 송금 버튼이 눌리는 버그

client/src/constants/errorMessage.ts
- close #678 
잘못된 비밀번호를 입력하면 `PASSWORD_INVALID`라는 오류 코드를 받게되는데요.
이 `PASSWORD_INVALID`가 프론트엔드에서 관리하는 서버 오류 코드 상수에 존재하지 않았어요.
`알 수 없는 페이지` 는 프론트엔드의 서버 오류 코드 상수에 존재하지 않는 경우 도달하게 되는 페이지입니다.
그래서 `PASSWORD_INVALID`를 서버 오류 코드 상수에 추가해주었어요~!
```jsx
PASSWORD_INVALID: '비밀번호를 올바르게 입력해주세요.',
```
https://github.com/user-attachments/assets/3b948be6-8edf-48a8-a62a-adc01adc3521
=> [FE] 관리 입장시 잘못된 비밀번호 입력하면 '알수 없는 페이지'로 이동함

client/src/components/ShareEventButton/ShareEventButton.tsx
- close #681
데스크탑에서 '정산하기' 버튼 margin 미적용된 것을 적용했습니다.
=> [FE] 데스크탑에서 '정산하기' 버튼 margin 미적용

client/src/components/Loader/EventLoader.tsx, client/src/router.tsx
- close #683 
아래 영상을 보면 행사 이름 레이아웃이 먼저 보이고 행사 이름이 채워진 후 아래 step 들이 보이게 됩니다.
사용자에게 깜빡거리는 안 좋은 경험을 주게 됩니다.
https://github.com/user-attachments/assets/8e916e2c-a851-4ea0-9ec7-111dc1843dbb
이런 현상을 해결하기 위해선 컴포넌트를 랜더링 하기 전에 필요한 데이터를 전부 불러온 뒤에 컴포넌트를 랜더링하면 되지 않을까 해서 적용해봤습니다.
1. react-router loader 도입에 대한 고민
처음에는 react-router의 loader 기능을 활용해서 컴포넌트가 랜더링 되기 전 데이터를 load 한 뒤 랜더링을 하려고 했습니다.
우리는 서버 상태를 react-query로 관리하며 react-query와 loader를 같이 사용하기 위해선 router에서 query client가 필요해집니다. 하지만 router는 jsx element를 반환하는 컴포넌트가 아니기때문에 hook을 사용할 수 없습니다.
즉 useQueryClient를 사용해서 queryClient를 받아올 수 없기 때문에 지금 작성된 구조로는 loader를 도입하는데 어려움이 있다고 생각했어요
2. 컴포넌트를 감싸는 Loader
그렇다면 react-router의 loder와 비슷하게 구현해보면 되지 않을까 해서 컴포넌트를 감싸는 로더를 만들어봤어요
```tsx
<EventLoader>
<EventPageLayout />
</EventLoader>
```
위 구조와 같이 Loader를 만들어줍니다.
그리고 …
=> [FE] 이벤트 페이지 api 호출 개선

client/src/hooks/useAccount.ts
- close #690 
원래 변경된 필드만 payload로 보냈으나 변경 여부 관계없이 둘 다 보내는 것으로 변경했습니다.
https://github.com/user-attachments/assets/12c3a6fb-f125-4f6a-8ffc-2ae68302b116
=> [FE] 계좌번호 수정이 되지 않는 문제

client/src/components/QueryClientBoundary/QueryClientBoundary.tsx
- close #593 
react-query의 stale time, gc time을 설정했습니다.
stale time과 gc time을 동일하게 1분으로 설정했습니다.
이 근거를 설명하겠습니다.
1분으로 짧게 가져간 이유는 행동대장 서비스가 "정산"을 다루기 때문입니다.
정산 프로그램은 사용자에게 정확한 데이터를 보여주어야 합니다. 실수로 수정되기 전의 데이터가 보여진다면 큰 혼란을 겪을 수 있습니다.
예로 들자면 정산 링크를 공유한 뒤에 잘못 작성한 내용이 있어 급하게 수정했다면, 주최자가 보고 있는 화면과 참여자가 보고 있는 화면이 다를 수 있습니다. 이 때 1분이라는 아주 짧은 시간을 가진다면 1분 뒤 다시 데이터를 조회했을 때 수정된 값을 보여줄 수 있습니다. 즉 캐시 시간을 짧게 가져가서 사용자에게 올바른 데이터를 보여줄 확률을 높이려고 했습니다.
그렇다면 아에 캐싱을 하지 않으면 정확한 정보를 가져올 수 있지 않나 생각할 수 있지만, 근거가 있습니다.
1. 네트워크 상황이 좋지 않은 경우
네트워크 상황이 좋지 않은 상황에서(야구장에서 사용할 경우) 서버로 재요청을 날릴 때 이미 조회를 했으니 데이터를 다시 불러오지 않게 되어 빠르게 보여줄 수 있습니다
2.  불필요한 api 호출 줄임
탭을 왔다갔다 하는 경우 계속 요청을 하게 되는데 캐싱을 해놓으면 재요청을 하지 않으니 서버로의 불필요한 요청을 줄일 수 있어서 설정했습니다.
다른 의견이 있다면 적극 반영할게요!
=> [FE] staleTime, gcTime 기본 값 설정

server/src/main/java/server/haengdong/HaengdongApplication.java, server/src/main/java/server/haengdong/config/JpaConfig.java, server/src/main/java/server/haengdong/domain/BaseEntity.java, server/src/main/java/server/haengdong/domain/bill/Bill.java, server/src/main/java/server/haengdong/domain/bill/BillDetail.java, server/src/main/java/server/haengdong/domain/event/Event.java, server/src/main/java/server/haengdong/domain/event/EventImage.java, server/src/main/java/server/haengdong/domain/member/Member.java
- close #699 
createdAt 설정을 위해 BaseEntity를 추가했습니다.
=> [BE] createdAt 설정을 위한 BaseEntity 적용

client/src/hooks/queries/bill/useRequestDeleteBill.ts, client/src/hooks/queries/bill/useRequestPostBill.ts, client/src/hooks/queries/bill/useRequestPutBill.ts, client/src/hooks/queries/bill/useRequestPutBillDetails.ts, client/src/hooks/queries/event/useRequestPostEvent.ts, client/src/hooks/queries/member/useRequestDeleteMember.ts, client/src/hooks/queries/member/useRequestPostMembers.ts, client/src/hooks/queries/member/useRequestPutMembers.ts
- close #711 
저번 버전에서 gc,stale time을 추가하면서 새로운 행사를 생성해도 이전 행사의 데이터가 캐싱되는 현상이 발생했습니다. 물론 1분이 지나고 새로고침을 하면 사라지긴 합니다. 하지만, 즉각 행사를 생성하는 경우가 발생할 수 있기 때문에 수정을 진행했습니다.
**Problem 1**
새로운 지출내역을 생성해도 이전 지출내역의 참여자가 자동으로 추가되지 않는 문제가 발생했습니다.
- 해결
Bill과 Member 에서 patch, post, delete를 요청하는 query hook에 `queryClient.invalidateQueries({queryKey: [QUERY_KEYS.currentMembers]});`를 추가해줬습니다. 
성공적으로 요청이 진행되면 currentMembers를 refetching합니다.
**Problem 2**
만들었던 행사가 존재하고 곧 바로 새로운 행사를 생성하면 이전 행사의 데이터가 들어오는 문제가 발생했습니다.
- 해결
새로운 행사를 생성해도 이전의 데이터가 캐싱되어 발생한 문제였기에, 요청이 성공적으로 진행되면 event가 refetching 되도록 했습니다. 
```tsx
onSuccess: () => {
queryClient.invalidateQueries({queryKey: [QUERY_KEYS.event]});
},
```
위에 작성한 Problem2의 내용을 쿠키가 준 피드백 방향으로 수정했습니다~!
removeQueries()와 resetQueries() 중에 어떤 것이 더 적절할까? 테스트를 해봤어요.
removeQueries()는 …
=> [FE] react-query 캐싱 적용으로 인해 발생한 버그 해결

client/src/hooks/useToast/toast.ts, client/src/hooks/useToast/useToast.tsx
- close #689 
pr제목 그대로.. 띄울 토스트의 타입이 error, none이어도 모두 confirm으로 아이콘이 뜨는 문제가 있었습니다.
기존에는 toast는 message, options 두 값을 담아 UI 컴포넌트인 Toast 컴포넌트에 전달해주었는데요. 이 options값에 type(confirm인지 error인지 none인지..)이 없었기 때문에 기본 값인 confirm으로 계속 뜨고있었습니다.
따라서 제일 오른쪽에 보이는 것처럼 타입을 인자로 받도록 인터페이스를 열었습니다.
그리고 아래처럼 options를 원래의 options + type 값이 담기도록 스프레드연산자를 통해 담아 넘겨주었습니다.
```jsx
const showToast = (message: ToastMessage, options: ToastOptions, type?: ToastType) => {
return toastEventManager.trigger(TOAST_EVENT.show, message, {...options, type});
};
```
ToastContainer.tsx에서 아래와 같이 options를 스프레드해서 넘겨주기 때문에 정상적으로 Toast컴포넌트에 type prop이 전달되어 문제가 해결됩니다.
=> [FE] toast.error, toast.none이어도 모두 toast.confirm으로 출력되는 문제

client/src/apis/fetcher.ts, client/src/apis/request/images.ts, client/src/hooks/queries/images/useRequestPostImages.ts, client/src/hooks/useAddImagesPage.ts
- close #725 
기존에는 실행된 후 바깥에서 useEffect로 isSuccess를 감지해서 true이면 navigate를 하도록 되어있었습니다.
이를 async를 이용해서 아래 onSuccess가 된 것을 먼저 실행한 후에 navigate를 실행하는 방식으로 변경했습니다.
```ts
const {mutateAsync, ...rest} = useMutation({
mutationFn: ({formData}: RequestPostImages) => requestPostImages({eventId, formData}),
onSuccess: () => {
queryClient.removeQueries({queryKey: [QUERY_KEYS.images]});
},
});
```
```ts
await postImages({formData});
navigate(`/event/${eventId}/admin`);
```
=> [FE] 사진 추가한 후 다시 접속 시 반영이 되지 않는 버그

client/src/components/Design/components/Select/Select.tsx, client/src/components/Design/components/Select/useSelect.ts, client/src/hooks/useSendPage.ts
- close #734 
데스크탑 환경에선 선택지를 복사하기 밖에 보이지 않도록 설정했습니다.
모바일 환경에선 3가지가 다 보이게 했어요.
현재는 목록이 열려있을 때 select box를 클릭했을 때 목록이 열렸다가 닫히는 현상이 있었습니다.
이를 수정했어요
=> [FE] 송금에서 데스크탑 환경은 복사하기밖에 보이지 않도록 수정

client/src/hooks/useAddImagesPage.ts, client/src/pages/AddImagesPage/AddImagesPage.tsx, client/src/pages/EventPage/HomePage/HomePage.tsx
- close #736
- 이미지 추가 페이지에서 A사진 등록 -> A 사진 등록 해제 -> 다시 A 사진 등록 과정이 안되는 문제가 있습니다.
https://github.com/user-attachments/assets/fa45b1dc-d50f-477f-b8bb-3e7fc014a310
- 이미 추가했던 사진이 있고, 이후에 사진들을 등록한 뒤 이미 추가한 사진을 삭제할 때, 등록한 이미지들이 사라지는 문제가 있습니다.
https://github.com/user-attachments/assets/57a349ba-8321-4504-ba72-1769d61975dd
- 등록된 사진이 없을 때, 홈에서 사진 조회 페이지에 들어갈 수 있는 문제가 있습니다.
https://github.com/user-attachments/assets/25fa1872-02dc-4880-a001-6d7bc2fb51f7
1. **이미지 추가 페이지에서 A사진 등록 -> A 사진 등록 해제 -> 다시 A 사진 등록 과정이 안되는 문제**
두 사진이 같은 경우, file input의 `onChange`가 작동하지 않아서 `handleChangeImage`가 제대로 트리거되지 않는 문제입니다.
```tsx
if (fileInputRef.current) {
fileInputRef.current.value = '';
}
```
`handleDeleteImage`를 실행할 경우, inputRef의 value를 초기화 함으로써 handleChange가 항상 작동하도록 변경하였습니다.
- **이미 추가했던 사진이 있고, 이후에 사진들을 등록한 뒤 이미 …
=> [FE] 이미지 추가 및 조회 기능에서 발생하는 버그

client/index.html, client/src/pages/EventPage/EventPageLayout.tsx
- close #738
정산 시 og 태그들이 동일하게 나타나는데, 이곳에 행사에 대한 개요를 담으면 좋을 것 같다고 생각했습니다.
따라서 `eventLayoutPage`가 포함된 페이지에서는 행사 이름을 포함하는 og:title로 변경하여 썸네일을 보고도 행사의 이름을 알 수 있게 변경합니다.
```tsx
// EventPageLayout.tsx
// ...
updateMetaTag('og:title', `행동대장이 "${eventSummary.eventName}"에 대한 정산을 요청했어요`);
return () => {
updateMetaTag('og:title', '행동대장 - 쉽고 빠른 모임 정산 및 송금 서비스');
};
}, []);
// ...
```
`EventPageLayout`이 마운트 될 때, og:title 태그를 변경하도록 적용하였습니다.
아래 동영상에서, 우측의 meta tag가 변경되는 것을 확인할 수 있습니다.
https://github.com/user-attachments/assets/3b94474c-2a6f-4f6d-bd75-ccbe161227e7
=> [FE] eventName에 따라 og태그가 변경되도록 수정

client/src/components/Design/components/NumberKeyboard/Keypad.tsx, client/src/components/Design/components/NumberKeyboard/NumberKeyboard.tsx, client/src/components/Design/components/NumberKeyboard/keypads.ts
- close #748 
https://github.com/user-attachments/assets/ad6c0c18-5e4e-49ae-85ca-9ea6bd57014b
현재는 위 영상에서 00 버튼을 '공' 버튼이라고 읽습니다.
실제로 0이 두 개이고 이 버튼을 클릭하면 1원에서 100원이 되지만 0이라고 읽힌다면 스크린리더로 서비스를 이용하는 사용자에게 불편한 경험을 줄 수 있습니다.
그래서 넘버 키패드 00을 `'0' 2개 버튼`으로 읽도록 개선해야합니다.
추가로 지우기 버튼도 `다음보다 작음`이라고 읽고 있습니다. 이를 `금액 지우기, 버튼`으로 읽어야 스크린리더 사용자가 헷갈리지 않고 이용할 수 있습니다.
기존에는 amountKeypads 배열이 이렇게 선언되어 있었습니다.
```ts
const amountKeypads = ['1', '2', '3', '4', '5', '6', '7', '8', '9', '00', '0', '<-'];
```
여기에 스크린 리더가 읽어야 할 label 속성을 추가했습니다.
```ts
{
keypad: '1',
label: '1',
},
```
스크린 리더가 읽는 값과 화면에 표시되는 값을 다르게 설정하는 방식으로 구현했습니다.
그래서 00은 `0 2개 버튼`, <-는 `직전 입력 지우기`로 설정했어요.
https://github.com/user-attachments/assets/1c4e51ff-44f7-40ee-b887-b35e2e9c43fa
접근성 개선 결과를 확인하고 싶을 때 `npm run storybook`를 사용해 본인의 기기로 …
=> [FE] 접근성 : 넘버 키패드 스크린리더 개선

client/src/GlobalStyle.ts, client/src/components/Design/components/Select/SelectInput.tsx
- close #743 
SelectBox의 버그를 수정합니다. 유저가 사용할 때, 큰 불편함은 존재하지 않겠지만 사용성을 조금 더 올리기 위해서 개선을 진행합니다.
- 클릭 시 파란색 강조되는 현상을 해결해야합니다.
이는 SelectBox 뿐 만아니라 다양한 컴포넌트에서도 발생하고 있는 사항입니다. 따라서 전역 스타일에서 해당 문제를 해결했습니다.
```tsx
WebkitTapHighlightColor: 'transparent',
```
[[root 속성 (-webkit-tap-highlight-color: transparent;)](https://velog.io/@jongk91/root-%EC%86%8D%EC%84%B1)](https://velog.io/@jongk91/root-속성)
- SelectBox 디자인과 불일치한 요소 수정
SelectBox에서 SelectInput의 labelText에 Flex 컴포넌트가 사용되고 있었습니다. 그리고 그 컴포넌트에 gap에 0.375rem이 사용되고 있었습니다. 이미 labelText의 개별 style에 marginBottom을 주고 있었기 때문에 해당 gap은 중복으로 0.375rem을 주고 있었습니다. 
따라서 SelectInput의 Flex 컴포넌트에 적용한 gap을 제거했습니다.
=> [FE] SelectBox 수정 + globalStyle 파란색 하이라이팅 제거

client/src/constants/sessionStorageKeys.ts, client/src/hooks/useAdminPage.ts, client/src/hooks/useBanner.ts, client/src/pages/EventPage/AdminPage/AdminPage.tsx, client/src/pages/EventPage/EventPageLayout.tsx
- close #729 
현재 유저가 입금 상태를 관리할 수 있는 기능을 인지할 방법이 존재하지 않습니다.
그렇기 때문에 유저가 지출내역을 생성했다면, 입금 상태를 관리하는 기능을 인지할 수 있도록 Banner를 활용하여 알려줍니다.
참여자 입금 상태 Banner를 띄우는 조건은 다음과 같습니다.
- 계좌번호를 등록 할 것
- 최소 1개의 지출내역이 존재할 것
- sessionStorage에 `*closeDepositStateBanner-*${*eventToken*}` key가 존재하지 않고 그 값이 false일 경우
참여자 입금 상태 Banner가 닫히는 조건은 단 하나입니다.
- Banner의 X 버튼을 클릭했을 때
닫히는 조건을 더 추가할까 고민했습니다만, 일단은 x 버튼을 클릭해야만 닫히도록 했습니다. 현 상황에서는 Banner는 최대 1개만 띄워지기 때문입니다.
Banner는 총 2개가 존재하지만 해당 입금상태 Banner는 계좌번호가 존재해야 띄워집니다. 계좌번호 Banne는 계좌번호가 입력되면 사라지기 때문에 2개의 Banner가 동시에 띄워질 일은 발생하지 않습니다. 따라서 입금 상태 Banner에 따로 닫히는 조건을 추가하지는 않았습니다. (만약, 사진 첨부 Banner를 띄우게 된다면 추가로 고려하면 될 것 같습니다.)
쿠키가 Banner를 너무 잘 만들어줘서.. 쿠키가 작성한 코드를 바탕으로 구현했습니다.
```tsx
// constants/sessionStorageKeys.ts
const SESSION_STORAGE_KEYS = {
// ... …
```
=> [FE] 첫 지출내역 추가 시, 입금 상태 관리 Banner 띄우기

client/src/components/Design/components/Top/Line.tsx, client/src/components/Design/components/Top/Top.tsx
- close #757 
핵심 flow인 지출내역 생성에서 스크린리더를 사용하는 유저는 header를 제외하고는 가장 먼저 Top을 듣게 될 것입니다. Top 컴포넌트는 해당 페이지에 대한 설명을 담은 컴포넌트로, 스크린리더 사용자는 해당 페이지에서 어떤 것을 입력해야 하는지 듣게 됩니다.
그런데, 기존의 Top 컴포넌트의 text는 끊어서 읽혔습니다. 이런 점은 스크린리더 사용자에게 혼동과 불편함을 주게 될 것입니다. 따라서, Top 컴포넌트를 스크린리더가 읽혔을 때 내용이 한번에 읽히도록 수정합니다.
🔇 영상 속 스크린리더기는 음성을 사용하지 않습니다! 
💬 영상 하단에 스크린리더 자막으로 확인해주세요!
- 개선 전
- 
https://github.com/user-attachments/assets/91ee2e08-7fae-4bac-9ef1-1a0d20e4d7de
- 개선 후
https://github.com/user-attachments/assets/432d4034-c5bb-4682-b5ba-24a2e8b303ad
```tsx
const [childrenTexts, setChildrenTexts] = useState<string[]>([]);
const collectedTexts: string[] = [];
React.Children.forEach(children, child => {
if (React.isValidElement(child) && child.type === Top.Line) {
collectedTexts.push(child.props.text);
}
}); …
```
=> [FE] 접근성 개선 : 지출내역 추가 Flow의 Top

client/.storybook/preview.tsx, client/index.html, client/src/GlobalStyle.ts, client/src/components/Design/theme/GlobalStyle.ts
- close #768 
lighthouse를 실행한 결과 다음과 같은 진단이 나왔습니다.
이런 진단의 이유는 우리 서비스에서 사용하는 Pretendard 폰트가 preconnect 되지 않아서 발생한 것이었습니다. 따라서 Pretendard 폰트를 preconnect하여 320ms를 절감합니다.
개선 전의 네트워크 요청을 확인해보면 Pretendard.css는 뒤늦게 다운로드 되는 것을 확인할 수 있습니다.
개선 후의 네트워크 요청을 확인해보면 Pretendard.css는 조기에 다운로드되는 것을 확인할 수 있습니다. 추가로 lighthouse 진단에서 발생하던 `필수 원본 미리 연결하기`가 사라진 것을 확인할 수 있습니다.
이전에는 GlobalStyle.ts에서 import를 통해 font link를 불러오고 있었습니다. 또한, font import는 예전 디자인 시스템 GlobalStyle.ts과 src 하위 GlobalStyle.ts, 총 2번 호출하고 있었습니다. 현재는 디자인시스템을 따로 배포하여 사용하지 않기 때문에 두 GlobalStyle.ts에서 font import를 제거했습니다.
font를 preconnect와 dns-prefetch를 하기 위해 index.html에서 직접 font link를 import 했습니다. 기존 코드들과의 통일서을 위해서 React 컴포넌트 단에서 useEffect를 활용하여 font를 import하는 방법도 존재했습니다. 아니면 React 컴포넌트에서 head 태그에 접근하기 위해서 라이브러리를 활용하는 방법도 있었습니다. 다만 font를 preconnect …
=> [FE] 성능 개선 : Preconnect to requered origins

.github/workflows/backend-prod.yml, server/build.gradle, server/src/main/resources/application.yml
=> [BE] v2.1.2 배포

client/src/components/Design/components/Carousel/Carousel.style.ts
- close #765
- 768px 이상의 해상도에서 carousel이 잘리는 문제가 발생했습니다.
- `Carousel` component에서 이미지 카드의 `max-width`를 적용해 줌으로써 해결하였습니다.
=> [FE] carousel 에 maxWidth가 적용되지 않아 768 이상 해상도에서 짤리는 문제

client/src/hooks/useMainPageYScroll.ts, client/src/hooks/useMainSectionBackgroundScroll.ts, client/src/pages/MainPage/MainPage.style.ts, client/src/pages/MainPage/Section/CreatorSection/Avatar.tsx, client/src/pages/MainPage/Section/CreatorSection/CreatorSection.style.ts, client/src/pages/MainPage/Section/FeatureSection/FeatureSection.tsx
- close #796 
- 현재 모바일 환경이나 일부 데스크탑 환경에서 가로 스크롤이 제대로 되지 않는 오류가 있어 이를 해결합니다.
현재 가로 스크롤이 작동하는 과정은 아래와 같습니다.
1. 스크롤이 featureSection에 도달한다.
2. featureSection 영역부터, 종방향 스크롤을 하면 이를 featureSection 위치로 다시 종방향 스크롤시킨다
3. 종방향 스크롤을 한 만큼, featureSection을 translateX 시킨다.
4. translateX가 최대치에 도달하면, 다시 종방향 스크롤을 가능하게 한다.
이 과정에서, 종방향 스크롤을 강제로 못하게 원 위치로 되돌리는 방식이다 보니, 스크롤이 계속 유지되는 모바일 환경의 touch 이벤트에서는 제대로 작동하지 않는 것이 문제가 되었습니다.
또한, 스크롤 자체를 다시 원위치로 되돌이는 것이다 보니, 중간 중간 스크롤이 꿀렁거리는 오류가 있었습니다.
이를 해결하기 위해 작동 방식을 아래와 같이 변경하였습니다.
1. 스크롤이 featureSection에 도달한다.
2. featureSection의 position을 fixed로 변경한다.
3. featureSection이 fixed인 상태로 스크롤 되는 만큼 페이지에 여백을 만들어 둔다.
4. 여백 내부에서 종방향 스크롤을 한 만큼, featureSection을 translateX 시킨다.
5. 여백이 끝에 도달할 때, opacity를 이용해 featureSection을 없애준다.
따라서, 스크롤은 실제로 이루어지고, default Event를 강제로 조작하지 않으므로 많은 …
=> [FE] 랜딩페이지 스크롤 오류 해결

client/src/components/Design/components/NumberKeyboard/NumberKeyboardBottomSheet.tsx, client/src/components/Design/components/NumberKeyboard/useNumberKeyboardBottomSheet.ts, client/src/hooks/useEditBillKeyboardAction.ts, client/src/hooks/useEditBillPage.ts, client/src/hooks/useEditBillPageScroll.ts, client/src/pages/EditBillPage/EditBillPage.tsx
- close #744 
- 기존에 모바일 환경에서, 상세 지출 내역 아이템 선택 시, 특정 높이에서 가상 키보드가 선택 영역을 가리는 문제가 존재했습니다.
- 사용자 경험 향상을 위해서 이 문제를 해결합니다.
https://github.com/user-attachments/assets/7763a90b-c5eb-4154-a4e8-c04b4699c2fb
- 기존에는 키보드의 height만을 고려해서 코드를 작성하였기 때문에, 브라우저 특성으로 인한 `window.innerHeight`를 별도로 고려하지 않아 브라우저 환경 별 위와 같은 문제가 발생했습니다.
- 이를 해결하기 위해 keyboardHeight만을 고려하는 것이 아닌, 브라우저 환경에 따라 변경되는 `offsetTop`을 이용하여 기준점을 설정하도록 변경하였습니다.
=> [FE] 상세 지출 수정에서 가상 키보드가 선택 영역을 가리는 문제 해결

client/index.html
- close #798 
폰트가 프리로드되지 않아 render-blocking 요소로 측정되고 있었습니다.
그래서 프리로드하도록 개선했습니다.
=> [FE] 폰트를 프리로드 하도록 수정

client/src/components/AppErrorBoundary/ErrorCatcher.test.tsx, client/src/pages/ErrorPage/ErrorPage.tsx
- close #807 
현재 UnpredictableErrorBoundary에서 에러가 잡혔을 경우 '에러가 발생했습니다.'라는 텍스트만 뜹니다.
그래서 에러 페이지를 꾸며보았습니다.
에러 페이지를 구현합니다.
=> [FE] 에러 페이지 구현

server/src/main/java/server/haengdong/application/ImageService.java, server/src/main/java/server/haengdong/config/S3Config.java, server/src/main/java/server/haengdong/exception/HaengdongException.java
- close #813
여러 이미지를 순차적으로 업로드하던 기능을 병렬로 업로드할 수 있게 변경합니다.
[10MB 이미지 10개]
순차 업로드 : 5.5s
병렬 업로드 : 2.1s
로 응답시간을 개선했습니다.
추가로 S3Client 호출 시에 발생하는 예외를 추적할 수 있도록 HaengdongException 생성자에 Throwable 을 추가했습니다.
=> [BE] 이미지 병렬 업로드 기능 추가

server/src/main/java/server/haengdong/application/EventImageFacadeService.java, server/src/main/java/server/haengdong/application/EventService.java, server/src/main/java/server/haengdong/application/ImageService.java, server/src/main/java/server/haengdong/domain/event/EventImageRepository.java, server/src/main/java/server/haengdong/exception/HaengdongErrorCode.java, server/src/main/java/server/haengdong/presentation/admin/AdminEventController.java, server/src/test/java/server/haengdong/application/EventServiceTest.java, server/src/test/java/server/haengdong/application/ImageServiceTest.java, server/src/test/java/server/haengdong/docs/AdminEventControllerDocsTest.java, server/src/test/java/server/haengdong/presentation/ControllerTestSupport.java
- close #814
이벤트 1개에 업로드할 수 있는 이미지 수량을 10개로 제한합니다.
flow : validateImageCount -> uploadImages-> saveImages
비지니스 플로우가 Controller에 노출되어 파사드 패턴을 도입했습니다.
현재 flow가 validateImageCount -> uploadImages-> saveImages 인데
eventService에서 validateImageCount와 saveImages로 별도의 메소드로 분리되어 
외부에서 인지했을 때 saveImages전에 validate가 필요한지 인지하기 어려울 것 같습니다.
그래서 다른 방법으로 
1. validateAndsaveImages -> uploadImages를 실시하고 업로드 실패시 데이터베이스만 deleteImages를 하는 방법
2. uploadImages -> validateAndsaveImages를 실시하고 업로드 실패시 deleteImages API를 날리는 방법
이 있는데 어떻게 생각하시나요?
=> [BE] 이벤트당 이미지 업로드 수량 제한

client/src/hooks/queries/report/useRequestGetReports.ts, client/src/hooks/useEventMember.ts
- close #823
기존에는 전체 참여자 관리 페이지에서 참여자의 정렬이 이뤄지지 않고 있습니다. 이런 방식은 참여자가 많아질 경우, 관리자가 참여자를 찾는 것에 불편함을 줍니다. 참여자의 상태를 관리하기 위해 관리자가 참여자의 이름을 찾는 과정에서 참여자 이름에 규칙이 존재하지 않기 때문에 어느 위치에 존재하는지 찾기가 어려워지기 때문입니다.
따라서, 참여자의 이름을 사용자 브라우저의 언어 설정에 맞게 (ㄱ-ㅎ,a-z / 한글 언어 설정 기준) 순으로 정렬하는 기능을 추가했습니다.
sort 메서드를 활용하여 initialReports를 이름을 기준으로 정렬했습니다.
useEventMember hook은 기존에 서버로부터 reports 데이터 값을 받아오면 useEffect를 사용하여 initalReports의 값이 변화가 생기면 reports 클라이언트 값을 바꾸도록 했습니다. 이 과정에서 reports에 값을 set을 통해 변경하기 전, initalReports를 이름을 기준으로 정렬하는 과정을 추가했습니다.
```tsx
const sortedMemberNameReports = initialReports.sort((a, b) => a.memberName.localeCompare(b.memberName));
setReports(sortedMemberNameReports);
}, [initialReports]);
```
sort 메소드를 활용하여 정렬했습니다. 이때, 두개의 요소 a와 b를 비교하는 콜백함수를 받습니다.
- `(a, b) => …
=> [FE] 전체 참여자 관리 : 참여자 이름 정렬 

client/src/apis/request/auth.ts, client/src/components/AppErrorBoundary/ErrorCatcher.tsx, client/src/components/Design/components/TopNav/NavItem.tsx, client/src/constants/routerUrls.ts, client/src/constants/sessionStorageKeys.ts, client/src/hooks/createEvent/useCreateGuestEventData.tsx, client/src/hooks/queries/auth/useRequestPostAuthentication.ts, client/src/hooks/queries/auth/useRequestPostLogin.ts, client/src/hooks/queries/event/useRequestGetEvent.ts, client/src/hooks/useAmplitude.ts, client/src/hooks/useEventPageLayout.ts, client/src/hooks/useLoginPage.ts, client/src/hooks/useReportsPage.ts, client/src/mocks/handlers/authHandlers.ts, client/src/mocks/sharedState.ts, client/src/pages/AccountPage/Account.tsx, client/src/pages/CreateEventPage/CreateGuestEventPage/CreateGuestEventFunnel.tsx, client/src/pages/EventPage/AuthGate/index.tsx, client/src/pages/EventPage/EventPageFallback/Login/GusetEventLogin.tsx, client/src/pages/EventPage/EventPageFallback/Login/MemberEventLogin.tsx, client/src/pages/LoginPage/LoginFailFallback.tsx, client/src/pages/LoginPage/LoginRedirectPage.tsx, client/src/pages/LoginPage/index.tsx, client/src/router.tsx, client/src/types/serviceType.ts, client/src/utils/SessionStorage.ts, client/src/utils/getDeletedLastPath.ts, client/src/utils/getEventBaseUrl.ts
- close #836 
**[블로그](https://jinokim.tistory.com/47)에서도 아래 내용을 확인할 수 있습니다.**
먼저 유저가 관리 페이지에 진입하게 되면 PostAuthenticate 함수 호출을 하게 됩니다. 이는 백엔드로 "내가 이 행사의 접근 권한이 있나요?"를 물어보는 기능으로 백엔드에서 쿠키를 확인한 후 결과를 알려주게 됩니다. 쿠키가 있다면 행사의 주최자가 맞으므로 관리 페이지에 정상 진입하게 되고, 쿠키가 없거나 변조된 값이면 주최자가 아니기 때문에 관리 페이지 대신 비회원 로그인 페이지로 가도록 하며, 비밀번호 4자리를 입력하고 로그인을 해야 주최자로 승인 받게 됩니다.
행사마다 회원 소유가 없으며 비밀번호를 정상적으로 입력하는 유저는 모두 주최자로 인정받을 수 있기 때문에 단순한 플로우를 구축할 수 있었고 프론트엔드에서 인증 절차를 복잡하게 가져가지 않았습니다.
하지만 이제 회원가입이 생겨 행사의 소유자가 생기고 로그인 한 유저는 비밀번호 4자리를 입력하지 않으므로 위 전략대로 가져갈 수가 없습니다. 행사 주최자가 비밀번호 없이 행사를 만들었는데 관리 페이지 접근 시 비밀번호 입력 화면을 보여주면 안 되기 때문입니다. 그리고 로그인으로 카카오 OAuth를 사용하게 되어 서비스를 이탈했다가 돌아와야하는 요구사항도 생겼습니다. 그래서 관리 페이지에서 카카오 로그인으로 이동한 뒤 관리 페이지로 다시 돌아갈 수 있는 기능도 추가 되어야 합니다. 요구사항을 짧게 정리해보면
1. 행사 소유자에 따른 로그인 기능 분리 (비밀번호 / 카카오)
2. 인증 실패 후 로그인을 성공했을 …
=> [FE] 로그인 구축으로 인한 인증 전략 변경

client/src/constants/routerUrls.ts, client/src/pages/MyPage/Container.tsx, client/src/pages/MyPage/MyPage.style.ts, client/src/pages/MyPage/index.tsx, client/src/router.tsx
- close #838 
로그인 후 사용자가 혜택을 누릴 수 있는 화면, 마이페이지 화면 퍼블리싱 작업만 수행했습니다.
이 페이지에서 로그아웃, 닉네임 설정, 계좌번호 설정, 내가 만든 행사 목록, 탈퇴 기능을 수행할 수 있습니다.
피그마에 있는 레이아웃 대로 작업했으며 기능은 추후에 추가할 예정입니다.
=> [FE] 마이페이지 화면 퍼블리싱

client/src/apis/request/event.ts
- close #841 
백엔드에서 endpoint가 변화해서 이를 반영했습니다.
반영 후 제 브랜치에서 정상 작동 확인했어요 :)
=> [FE] 회원 행사 생성 endpoint가 맞지 않아 에러 발생됐던 원인 해결

server/src/main/java/haengdong/event/application/EventService.java, server/src/main/java/haengdong/event/application/request/EventMineAppResponse.java, server/src/main/java/haengdong/event/domain/bill/MemberBillReport.java, server/src/main/java/haengdong/event/domain/event/EventRepository.java, server/src/main/java/haengdong/event/domain/event/member/EventMemberRepository.java, server/src/main/java/haengdong/event/presentation/EventController.java, server/src/main/java/haengdong/event/presentation/response/EventMineResponse.java, server/src/main/java/haengdong/event/presentation/response/EventsMineResponse.java, server/src/test/java/haengdong/domain/eventmember/EventMemberBillReportTest.java
- close #845 
내 행사 조회 기능 추가
GET /api/events/mine
```json
{
"events": [
{
"eventId": "238ab144-11a0-4028-bc3b-f49b512ec66f",
"eventName": "행동대앚",
"isFinished": false,
"createdAt": "2024-12-08T14:52:28.613223"
},
{
"eventId": "238ab144-11a0-4028-bc3b-f49b512ec66f",
"eventName": "행동대앚",
"isFinished": false,
"createdAt": "2024-12-08T14:52:28.613223"
},
{
"eventId": "238ab144-11a0-4028-bc3b-f49b512ec66f",
"eventName": "행동대앚",
"isFinished": false,
"createdAt": "2024-12-08T14:52:28.613223"
}
]
}
```
=> [BE] 내 행사 조회 기능 추가

client/src/apis/request/event.ts, client/src/hooks/queries/event/useRequestPatchEventName.ts, client/src/hooks/queries/event/useRequestPatchUser.ts, client/src/hooks/useAccount.ts, client/src/types/serviceType.ts
- close #843 
회원가입이 들어가며 계좌번호 관리 책임을 이벤트가 아니라 유저의 책임으로 백엔드 구조가 변경되며 api 명세가 변동되었습니다. 그래서 이에 맞춰 User 타입을 만들었습니다. 유저는 닉네임, 계좌번호, 은행 3가지를 가집니다.
또한 은행과 계좌번호를 합친 BankAccount 타입을 만들어 이를 &연산을 통해 Event와 User에 적용시켰습니다.
```tsx
export type BankAccount = {
bankName: string;
accountNumber: string;
};
export type Event = BankAccount & {
eventName: EventName;
createdByGuest: boolean;
};
export type User = BankAccount & {
nickname: Nickname;
};
```
useRequestPatchEventName는 이제 이름만 변경할 수 있고 useRequestPatchUser에서 계좌번호와 은행을 바꿀 수 있습니다.
닉네임 수정은 차후에 적용하겠습니다.
=> [FE] 계좌번호 수정이 되지 않는 문제 해결

server/src/main/java/haengdong/event/application/EventService.java, server/src/main/java/haengdong/event/application/response/UserAppResponse.java, server/src/main/java/haengdong/event/domain/event/member/EventMember.java, server/src/main/java/haengdong/user/application/KakaoUserService.java, server/src/main/java/haengdong/user/application/UserService.java, server/src/main/java/haengdong/user/application/request/UserJoinAppRequest.java, server/src/main/java/haengdong/user/domain/User.java, server/src/main/java/haengdong/user/presentation/UserController.java, server/src/main/java/haengdong/user/presentation/response/UserResponse.java
- close #851
회원 정보 조회 기능 구현했습니다.
/api/users/mine
```java
{
"nickname" : "닉네임1",
"bankName" : "국민",
"accountNumber" : "12345-1245",
"isGuest" : true,
"profileImage" : null
}
```
=> [BE] 회원 정보 조회 기능 구현

client/src/apis/request/user.ts, client/src/components/Design/components/Image/Image.tsx, client/src/components/Design/components/Profile/Profile.stories.tsx, client/src/components/Design/components/Profile/Profile.style.ts, client/src/components/Design/components/Profile/Profile.tsx, client/src/components/Design/components/Profile/Profile.type.ts, client/src/components/Loader/EventLoader.tsx, client/src/components/ShareEventButton/DesktopShareEventButton.tsx, client/src/components/ShareEventButton/MobileShareEventButton.tsx, client/src/constants/queryKeys.ts, client/src/hooks/queries/user/useRequestGetUserInfo.ts, client/src/hooks/useEventPageLayout.ts, client/src/pages/EventPage/EventPageFallback/EventPageLoading.tsx, client/src/pages/EventPage/EventPageLayout.tsx, client/src/router.tsx, client/src/types/serviceType.ts
- close #849 
Image 컴포넌트를 그대로 이용해서 구현해도 됐었지만, 프로필 이미지라는 것은 서비스의 성격을 띈다고 생각했습니다. 그래서 프로필의 스타일을 가진 (둥글고 사진이 들어가는) 디자인 컴포넌트를 제작하여 이용하도록 구성했습니다.
구현은 이미지 컴포넌트에 aria-label로 프로필 이미지를 의미하도록 설정해줬으며, 스타일을 적용해줬습니다.
size의 기본값은 28px으로 외부에서 이를 변경할 수 있도록 확장했습니다. 나머지 props는 ImageProps와 동일합니다.
```tsx
export const Profile = ({size = 28, ...profileProps}: ProfileProps) => {
const {theme} = useTheme();
return <Image aria-label="프로필 이미지" {...profileProps} css={profileContainerStyle(theme, size)} />;
};
```
이벤트 페이지에서 카카오 로그인 유저일 때 프로필이 보이도록 설정했으며, 이를 클릭할 때 제가 저번 pr에 퍼블리싱한 마이페이지가 보이도록 했습니다
비회원/회원 여부, 닉네임, 카카오 이미지 정보를 조회할 수 있는 api(/api/users/mine)가 추가되었습니다. 
Get 메서드이며 User 타입(nickname, bankName, accountNumber)에 isGuest, profileImage가 추가된 응답을 받습니다.
profileImage 정보를 이용하여 프로필 이미지를 보여주며, 만일 이 값이 null일 경우 행댕이 이미지가 …
=> [FE] 이벤트 페이지 프로필 표시(로그인 유지) 및 이벤트 페이지 로딩 화면 설정

client/src/apis/request/event.ts, client/src/components/Design/components/ChipGroup/ChipGroup.tsx, client/src/components/Design/components/CreatedEvent/CreatedEvent.style.ts, client/src/components/Design/components/CreatedEvent/CreatedEvent.tsx, client/src/components/Design/components/CreatedEvent/CreatedEvent.type.ts, client/src/constants/queryKeys.ts, client/src/constants/routerUrls.ts, client/src/hooks/queries/bill/useRequestGetBillDetails.ts, client/src/hooks/queries/event/useRequestGetCreatedEvents.ts, client/src/hooks/queries/event/useRequestGetEvent.ts, client/src/hooks/queries/member/useRequestGetAllMembers.ts, client/src/hooks/queries/member/useRequestGetCurrentMembers.ts, client/src/hooks/queries/report/useRequestGetReports.ts, client/src/hooks/queries/step/useRequestGetSteps.ts, client/src/pages/CreatedEventsPage/CreatedEventsPage.tsx, client/src/pages/MyPage/index.tsx, client/src/router.tsx, client/src/types/serviceType.ts
- close #854 
- 로그인 기능이 생긴 이후, 유저들이 지금까지 본인이 생성한 행사를 모아볼 수 있게 되었습니다.
- 사용자가 지금까지 정산을 진행한 페이지를 한눈에 모아볼 수 있도록 해당 페이지를 구현하여 제공합니다.
- route는 기존 @jinhokim98 이 구현한 `mypage`를 이용하여, `mypage/events` 로 정했습니다.
- 기존의 `EventHomePage`과 비슷한 UI, 기능들로 인하여 이를 참고하여 구현하였습니다.
- 피그마의 UX writing을 일부 수정하였습니다
- 기존 API는 오래된 것을 먼저 보여주지만, `useRequestGetCreatedEvents` hook 내부에서 data를 최신순으로 sort 하여 반환합니다.
- queryKey에 eventId 추가
- 기존 방식대로면, eventId가 변경되면서 다른 페이지에 접근해도, 기존의 요청 캐시로 인해 정보가 갱신되지 않았습니다. 이에 get 요청들의 query key에 eventId를 추가해 줌으로써, 페이지가 변경될 때 마다 새로 요청을 보내도록 변경했습니다.
- 개선 전
https://github.com/user-attachments/assets/aa8a5e9b-a9a5-430b-9a3f-09d9ed68ae27
- 개선 후
https://github.com/user-attachments/assets/3d35d099-8cc6-4125-986b-20e76d7b921b
기존의 ExpenseList와 비슷한 UI라고 생각하여 이를 재사용하려 하였으나, 이 조차도`Event`엔티티에 깊게 결합되어있어 …
=> [FE] 생성한 행사 모아보기 페이지

client/src/App.tsx, client/src/apis/endpointPrefix.ts, client/src/apis/request/auth.ts, client/src/apis/request/event.ts, client/src/components/QueryClientBoundary/QueryClientBoundary.tsx, client/src/constants/queryKeys.ts, client/src/errors/RequestGetError.ts, client/src/hooks/queries/auth/useRequestGetUserInfo.ts, client/src/mocks/handlers/authHandlers.ts, client/src/pages/MainPage/MainPage.tsx, client/src/pages/MainPage/Nav/Nav.tsx, client/src/pages/MainPage/Section/MainSection/MainSection.tsx, client/src/router.tsx, client/src/types/serviceType.ts
1. isGuest가 반대로 되어 로그인 상황일 때 로그인 페이지가 뜨고, 로그인 상황이 아닐 때 로그인 페이지가 안뜨는 문제를 해결했습니다.
2. MainPage에서 호출하는 회원 정보 확인 api에서 오류 토스트가 뜨는 문제를 해결했습니다.
3. initialData와 initialDataUpdatedAt 을 사용해 회원 정보 확인 api에서 오류가 떴을 때도 정상적으로 플로우가 수행되도록 했습니다.
```jsx
// 이전
navigate(isGuest ? ROUTER_URLS.createMemberEvent : ROUTER_URLS.login);
// 이후
navigate(isGuest ? ROUTER_URLS.login : ROUTER_URLS.createMemberEvent);
```
이 pr이 반영된다면 로그인 상태가 아닌 채로 MainPage에 진입하면 `로그인 정보를 확인하는 api`에서 401 쿠키없음 에러를 받습니다. 그리고 이 에러가 에러 핸들러에서 처리가 되기 때문에 "로그인해야 이용할 수 있습니다"라고 토스트가 뜨는 문제가 있었습니다. 
`로그인 정보를 확인하는 api`에서는 쿠키가 없을 때 쿠키 없음 에러를 뱉지 않고 200에 리스폰스 바디에 에러코드로 분기해달라고 요청할 수도 있었으나, 백엔드 설계를 많이 바꿔야할 것 같아 다른 방법을 생각했습니다. 
해당 api에서 에러가 발생하는 경우는 쿠키가 없을 때 즉 비회원인 경우입니다. 에러의 발생 여부로 회원, 비회원을 판단하는 것입니다. 따라서 디폴트로 수행되는 에러 핸들러의 동작을 이 api에서는 막아줘야 합니다. 
그래서 커스텀 …
=> [FE] 로그인 상태라면 행사 생성시 로그인 페이지를 띄우지 않음

client/src/apis/endpointPrefix.ts, client/src/apis/request/event.ts, client/src/apis/request/user.ts, client/src/assets/image/check.svg, client/src/components/Design/components/Checkbox/Checkbox.stories.tsx, client/src/components/Design/components/Checkbox/Checkbox.style.ts, client/src/components/Design/components/Checkbox/Checkbox.tsx, client/src/components/Design/components/Icon/Icon.style.ts, client/src/components/Design/components/Textarea/Textarea.stories.tsx, client/src/components/Design/components/Textarea/Textarea.style.ts, client/src/components/Design/components/Textarea/Textarea.tsx, client/src/components/Design/components/Textarea/Textarea.type.ts, client/src/components/Design/index.tsx, client/src/components/Logo/StandingDogLogo.tsx, client/src/constants/routerUrls.ts, client/src/hooks/queries/user/useRequestDeleteUser.ts, client/src/hooks/useWithdrawFunnel.ts, client/src/pages/MyPage/WithdrawPage/WithdrawPage.tsx, client/src/pages/MyPage/WithdrawPage/steps/CheckBeforeWithdrawingStep.tsx, client/src/pages/MyPage/WithdrawPage/steps/EtcStep.tsx, client/src/pages/MyPage/WithdrawPage/steps/NotUseServiceStep.tsx, client/src/pages/MyPage/WithdrawPage/steps/ReasonStep.style.ts, client/src/pages/MyPage/WithdrawPage/steps/ReasonStep.tsx, client/src/pages/MyPage/WithdrawPage/steps/UnableToUseDueToError.tsx, client/src/pages/MyPage/WithdrawPage/steps/WithdrawalCompleted.tsx, client/src/pages/MyPage/index.tsx, client/src/router.tsx
- close #848 
행동대장 서비스에 소셜 로그인을 도입하게 되었다. 그러면서 다양한 기능들이 새롭게 추가되어야 했는데, 그 중에 하나가 바로 회원탈퇴 기능이다.
회원 가입을 했기 때문에 당연히 회원 탈퇴를 할 수 있는 기능은 필수이다. 물론 자주 발생하지 않을 이벤트로 추측되지만, 그렇다고 개발자가 편하기 위해서 구글 스프레드 시트나 문의 사항으로 대체 할 수는 없다. 그렇게 된다면 사용자는 불편해지게 되면서 행동대장 서비스의 사용성이 안 좋아지게 될 것이다. 이는 우리 서비스에 대한 안 좋은 인식으로 퍼질 수 있다. 따라서, 회원탈퇴 기능도 사용자가 편할 수 있도록 구현하고자 신경썼다.
내가 개발하면서 가장 신경쓰는 부분은 UI/UX를 이쁘고 편하게 만드는 것이다. 그렇기에 디자인을 할 때, 토스를 참고하여 행동대장 서비스에 맞게 디자인을 신경썼다.
회원 탈퇴 기능에서 UI/UX 뿐 아니라 회원을 탈퇴하는 이유를 명확하게 수집하고자 했다. 단, 앞서 언급한 UX가 편하면서 탈퇴 이유 데이터를 수집할 수 있도록 해야 했다. 그러려면 사용자가 탈퇴하는 이유를 우리에게 말해줄 때 귀찮지 않게 해야 한다고 생각했다. 그래서 나는 탈퇴 이유를 큰 카테고리로 한 번 나누고, 그 카테고리 안에서 상세 내용을 선택할 수 있도록 다양한 선지를 사용자에게 주었다. 
- Icon 컴포넌트에서 svg 아이콘의 색상을 변경할 수 없는 에러가 존재하여 수정하였습니다.
- check icon이 기존에 존재했지만 다른 곳에서 사용하고 있지 않았고, 현재 사용해야 하는 check와 색상 및 사이즈가 달랐기 때문에 해당 …
=> [FE] 회원탈퇴 페이지 퍼블리싱 및 api 연결

client/src/constants/errorMessage.ts, client/src/hooks/createEvent/useSetNicknameStep.ts, client/src/utils/validate/validateMemberName.ts
- close #859 
1. 관리자 이름 유효성을 검증하는 유틸 함수인 validateMemberName이 이름에 맞는 일을 하고있지 않습니다. 현재 하고 있는 일은 setNickname을 수행할 수 있는지 여부를 반환하고 있습니다. setNickname은 할 수 있더라도 그게 valid한 값이 아닐 수 있습니다.
2. ‘aa’에서 ‘aa2’처럼 숫자를 입력하면 이름은 4자까지 입력 가능하다는 에러메세지가 뜨고있습니다. '숫자를 입력할 수 없다'라는 에러메세지가 떠야합니다.
3. 공백을(‘ ‘) 입력하면 name.length !== 0이 아니기 때문에 true가 되어 다음 단계로 넘어갈 수 있습니다. 올바른 이름이 아니므로 넘어가면 안됩니다.
이 pr본문에서 validateMemberName은 기니까 `검증 함수`로 줄여서 지칭하겠습니다! 
이름의 유효 갈이는 0자 초과 4자 이하여야 합니다. 따라서 검증 함수에서 4까지 slice하고 0이상임을 확인하도록 했습니다.
```js
const slicedName = name.trim().slice(0, RULE.maxMemberNameLength);
const validateLength = () => {
return slicedName.length > 0;
};
```
그냥 validateLength에 넣으면 되지 왜 slice를 하는 건지 의문이 들 텐데요.
validateLength에서 && 로 함께 최대 길이를 검증할 경우 초과 입력의 경우 isValid가 false가 되기 때문입니다. 하지만 input안에 이름은 4자까지만 입력되기 때문에 초과 입력이 …
=> [FE] 행사 생성 시 관리자 이름 유효성 검사가 올바르게 수행되지 않는 버그와 그 외

client/src/hooks/useSendPage.ts, client/src/utils/navigateApp.ts
- close #871 
두 어플을 사용하지 않는 사용자는 송금하기 기능을 이용할 수 없습니다. 그래서 최후의 선택으로 복사하기 기능을 제공하여 사용자가 직접 송금할 수 있는 방법을 두었지만, 토스, 카카오페이를 선택한 후 송금하기를 클릭하면 아무런 반응이 일어나지 않는 에러가 있었습니다. 이 때 사용자에게 적절한 안내를 주어야 한다고 생각했기 때문에 설치를 위한 앱스토어로 이동하도록 기능을 추가했습니다.
지금 설정은 노트북에서 토스 송금하기가 보이지 않도록 설정했지만 악의적인 조작으로 보이게 할 수 있습니다. 이 때도 예외처리를 적용하여 아래와 같이 토스트를 보여주도록 했습니다.
버튼을 클릭한 후 일정 시간을 기다렸지만 앱이 실행되지 않는 경우, 앱이 설치되지 않은 것이라 판단하여 설치 링크로 이동할 수 있도록 기능을 구현했습니다. 여기서 Android와 IOS가 다르게 이동해야 하기 때문에 각각 다른 주소를 넣어줬습니다.
이 때도 '앱이 설치되지 않았어요. 설치 후 이용해주세요' 라는 토스트를 보여줍니다.
=> [FE] 토스/카카오톡 앱이 없을 때 앱스토어로 이동할 수 있도록 개선

client/src/apis/endpointPrefix.ts, client/src/apis/request/event.ts, client/src/pages/event/[eventId]/admin/edit-account/EditAccountPage.tsx
- close #887 
행사의 계좌번호와 유저의 계좌번호를 분리하기로 결정하게 되어 기존의 행사 계좌 번호를 준비되어있는 행사 계좌 번호 수정 api를 사용하여 수정합니다.
EditAccountPage에서 EditAccountPageView 의 onSubmit인자로 넘겨줄 api 콜 함수만 행사 계좌 번호 수정 api로 변경해주었습니다.
```jsx
const EditAccountPage = () => {
const {bankName, accountNumber} = useEventDataContext();
const {patchEvent} = useRequestPatchEvent(); // 여기만 다른 api로 연결
const location = useLocation();
const redirectUrlOnSubmit = `/${getEventBaseUrl(location.pathname)}/admin`;
return (
<EditAccountPageView
bankName={bankName}
accountNumber={accountNumber}
onSubmit={patchEvent}
redirectUrlOnSubmit={redirectUrlOnSubmit}
/>
);
};
```
그리고 `useRequestPatchEvent`는 리스폰스 바디가 없으므로 `requestPatchWithoutResponse`를 사용해 PATCH요청을 보내도록 수정했습니다.
=> [FE] 행사 계좌 번호 수정 api 연결

.github/workflows/frontend-dev-deploy.yml, .github/workflows/frontend-prod-deploy.yml
- close #868 
이전에는 AWS의 access key를 발급 받을 수 없어 S3에 접근할 수 있는 권한이 없었습니다. 그래서 AWS Pipeline을 사용해서 S3에 배포했었는데 이제는 AWS access key를 발급 받을 수 있어 github action으로 CD 체계를 변경했습니다.
github action으로 옮겼을 때의 장점은 env의 수정 사항이 생겼을 때 aws에 로그인하지 않고 github secrets를 수정하면 돼서 간편하다는 것이라고 생각합니다.
개발 환경은 fe-dev에 push 될 때, 운영 환경은 main에 push 될 때 action이 발생하도록 설정했습니다. 또한 paths 설정으로 client 파일이 수정됐을 때만 action이 실행됩니다.
fe-dev를 base로 올라온 pr이 fe-dev에 머지, main을 base로 올라온 pr이 main에 머지될 때 action이 발생하여 배포가 되는 설정입니다.
```yml
defaults:
run:
shell: bash
working-directory: ./client
```
github action 환경에서 실행될 디렉토리를 먼저 설정해줍니다. 
```yml
- name: Checkout code
uses: actions/checkout@v4
- name: Set up Node.js
uses: actions/setup-node@v4
with:
node-version: "20.15.1"
- name: Install Dependencies
run: npm install
```
여기까지는 기존의 …
=> [FE] Frontend CD 환경 재구축

client/src/constants/routerUrls.ts, client/src/pages/event/[eventId]/admin/edit-event-name/EditEventNamePage.tsx, client/src/pages/mypage/MyPage.tsx, client/src/pages/mypage/edit-nickname/EditUserNicknamePage.tsx, client/src/router.tsx
- close #910 
회원을 위한 서비스 중 닉네임 저장하기 기능을 구현하고자 합니다. 해당 기능은 행사를 생성할 때 주최자의 닉네임 작성이라는 단계를 줄여주고자 도입했습니다. 이를 통해, 회원은 비회원과 달리 행사 생성 단계를 줄일 수 있어 빠르게 행사 생성이 가능합니다.
회원은 마이페이지에서 `닉네임 변경하기` 탭을 클릭하여 기존에 입력했던 닉네임을 수정할 수 있습니다.
- `닉네임 변경하기`를 `이름 변경하기`로 수정
닉네임이라는 단어를 사용할 경우 유저가 **익명성의 이름을 작성하라는 것처럼** 받아드릴 것이라고 생각했습니다. 
우리의 서비스는 익명성 사용이 유도될 필요가 없는 서비스라고 판단했기 때문에 `닉네임 → 이름`으로 워딩을 변경했습니다. 또한, 그간의 서비스에서 사용한 워딩이 `참여한 사람`, `이름` 등으로 사용했기에 통일성을 주고자 닉네임이 아닌 이름을 사용한 이유도 있습니다.
**🚨유저에게 보이는 페이지에서만 이름으로 변경했을 뿐, 개발에서 사용되는 용어는 그대로 nickname을 사용했습니다!**
- 이름 변경하기 페이지
Top 컴포넌트의 text에 `변경할 이름` 이라는 워딩을 넣는 것이 좋을지 고민하였습니다만. 
마이페이지에서 이름 변경하기를 클릭한 후 해당 페이지로 이동하기 때문에 **변경 이라는 워딩을 넣지 않아도 된다고 생각**하여 다음과 같이 작성하였습니다. 
- 이름 유효성 검사 및 onChange
기존에 비회원으로 행사 생성을 진행하면 `관리자 이름`을 입력하는 단계가 존재했습니다. 해당 단계에서 `useMemberName`이라는 hook을 사용하고 있었습니다. …
=> [FE] 회원 이름 변경 구현

.github/workflows/frontend-dev-deploy.yml, .github/workflows/frontend-prod-deploy.yml
- close #916 
이전 방식은 빌드 과정에서 env를 secret으로 넣어줬지만 정상적으로 환경 변수가 들어가지 않는 문제가 있었습니다.
그래서 빌드 전에 env 파일을 만드는 과정을 추가하여 환경 변수가 작동하도록 설정했습니다.
dev는 .env.dev를 만들고 prod는 .env.prod를 만들도록 설정하여 이제 빌드 과정에서 env가 없는 문제가 일어나지 않게 됐습니다.
```yml
- name: Create environments from github secrets
run: |
echo "API_BASE_URL=${{ secrets.API_BASE_URL }}" >> .env.dev
echo "AMPLITUDE_KEY=${{ secrets.AMPLITUDE_KEY }}" >> .env.dev
echo "KAKAO_JAVASCRIPT_KEY=${{ secrets.KAKAO_JAVASCRIPT_KEY }}" >> .env.dev
echo "IMAGE_URL=${{ secrets.IMAGE_URL }}" >> .env.dev
echo "KAKAO_REDIRECT_URI=${{ secrets.KAKAO_REDIRECT_URI }}" >> .env.dev
echo "SENTRY_AUTH_TOKEN=${{ secrets.SENTRY_AUTH_TOKEN }}" >> .env.dev
- name: Build for Dev environment
run: npm run build-dev
```
fork한 레포지토리로 확인해 본 결과 문제 없음을 확인했습니다 휴유
또한 어제 회의하며 echo를 실행하는 과정에서 …
=> [FE] CD 환경 변수 설정 버그 수정

client/src/pages/event/[eventId]/EventPageLayout.tsx, client/src/pages/mypage/MyPage.tsx
- close #914
카카오 로그인 프로필 연동을 선택하지 않을 경우 프로필 이미지가 alt로 띄워지는 문제가 존재합니다.
- 카카오 회원가입 시, 프로필 이미지를 연동하지 않음
정상적으로 동작했을 때와 버그 발생 상황의 요소를 비교해보면, 프로필 이미지를 연동하지 않았을 경우 source 태그의 srcset 값이 채워지고 있지 않음을 알 수 있습니다.
우선 Mypage에서 getImageUrl()을 통해 runningDog 이미지가 잘 불러와짐을 확인했습니다.
MyPage는 Profile 컴포넌트를 통해 회원 프로필 이미지를 불러오고 있습니다. Profile 컴포넌트에서 Image 컴포넌트를 사용하고 있고, Image 컴포넌트에서 src 값으로 runningDog이 출력되어야 하는 것이 정상적입니다. 그러나 출력되지 않는 것을 확인했습니다.
이는 Profile 컴포넌트에서 runningDog 이미지를 넘겨받고 있지 않고 있음을 뜻합니다.
- 프로필 이미지를 연동했을 경우
카카오 프로필 이미지를 연동했을 경우에는 Profile 컴포넌트에서 회원 프로필의 이미지 url을 정상적으로 받고 있습니다.
- 프로필 이미지를 연동하지 않았을 경우
- profileImage의 값이 false일 경우 Profile 컴포넌트로 값이 넘겨지지 않는 것으로 판단되었습니다.
문제는 profileImage의 값이 boolean으로 판단했을 때 false일 경우라고 생각했습니다.
- 이전 코드
```tsx
<Profile src={profileImage ?? getImageUrl('runningDog', 'png')} …
```
=> [FE] 카카오 로그인 프로필 연동을 선택하지 않을 경우 프로필 이미지 alt로 띄워지는 문제

client/src/hooks/queries/bill/useRequestDeleteBill.ts, client/src/hooks/queries/bill/useRequestPostBill.ts, client/src/hooks/queries/bill/useRequestPutBill.ts, client/src/hooks/queries/bill/useRequestPutBillDetails.ts, client/src/hooks/queries/member/useRequestPostMembers.ts, client/src/hooks/useEditBillActions.ts, client/src/hooks/useMembersStep.ts
- close #921 
| 지출 내역을 추가할 때 인원을 추가하는 경우             | 지출 내역을 수정하는 경우            |
|--------------------------------------|--------------------------------------|
| ![image1](https://github.com/user-attachments/assets/dc7d37c2-f2a3-488c-9239-ff896b57fc80) | ![image2](https://github.com/user-attachments/assets/f7cabbea-3d06-46b8-9df2-655b93f2430a) | 
<table>
<tr>
<td>
</td>
<td>
</td>
<td>
</td>
</tr>
</table>
___ 
개선 전의 모습을 보면 지출 내역 추가 시 api 호출이 총 5번이 일어나는 모습을 확인할 수 있고 그 중 **current api는 두 번 요청되는 모습**을 확인할 수 있습니다. 이 문제를 발견 후 각 페이지 별 캐시 상태를 비교해봤습니다.  (위 세 번째 사진 참고)
여기서 주목할 데이터는 `currentMembers` 입니다. 지출 내역 추가 후 관리 페이지로 이동한 후에는 currentMembers 데이터가 필요하지 않지만 두 번이나 서버로 요청을 보내는 문제가 있었습니다.
useRequestPostMembers와 useRequestPostBill hook에서 mutate 실행 후 invalidate를 해주는 과정에서 불필요한 api가 호출되었습니다.
우선 …
=> [FE] api 호출 개선 : 지출 내역 과정

client/src/components/Loader/EventData/EventDataLoader.tsx, client/src/components/Loader/EventData/EventDataProvider.tsx, client/src/hooks/queries/auth/useRequestPostAuthentication.ts, client/src/hooks/useAdminPage.ts, client/src/hooks/useEventLoader.ts, client/src/hooks/useEventPageLayout.ts, client/src/hooks/useMembersStep.ts, client/src/pages/event/[eventId]/home/HomePage.tsx
- close #922 
이벤트 페이지 접속 시 같은 api 요청이 7~8번씩 발생하는 문제가 있었습니다.
event, steps, reports, all members 요청이 반복적으로 실행되어 초기에 30번 이상 요청을 보내는 모습을 보고 경악을;;;;;;
다행이 원인을 발견하였고, SuspenseQueries의 initialData를 설정해주지 않아서였습니다.... 
suspenseQueries 옵션으로 initialData를 설정하고 initialDataUpdatedAt: 0을 설정했습니다.
initialDataUpdatedAt: 0을 설정한 이유는 이를 설정하지 않으면 초기 데이터를 화면에 보여주고 api 요청을 보내지 않게 되기 때문입니다.
```tsx
{
queryKey: [QUERY_KEYS.event, eventId],
queryFn: () => requestGetEvent({eventId}),
initialData: {eventName: '', bankName: 'KB국민은행', accountNumber: '', createdByGuest: true},
initialDataUpdatedAt: 0,
},
```
이렇게 하고 끝났을 때 문제가 하나 생겼습니다. 바로 Suspense의 Fallback 컴포넌트가 보이지 않게 된 것이었습니다.
SuspenseQueries를 적용한 이유가 로딩 화면을 선언적으로 보여주기 위함인데 이렇게 되어버리면 Suspense를 적용하는 의미가 없어진다고 생각했습니다. …
=> [FE] api 호출 개선 : 이벤트 페이지 진입 시 같은 api 7개씩 호출되는 문제

client/src/hooks/useAccount.ts, client/src/utils/validate/validateAccountNumber.ts
- close #657 
validate 길이를 체크하는 함수에서 공백과 대시를 제거해서 세도록 변경했습니다.
아주 오래된 이슈를 털었어요 드디어ㅋㅋㅋ
| 30자 이상이어도 대시가 포함되면 정상             | 8자여도 대시가 포함되면 오류 메시지              | 공백도 위와 동일                           |
|--------------------------------------|--------------------------------------|--------------------------------------|
| ![image1](https://github.com/user-attachments/assets/1c40bc4f-f762-4050-8d9c-00592d37c256) | ![image2](https://github.com/user-attachments/assets/688df640-805b-4055-a7ac-54d3683d368a) | ![image3](https://github.com/user-attachments/assets/5a1c1d42-c1d5-4ee1-a9dc-b389a8ae5c0f) |
=> [FE] 계좌번호 입력 제한 글자 수 세는 정책 변경

client/src/apis/request.ts
- close #702 
API_BASE_URL에서 널 병합 연산자 제거했습니다.
global.d.ts에서 env에 대한 타입이 string으로 단언 되었으므로 undefined를 고려하지 않아도 됩니다.
=> [FE] API_BASE_URL에서 널 병합 연산자 제거

client/src/hooks/useEventMember.ts, client/src/pages/event/[eventId]/admin/members/MemberPageType.ts, client/src/pages/event/[eventId]/admin/members/MembersPage.style.ts, client/src/pages/event/[eventId]/admin/members/MembersPage.tsx
- close #934
- 버그 발생 페이지 : 전체 참여자 관리
- 버그 발생 상황: 참여자 이름 변경을 위해 input에 값을 지울 경우
- 버그: 글자가 1개 남았을 경우 더이상 값이 지워지지 않음
- 예상 정상 작동 결과: input에 값이 모두 지워지고 placeholder 문구가 보여야 함
https://github.com/user-attachments/assets/eb9db413-f221-4e6b-9dd6-1716a7211c3e
4주전 task에서 validateMemberName 함수에서 member의 글자수를 체크하는 validateLength의 범위가 변경되었습니다.
- 기존 (0도 포함)
```tsx
const validateLength = () => {
return slicedName.length >= 0;
};
```
- 변경 (0 미포함)
```tsx
const validateLength = () => {
return slicedName.length > 0;
};
```
이전에는 제가 구현하면서 글자수 범위를 0도 포함하도록 구현했었습니다. validateMemberName을 사용하는 곳에서 0일 경우 버튼 submit이 불가능하도록 막았습니다.
이런 방식은 validate라는 이름이 붙은 함수와는 부적합하다는 것을 이번 버그를 해결하는 과정에서 느꼈습니다.
0을 포함하여 validate 함수를 구현했기 때문에 추후 다른 작업에서 validateMemberName을 사용하면서 혼동을 야기했습니다.
validateMemberName에서의 validateLength는 변경되었던 것처럼 …
=> [FE] 전체 참여자 관리 : 참여자 이름이 1개 남았을 경우 지울 수 없는 버그

client/src/pages/event/[eventId]/admin/members/MembersPage.style.ts
- close #939 
MemberPageStyle에서 플레이스 홀더에 들어가는 폰트 색상에 관한 스타일이 2개 있는 것을 배포과정에서 발견했습니다.
따라서  플레이스홀더 폰트 스타일 색상을 그레이 색상 하나만 적용시켜뒀습니다.
=> [FE] 스타일에 플레이스 홀더가 두개 들어가있는 문제 해결

client/src/hooks/useMembersStep.ts
- close #944 
eventName을 가져오기 위해 useEventDataContext를 사용했지만 실제로 context로 감싸지지 않아서 오류가 발생했습니다.
그래서 useRequestGetEvent를 사용해서 데이터를 불러오는 방식으로 변경했어요.
이 오류를 보면서 router.tsx도 같이 정리가 됐으면 하는 바람도 있습니다.
원래는 행사 페이지 안에 지출 내역 추가가 있지만 router.tsx에는 그렇지 않아서요..
=> [FE] 지출 내역 인원 변동 step으로 들어갈 때 provider 오류

client/src/components/Design/components/Icons/Svg.style.ts, client/src/components/Design/components/Icons/Svg.tsx
- close #947 
현재 iOS에서 svg아이콘이 제대로 보이지 않는 문제가 있습니다.
이를 바로 잡기 위해 IconComponent를 변경합니다.
svg의 크기를 동적으로 조절하기 위해 
```tsx
export const svgStyle = css`
svg {
width: auto;
height: auto;
}
`;
```
처럼 사용했지만, 크롬에서는 부모의 위치에 맞도록 설정되지만, safari에선 fixed로 되는 것이 기본 설정이기 때문에, os에 따라서 다르게 보이는 문제가 있었습니다.
이에 아래와 같이 변경하였습니다.
```tsx
export const svgStyle = css`
width: 100%;
height: 100%;
svg {
width: 100%;
height: 100%;
}
`;
```
=> [FE] iOS에서 아이콘이 제대로 보이지 않던 문제

.github/auto_assign.yml, .github/workflows/frontend-sync-issue-to-pr.yml
- close #953 
이전에 잘 돌아가던 action이 어느 순간부터 돌아가지 않게 되어 문제를 분석한 결과 secret의 CONFIG_SUBMODULE_TOKEN이 만료된 것이 원인이라는 것을 알게 되었습니다.
이를 새로 발급 받아 넣어줬을 때 정상 작동함을 확인했습니다. 여기서 이슈를 끝내기 아쉬워서 지금까지 불편하다고 생각했던 것을 이왕에 개선해보기로 했습니다.
**불편한 점: PR을 만들고 난 뒤 손수 Reviewers, Assignees, Labels, Projects, Milestone, Project status In Review 설정, issue In Review 설정을 해줘야 한다는 것이 너무 번거로움**
이것을 자동으로 해줄 수 있다면 너무 편해지지 않을까 해서 개선을 시도했습니다.
marketplace의 [kentaro-m/auto-assign-action@v2.0.0](https://github.com/kentaro-m/auto-assign-action/tree/v2.0.0/)을 사용하여 구현했습니다.
./github/auto_assign.yml에서 설정을 수정할 수 있습니다.
PR이 생성될 때 자동으로 Reviewer를 달고 그 목록을 우리 프론트엔드 멤버로 구성했습니다. 
또한 assignees는 PR을 생성하는 사람으로 설정했습니다. 예로 제가 PR을 생성하면 Assignees에는 제가 할당되고, Reviewer에는 토다리, 웨디, 소하가 설정됩니다. 너무 편하겠죠~ㅋㅋ
```yml
addReviewers: true
addAssignees: author
reviewers:
- …
```
=> [FE] Github PR create, close 할 때 관련 이슈 status 조정

client/src/constants/errorMessage.ts, client/src/constants/rule.ts
- close #966
이름 변경을 시도할 때, 제한한 글자수(8자)를 넘겨서 서버에 전송할 경우 서버에서 에러 메세지를 넘겨줍니다.
이때 토스트로 출력되는 에러 메세지는 "멤버 이름은 한글 30자까지, 영어 60자까지 입력이 가능해요." 입니다.
이 메세지는 현재 우리 서비스 정책과 맞지 않습니다.
https://github.com/user-attachments/assets/2058559b-3000-42e4-905c-e9e101015fd2
이 에러 메세지는 프론트 측에서 서버 측에서 넘겨주는 에러 코드를 확인하여 이에 맞는 에러 메세지를 가지고 있다가 유저에게 토스트로 출력해주는 것이었습니다. 즉, 프론트측에서 해당 코드와는 맞지 않은 메세지를 가지고 있던 것이었습니다.
에러 메세지 문구를 동일하게 수정했습니다.
https://github.com/user-attachments/assets/cf6f1fa4-d677-4c64-b694-66f086fb46ae
프론트는 maxEventNameLength의 값이 30이었습니다. 그런데 서버는 maxEventNameLength가 20이었습니다. 따라서 행사 이름이 20글자 넘게 입력이 가능했고 그 상태로 변경을 요청했을 경우 서버측에서 에러를 발생시켰습니다.
따라서 프론트측도 서버와 동일하게 maxEventNameLength의 값을 20으로 수정했습니다.
=> [FE] 이름 변경 글자수 서버 에러 메시지 버그 + 다양한 서버 에러 메세지 수정

server/src/main/java/haengdong/event/application/EventMemberService.java, server/src/main/java/haengdong/event/domain/event/member/UpdatedMembers.java, server/src/test/java/haengdong/application/EventEventMemberServiceTest.java, server/src/test/java/haengdong/domain/eventmember/UpdatedMembersTest.java
- close #963
/api/admin/events/{eventId}/members
```json
{
"members" : [ 
{ 
"id" : 1, 
"name" : "토다리", 
"isDeposited": true 
},
{ 
"id" : 2, 
"name" : "망쵸", 
"isDeposited": false 
}
]
}
```
멤버 정보 수정 API 호출시 누락된 member는 자동으로 삭제 됩니다. 
(id 1,2,3 인 멤버가 존재하는 경우 id 1,2 만 수정 요청시 id 3은 삭제됨)
=> [BE] 인원 수정 및 삭제 API 통합

client/src/components/Design/components/ContentItem/ContentItem.tsx, client/src/pages/main/MainPage.tsx
- close #975 
MainPage에 TopNav를 적용합니다.
톱니바퀴를 누르면 /setting으로 이동합니다.
editIcon에 size를 사용하지 않고 있길래 수정했어요!
=> [FE] 메인 페이지에 TopNav 적용

client/src/pages/login/LoginRedirectPage.tsx
- close #986 
LoginRedirectPage의 route 설정을 `navigate(ROUTER_URLS.createUserEvent)`에서 `navigate(ROUTER_URLS.main)`으로 변경했습니다.
=> [FE] 로그인 후 행사 생성이 아닌 메인 페이지로 이동

client/src/pages/event/[eventId]/EventPageLayout.tsx
- close #990 
머지하면서 navigate 함수를 중복 사용한 채로 적용이 되어버려서 해결했습니다.
=> [FE] 머지하면서 잘못 병합된 코드 해결

client/src/hooks/useEventPageLayout.ts, client/src/hooks/useShareEvent.ts, client/src/pages/event/[eventId]/EventPageLayout.tsx
- close #995 
링크 공유할 때 참여자 이름을 추가해서 쉽게 언급할 수 있도록 했습니다.
크루위키 문서 속 이미지를 가져오는 방식이 아닌, 우리 서비스 내에서 가져오도록 바꿨습니다.
=> [FE] 링크 공유 시 참여자 이름 넣기

.github/workflows/frontend-dev-deploy.yml, .github/workflows/frontend-prod-deploy.yml, client/package-lock.json, client/package.json, client/src/index.tsx, client/tsconfig.json, client/webpack.common.mjs, client/webpack.dev.mjs, client/webpack.prod.mjs
- close #1000
(영광의 1000번째 브랜치!!! 다들 1000번까지 달리느라 고생많았습니다..)
- 3회 측정 후 평균낸 값 기준으로는 빌드 시간이 build: 27초, build-dev: 13초로 많이 느립니다. 배포 결과 확인이 느려서 불편할 정도입니다. 
- 웹팩 말고도 전반적으로 빌드 속도에 영향이 미치는 부분을 수정했습니다.
- webpack dev 빌드 세팅에 터서 최적화가 적용되어 있습니다. dev모드에서는 큰 의미가 없는 최적화입니다.
- prod에서 불필요하게 소스맵이 공개되고 있습니다.
- 그 외 이런저런 불필요한 옵션이나 쓰면 좋을 옵션들을 추가하려 합니다.
**목차**
[1] webpack prod 환경에서의 빌드 최적화
[2] 환경 별로 올바르게 소스맵 규칙 수정
[3] [hash] deprecated 오류 제거
[4] emotion pragma 삽입 코드 제거
[5] workflow에서 node_modules 캐싱
[6] sentry제거
[7] terser optimization
prod 환경에서 적용할 수 있는 빌드 최적화 방법은 다음과 같습니다. 
현재 ts-loader, ForkTsCheckerWebpackPlugin 에 의해 타입이 중복 검사되고 있습니다.
ts-loader는 트랜스 파일링 용도로만 사용하고 타입 검사는 사용하지 않도록 합니다. 타입 검사에는 ForkTsCheckerWebpackPlugin만 사용하도록 수정했습니다.
그럼 ts-loader만 사용하고 ForkTsCheckerWebpackPlugin은 깔지 않아도 되지 않냐고 할 수 있는데, 별도의 …
=> [FE] webpack build, buld-dev 속도 개선

client/src/components/Design/components/Banner/Banner.tsx, client/src/components/Design/components/Banner/Banner.type.ts, client/src/components/Design/components/SendButton/SendButton.tsx, client/src/pages/event/[eventId]/home/HomePage.tsx
- close #1009 
행사의 관리자가 해당 행사의 계좌번호를 입력하지 않았을 경우, 다음과 같이 `금액복사` 버튼이 나타나게 됩니다. 이때, 금액 복사를 클릭할 경우 금액만 복사가 되고 계좌번호는 복사되지 않습니다.
추가로 입금이 완료되었을 경우에는 `금액복사` 버튼이 나타나면서 아무런 상호작용도 존재하지 않습니다.
아래는 계좌번호 입력이 완료되었을 경우의 화면입니다.
관리자가 행사의 계좌번호를 입력했을 경우, 참여자는 다음과 같이 `송금완료` 혹은 `송금하기` 버튼이 나타나게 됩니다.
- 행사에 입력된 계좌번호가 없을 경우에 `참여자는 계좌번호가 존재하지 않음을 인지할 수 없음.`
- 계좌번호를 입력하지 않았고 송금이 완료된 경우에 `금액복사 버튼이 출력됨.` → 이는 송금이 되었는지 혼동을 줄 수 있음.
- 행사에 입력된 계좌번호가 없을 경우, 참여자에게 계좌번호가 존재하지 않음을 인지할 수 있도록 Banner를 활용하여 알림 띄우기.
- 계좌번호가 입력되지 않았고 송금이 완료된 경우에는 `금액복사` 버튼이 아닌 `송금완료` 버튼이 출력되도록 수정하기
행사에 등록된 계좌번호가 없을 경우, 참여자가 주로 보게 되는 ‘홈 페이지’에 Banner를 활용하여 주최자가 계좌번호를 등록하지 않아 금액만 복사가 가능하다는 알림을 띄웁니다.
- Banner 컴포넌트 buttonText 필수 입력을 선택 입력으로 변경
기존에는 Banner 컴포넌트에 버튼이 필수적으로 필요했습니다.
그러나, 참여자가 주로 보는 ‘홈 페이지’에는 Banner를 활용할 때 해당 버튼이 필요 없다고 판단했습니다. 참여자가 주최자에게 …
=> [FE] 관리자 계좌번호 미입력시 참여자 Banner 알림

client/src/hooks/useAccount.ts
- close #1016 
#634 이 이슈에서 구현한 기능(신한은행 1021-12312-1123 문자열이 붙여넣기 될 때 1021-12312-1123만 남는 기능 구현)이 작동하지 않는다는 것을 확인했습니다.
paste 콜백 안에서 handleAccount를 사용해 정제하려고 했지만 정규식에 맞지 않는 문자열이 들어올 경우 '신한 1231-123123' canEditAccountNumber(newAccountNumber)가 false여서 accountNumber를 갱신하지 않는 문제가 있었습니다. 즉, 붙여넣은 값이 canEditAccountNumber의 조건을 통과하지 못하면 input에 표시되지 않게 되는 버그가 있었습니다.
아래처럼 clipboardData.getData 해온 값을 정규식에 맞지 않는 문자를 대체하고 set해주는 방식으로 붙여넣기가 지원되도록 고쳤습니다.
```ts
const newAccountNumber = `${accountNumber}${event.clipboardData.getData('text')}`;
const validAccountNumber = newAccountNumber
.replace(/[^\d\s\-]/g, '')
.replace(/\s+/g, ' ')
.trim();
setAccountNumber(validAccountNumber);
```
붙여넣기 이벤트가 발생할 때 `onPaste`가 먼저 실행되고 뒤이어 `onChange`가 실행됩니다.
그래서 복사 붙여넣기가 되고 바로 onChange가 실행되어 정규식에 맞는지 검사를 하게 되며 이 때 change의 …
=> [FE] 계좌번호 복사 붙여넣기 기능이 작동하지 않는 버그 해결
